### ISSUE TITLE
rMATs without conditions

### ISSUE THREAD

**Issue by gouthamatla** [Xinglab/rmats-turbo#1]
Hi,

I have a quick question. Can I use rMATs without having two conditions ? I have large panel of samples and I am interested to calculate PSIs across samples. This could be used for QTL analysis or for identifying co-splicing modules ( like co-expression modules).

**Comment by EricKutschera** [comment]
Yes, you can list all of the BAM files that you want rMATS to process in the `--b1` file, omit `--b2`, and use `--statoff`. The PSI values will be calculated for each BAM and reported in the `IncLevel1` column of the `*.MATS.*` output files.

**Comment by yxing77** [comment]
I should also add that if you have a large dataset (as in the case of a
sQTL analysis), the --task option of rMATS 4.1.0 allows you to run the
'prep' step in a parallelized manner (which can be distributed over a HPC
cluster) to pre-process many fastq/bam files in parallel and generate a
compact splicing graph .rmats file for each sample, then you can run the
'post' step on all the .rmats files to identify alternative splicing events
and calculate PSI values. This will significantly speed up the computing
over very large datasets.

**Comment by gouthamatla** [comment]
Thanks for this useful tip. How the .rmats files should be given to --task post ? I see that the .rmats files are generated in tmp folder and given a timestamp (e.g 2020-06-03-22:22:14_936865.rmats )

**Comment by ywang1993** [comment]
> Thanks for this useful tip. How the .rmats files should be given to --task post ? I see that the .rmats files are generated in tmp folder and given a timestamp (e.g 2020-06-03-22:22:14_936865.rmats )

You can run the code with `--task post`, providing another b1/b2 file containing all bam files you used in `--task prep` and the `--tmp` folder containing all `.rmats` files generated by prep step. 
Make sure that 1) the path (and name) of bam files in b1/b2 matches the path (and name) you used when running the `--task prep`. 2) the `--tmp` folder contains and only contains `.rmats` file required in b1/b2.
