### ISSUE TITLE
Cannot detect events on several chromosomes

### ISSUE THREAD

**Issue by NancyZhang97** [Xinglab/rmats-turbo#102]
Hi! Thank you so much for your nice tool. I met another problem when I used rMATs for single sample's AS event detection. I ran 24 bam files from different sources with rMATs 4.4.1 and the same annotation gtf file. After deleting events with NA Inclevel in [AS_Event].MATS.JC.txt and calculating the counts of AS events on each chromosome, I found that only a few chromosomes had detected AS events, like chr9 and chr11. Many chromosomes, like chr1, chr2, chr3 and chr4, don't have AS events in all of 24 JC output files. I check fromGTF.[AS_Event].txt and all of chromosomes have detected AS events and the counts are proportional to the size of chromosomes. I also check my bam files and cannot find anything weird. 
I wonder if it is caused by some input format issues. Is there any requirement for the annotation gtf and bam file, for example,  the order of chromosome or the format of chromosome (like "chr1" vs "1")?

I use single group and --stat-off. Here is one of my running output:

> gtf: 33.7247970104
There are 60676 distinct gene ID in the gtf file
There are 227818 distinct transcript ID in the gtf file
There are 36763 one-transcript genes in the gtf file
There are 1376499 exons in the gtf file
There are 25269 one-exon transcripts in the gtf file
There are 22508 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.754664
Average number of exons per transcript is 6.042099
Average number of exons per transcript excluding one-exon tx is 6.671126
Average number of gene per geneGroup is 8.463790
statistic: 0.0316829681396

> read outcome totals across all BAMs
USED: 36831575
NOT_PAIRED: 0
NOT_NH_1: 7516282
NOT_EXPECTED_CIGAR: 1433343
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 30469834
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 19461039
CLIPPED: 7539706
total: 103251779

> novel: 534.252084017
The splicing graph and candidate read have been saved into /home/Multiple_grp/R063_I/R063_I_temp/2021-03-19-19:39:22_751874_*.rmats
save: 0.944915056229
loadsg: 0.00835704803467

> ==========
Done processing each gene from dictionary to compile AS events
Found 49236 exon skipping events
Found 3403 exon MX events
Found 16624 alt SS events
There are 10098 alt 3 SS events and 6526 alt 5 SS events.
Found 6995 RI events
==========

> ase: 2.99896907806
count: 1.56597781181
Processing count files.
Done processing count files.

**Comment by EricKutschera** [comment]
rMATS should handle either 'chr1' or '1'. It will prepend 'chr' if it is lacking from either the gtf or bam (or both). The files do not need to be sorted either

From the output it does look like the alignments in your bam are not matching up with the exon coordinates in the gtf:
```
USED: 36831575 (~35.7%)
EXON_NOT_MATCHED_TO_ANNOTATION: 30469834 (~29.5%)
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 19461039 (~18.8%)
total: 103251779
```

Those `NOT_MATCHED_TO_ANNOTATION` results happen when the alignment passes all the other checks, but it cannot be matched to the coordinates in the gtf. It could be that the reference data (fasta, gtf) used to create the bam file does not use the same coordinates as the gtf input to rMATS. Since rMATS is matching alignments to events on chr9 and chr11 it might just be that for those chromosomes the reference files used for the bam have consistent coordinates with the gtf. Do you know what reference files were used to create the bam?

Since almost 50% of the alignments are marked as `NOT_MATCHED_TO_ANNOTATION` you could try randomly grabing some alignments and trying to manually match them up with the gtf file. That might give more insight into the problem

**Comment by NancyZhang97** [comment]
Thank you for your advice! I check the header of the bam file and use the same gtf file for running rMATs. The result shows better on `NOT_MATCHED_TO_ANNOTATION`. However, I notice that, when I run bam files with paired reads (using the same gtf as alignment) there are still many reads rMATs thinks they are `NOT_PAIRED`, like:

> read outcome totals across all BAMs
USED: 37992027
NOT_PAIRED: 147986730
NOT_NH_1: 31802222
NOT_EXPECTED_CIGAR: 1157072
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 15025513
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 38416
CLIPPED: 0
total: 234001980

I use samtools to check the bam file and it shows that all 234001980 are paired, but rMATs thinks most of them are unpaired. Do you have any idea what caused it?

**Comment by EricKutschera** [comment]
Here's where rMATS checks for `NOT_PAIRED`: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L276

It's checking `IsProperPair()` which is bit 2 of the flags from the SAM spec: https://samtools.github.io/hts-specs/SAMv1.pdf defined as "each segment properly aligned according to the aligner". It might be that your reads are marked as paired but not as properly paired

If you run `samtools stats {/path/to/file.bam} | grep 'pair'` you should see something like:
```
reads properly paired: {count} # proper-pair bit set
reads paired: {count} # paired-end technology bit set
```

**Comment by NancyZhang97** [comment]
Oh so rMATs only consider propoerly mapped reads. Thank you so much for answering my question!
