### ISSUE TITLE
Number of threads not working for running the statistical model separately?

### ISSUE THREAD

**Issue by boehmv** [Xinglab/rmats-turbo#104]
Hi Eric and all of the rMATS-team,
first of all, thank you for providing this great tool and constantly updating rMATS-Turbo! 

I have a question concerning the workflow of separating prep, post and stat tasks.

When I ran a test comparison (3-vs-3 bam files) with the "both" task, everything worked out fine and quite fast. 

Now, I wanted to run 50 bam files as described (https://github.com/Xinglab/rmats-turbo#running-prep-and-post-separately), which worked fine until after the post task. 

I am currently trying to run the separate "stat" task for individual comparisons. This seems to work, but it only uses one thread, which is thus pretty slow right now (still running since 2h ); no matter which "nthread" or "tstat" value I provide (I have tried various combinations).

![grafik](https://user-images.githubusercontent.com/52288457/112967715-d78f4e80-914b-11eb-9f97-3bd576bb3dba.png)

The following example command was used for the separate stat task:
`python rmats.py \
--od /rMATS/Output/control_vs_knockdown/ \
--tmp /rMATS/Output/control_vs_knockdown/ \
--tstat 10 \
--task stat`

I suspect that "tstat" is not properly handed over to rMATS_C/rMATSexe, but I cannot see where the problem might come from. Could it be an issue with the rMATS installation? Any idea from your side?

I am using rMATS v4.1.1; installed via bioconda on Ubuntu 18.04.4 LTS.

Thanks a lot in advance.

**Comment by EricKutschera** [comment]
I was able to install v4.1.1 from bioconda and see multiple cores being utilized in `htop`. I installed rMATS with: `conda install -c conda-forge -c bioconda rmats=4.1.1`

Here's the test data set that I used: [test_stat_thread_input.tar.gz](https://github.com/Xinglab/rmats-turbo/files/6230924/test_stat_thread_input.tar.gz)
With that data unpacked I ran: `rmats.py --od ./test_stat_thread_input --tmp ./tmp_dir --tstat 10 --task stat`

I had htop sorted by `PERCENT_CPU` (using F6) and could see the rMATSexe processes which included `-t 10` in the arguments to set the number of threads

If you can see multiple threads being used with the test data I attached, but not with your data, then there may be something about the files in your `--od` directory that is causing rMATS to spend a lot of time using 1 thread

Another possiblility is that OpenMP is not working properly in your setup. In that case you should only see 1 thread being used even with the test data. Here's the part of the code where rMATSexe is using OpenMP to run multiple threads: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_C/src/util.c#L462

If I change my command to `OMP_THREAD_LIMIT=1 rmats.py --od ./test_stat_thread_input --tmp ./tmp_dir --tstat 10 --task stat` then I only see 1 thread being used in `htop`

You could check to see if you have any OpenMP environment variables set with this command: `printenv | grep 'OMP'`

**Comment by boehmv** [comment]
Dear Eric,
thank you very much for your swift response and the detailed information. 

I have followed your recommendation and found that indeed rMATSexe uses the correct number of threads, both on the test set and on my own data. Sorry for raising any false alarm concerning this part of the analysis!

I have investigated more in detail and found the subsequent "rMATS_P/FDR.py" as the part of the analysis that takes quite some time (also since this step does not use multiple threads, does it?). I guess this is due to the large number of SE and MXE events, which in my case for the combined analysis were 1121131 (SE) and 1227202 (MXE) events?

I assume there is no simple "workaround" to speed up that part of the workflow? 

Again, thanks for your time and help!

**Comment by EricKutschera** [comment]
I took a look at FDR.py and you are right that it does not use multiple threads. I ran it with some test data of various sizes and it seems like the runtime may be quadratic.

(number of input rows: runtime in seconds): (10,000: 1), (20,000: 5), (40,000: 20), (80,000: 80)

If that pattern holds then it looks like it might take about 5 hours to run FDR.py on one of your files with 1.2 million events.

I think FDR.py could be improved to be much faster. This line looks like it may be the problem: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_P/FDR.py#L24 but I need to take a careful look

**Comment by EricKutschera** [comment]
I opened a pull request to improve the performance of FDR.py. I was able to run the new version on test data with a million rows and it finished in less than a minute. You could try downloading the new file and using it to replace the FDR.py from when you installed rMATS: https://github.com/Xinglab/rmats-turbo/blob/ff3491698436f3f72515524019bc2b1b0adef832/rMATS_P/FDR.py

**Comment by boehmv** [comment]
Thank you Eric, I forgot to give you feedback: your new FDR.py file worked perfectly and reduced runtime very much. Superb support from your side 👍
