### ISSUE TITLE
Correct after reading long, still no result，NOT_EXPECTED_READ_LENGTH: 0  

### ISSUE THREAD

**Issue by ouyang-lang** [Xinglab/rmats-turbo#109]
After correcting the long reading, there is still only the header but no content. Is there something wrong with my data? Single terminal data。

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 109630
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 5471503
total: 5581133
outcomes by BAM written to: out/2021-04-07-21:10:06_244106_read_outcomes_by_bam.txt

novel: 33.099395990371704
The splicing graph and candidate read have been saved into out/2021-04-07-21:10:06_244106_*.rmats
save: 0.0002880096435546875
loadsg: 0.0005803108215332031

==========

**Comment by EricKutschera** [comment]
Almost all of the reads are `CLIPPED` (5471503 out of 5581133). By default, rMATS does not use reads with soft or hard clipping operations in the alignment cigar. If you think that the alignment is ok with clipping, then you can tell rMATS to use those reads with `--allow-clipping`

**Comment by ouyang-lang** [comment]
Sorry, I don't quite understand this parameter. After I use the -- Allow-clipping parameter, the output result still only has the header without content. The specific content is as follows.

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 5581133
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 0
total: 5581133
outcomes by BAM written to: output/2021-04-08-15:31:20_818453_read_outcomes_by_bam.txt

novel: 33.96738290786743
The splicing graph and candidate read have been saved into output/2021-04-08-15:31:20_818453_*.rmats
save: 0.0002760887145996094
loadsg: 0.0005724430084228516

==========
Done processing each gene from dictionary to compile AS events
Found 19000 exon skipping events
Found 734 exon MX events
Found 8338 alt SS events
There are 5310 alt 3 SS events and 3028 alt 5 SS events.
Found 4086 RI events
==========

**Comment by ouyang-lang** [comment]
rmats.py --b1 ./b1.txt --b2 ./b2.txt  --gtf /data/gs/data/data1/reference/gencode.vM26.annotation.gtf --od output_b6 --tmp output  -t single  --nthread 6 --readLength 101  --allow-clipping

**Comment by ouyang-lang** [comment]
Since it is three generations of data, the BAM file obtained by comparison was obtained by minimap2 comparison

**Comment by EricKutschera** [comment]
All of your reads are now `NOT_NH_1` which means that they are not uniquely mapped. rMATS was designed to work with short-read sequencing data and expects uniquely mapped reads. It looks like you have long-read sequencing data which rMATS is not designed to analyze: https://github.com/Xinglab/rmats-turbo/issues/98

**Comment by ouyang-lang** [comment]
Okay, thank you. In other words, rmats has not been able to analyze ONT data, analyze ONT data, and still need to wait for the new version of the function, right?

**Comment by EricKutschera** [comment]
Yes, that's right

**Comment by ouyang-lang** [comment]
ok，thank you very much。

**Comment by ouyang-lang** [comment]
Then I would like to ask you, do you have any recommended software that can analyze the variable cutting events of ONT data? I look forward to the launch of the new function of rmats to analyze ONT data.

**Comment by EricKutschera** [comment]
There isn't any particular software that I would recommend. I'm not very familiar with these tools, but perhaps one of these would be useful to you:
https://github.com/BrooksLabUCSC/flair
https://github.com/LuyiTian/FLAMES
https://github.com/mortazavilab/TALON

There are probably other tools that exist that I do not know about that you may want to try

**Comment by EricKutschera** [comment]
We have released a new tool for long read data. See this post for more details: https://github.com/Xinglab/rmats-turbo/issues/98#issuecomment-1099257299
