### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by qicaibiology** [Xinglab/rmats-turbo#114]
Hi: 
I am trying to running the rmats-turbo version v4_1_1. I downloaded it directly in the server and tried to build it: 
what I have done is:
```
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ module load openblas
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ module load gsl
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ module load lapack
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ module load python
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ module load gcc
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ module load cmake
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ module load STAR
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ module load samtools
[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ gfortran --version
GNU Fortran (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Then I typed:
`[caiqi@midway2-login1 rmats_turbo_v4_1_1]$ ./build_rmats` 
```
cd bamtools; mkdir -p build; cd build; cmake ..; make;
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build
make[1]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[2]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[  0%] Built target SharedHeaders
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[  0%] Built target AlgorithmsHeaders
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[  0%] Built target APIHeaders
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[ 38%] Built target BamTools-static
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[ 39%] Linking CXX shared library ../../../lib/libbamtools.so
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[ 76%] Built target BamTools
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[ 80%] Built target jsoncpp
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[ 85%] Built target BamTools-utils
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[ 86%] Linking CXX executable ../../../bin/bamtools
make[3]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
[100%] Built target bamtools_cmd
make[2]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
make[1]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/bamtools/build'
cd bamtools/lib; rm *.so *.so.* *.dylib
rm: cannot remove '*.dylib': No such file or directory
make: [build] Error 1 (ignored)
cd rMATS_C; make;
make[1]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/rMATS_C'
cd lbfgs_scipy && make
make[2]: Entering directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/rMATS_C/lbfgs_scipy'
f77 -c -O2  -c -o lbfgsb.o lbfgsb.f
make[2]: f77: Command not found
make[2]: *** [lbfgsb.o] Error 127
make[2]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/rMATS_C/lbfgs_scipy'
make[1]: *** [lbfgs_scipy/lbfgsb.o] Error 2
make[1]: Leaving directory `/scratch/midway2/caiqi/rmats_turbo_v4_1_1/rMATS_C'
make: *** [build] Error 2

```

I don't know how to solve the error. ptyhon version is 3.7.6
Is there any advice on solving this issue (I have seen similar issue posted but it seems it already has the gfortan from the server)?

My second question is if I use conda3 to install it: `(base) [caiqi@midway2-login2 ~]$ conda install -c bioconda rmats`
do I still need to run the build step 
(it looks I also got error:
```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for notebook spyder nbconvert anaconda jupyterlab_pygments jupyter: : 340it [1:29:59,  3.82sExamining conflict for notebook spyder nbconvert anaconda jupyterlab_pygments jupyter: : 341it [1:29:59,  3.17sExamining conflict for distributed heapdict anaconda zict: : 341it [1:30:05,  3.17s/it]                        Examining conflict for anaconda-client anaconda-navigator anaconda anaconda-project: : 344it [1:30:22,  4.74s/iExamining conflict for anaconda-client anaconda-navigator anaconda anaconda-project: : 345it [1:30:22,  4.95s/iExamining conflict for flask anaconda werkzeug: : 345it [1:30:27,  4.95s/it]                                   Examining conflict for qt dbus pango harfbuzz gstreamer cairo gst-plugins-base glib: : 352it [1:30:44,  3.52s/iExamining conflict for rmats dbus harfbuzz gstreamer glib: : 353it [1:30:48,  3.52s/it]                     failed                                                                                    \                     

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment
pecifications:

  - alabaster -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|3.4.*|>=3.7,<3.8.0a0']
  - anaconda==2020.11 -> python[version='3.7.9|3.8.5',build='h7579374_0|h7579374_1']
  - argon2-cffi -> python[version='2.7.*|3.5.*|3.6.*|3.6.12|3.6.12|3.7.9|3.6.9|3.6.9|3.6.9|3.6.9|>=3.5,<3.6.0a0|3.4.*|3.7.*|3.9.*|3.8.*',build='0_73_pypy|1_73_pypy|5_73_pypy|4_73_pypy|3_73_pypy|2_73_pypy']
```?
in my anaconda3 I have:
```
(base) [caiqi@midway2-login2 ~]$ which python
~/anaconda3/bin/python
(base) [caiqi@midway2-login2 ~]$ python --version
Python 3.8.5
```
it looks I got a lot of conflicts during install.

Thanks for any comments

**Comment by EricKutschera** [comment]
For the error about `f77` not found, you should be able to tell the build where your fortran compiler is with `export FC="/path/to/gfortran"` similar to this post: https://github.com/Xinglab/rmats-turbo/issues/103#issuecomment-808488147

You don't need to build if you install from conda. Your error from the conda install might be that the build requires conda-forge. You could try `conda install -c conda-forge -c bioconda rmats=4.1.1`. It might be that the other things that you already installed in your base conda environment are incompatible with rmats. You can create a conda environment just for rmats with:
```
conda deactivate
conda create --prefix /path/to/new/directory/for/rmats_conda
conda activate /path/to/new/directory/for/rmats_conda
conda install -c conda-forge -c bioconda rmats=4.1.1
```
Then you would just need to activate that environment when you want to use rmats

**Comment by qicaibiology** [comment]
> conda create --prefix /path/to/new/directory/for/rmats_conda

Thanks for your reply. I tried to use conda to build a new enviroment but I got the following in the last step:
```
(base) [caiqi@midway2-login2 caiqi]$ conda activate /scratch/midway2/caiqi/conda_env_rmat_4_1_1/
(/scratch/midway2/caiqi/conda_env_rmat_4_1_1) [caiqi@midway2-login2 caiqi]$ conda install -c conda-forge -c bioconda ramts=4.1.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ramts=4.1.1

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/bcbio/linux-64
  - https://conda.anaconda.org/bcbio/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by qicaibiology** [comment]
> For the error about `f77` not found, you should be able to tell the build where your fortran compiler is with `export FC="/path/to/gfortran"` similar to this post: [#103 (comment)](https://github.com/Xinglab/rmats-turbo/issues/103#issuecomment-808488147)
> 
> You don't need to build if you install from conda. Your error from the conda install might be that the build requires conda-forge. You could try `conda install -c conda-forge -c bioconda rmats=4.1.1`. It might be that the other things that you already installed in your base conda environment are incompatible with rmats. You can create a conda environment just for rmats with:
> 
> ```
> conda deactivate
> conda create --prefix /path/to/new/directory/for/rmats_conda
> conda activate /path/to/new/directory/for/rmats_conda
> conda install -c conda-forge -c bioconda rmats=4.1.1
> ```
> 
> Then you would just need to activate that environment when you want to use rmats

I tried again this time to install rmats from the anaconda : `conda install -c bioconda rmats`
This time it looks I can get it installed, but when I tried to run using the following command:
`~/anaconda3/bin/python /scratch/midway2/caiqi/conda_env_rmat_4_1_1/rMATS/rmats.py --b1 /scratch/midway2/caiqi/Activity_rmats_analysis/b1.txt --b2 /scratch/midway2/caiqi/Activity_rmats_analysis/b2.txt --gtf /scratch/midway2/caiqi/gencode_ref_ms/transcripts.gtf -t paired --readLength 101 --nthread 4 --od /scratch/midway2/caiqi/Activity_rmats_analysis/DRB_vs_DRB_and_Bic/ --tmp /scratch/midway2/caiqi/Activity_rmats_analysis/tmp_output > log001 2> error001`

The error is:
```
Traceback (most recent call last):
  File "/scratch/midway2/caiqi/conda_env_rmat_4_1_1/rMATS/rmats.py", line 19, in <module>
    from rmatspipeline import run_pipe
ModuleNotFoundError: No module named 'rmatspipeline'
srun: error: midway2-bigmem01: task 0: Exited with exit code 1
```
What should I do to make it work?

**Comment by qicaibiology** [comment]
> > For the error about `f77` not found, you should be able to tell the build where your fortran compiler is with `export FC="/path/to/gfortran"` similar to this post: [#103 (comment)](https://github.com/Xinglab/rmats-turbo/issues/103#issuecomment-808488147)
> > You don't need to build if you install from conda. Your error from the conda install might be that the build requires conda-forge. You could try `conda install -c conda-forge -c bioconda rmats=4.1.1`. It might be that the other things that you already installed in your base conda environment are incompatible with rmats. You can create a conda environment just for rmats with:
> > ```
> > conda deactivate
> > conda create --prefix /path/to/new/directory/for/rmats_conda
> > conda activate /path/to/new/directory/for/rmats_conda
> > conda install -c conda-forge -c bioconda rmats=4.1.1
> > ```
> > 
> > 
> > Then you would just need to activate that environment when you want to use rmats
> 
> I tried again this time to install rmats from the anaconda : `conda install -c bioconda rmats`
> This time it looks I can get it installed, but when I tried to run using the following command:
> `~/anaconda3/bin/python /scratch/midway2/caiqi/conda_env_rmat_4_1_1/rMATS/rmats.py --b1 /scratch/midway2/caiqi/Activity_rmats_analysis/b1.txt --b2 /scratch/midway2/caiqi/Activity_rmats_analysis/b2.txt --gtf /scratch/midway2/caiqi/gencode_ref_ms/transcripts.gtf -t paired --readLength 101 --nthread 4 --od /scratch/midway2/caiqi/Activity_rmats_analysis/DRB_vs_DRB_and_Bic/ --tmp /scratch/midway2/caiqi/Activity_rmats_analysis/tmp_output > log001 2> error001`
> 
> The error is:
> 
> ```
> Traceback (most recent call last):
>   File "/scratch/midway2/caiqi/conda_env_rmat_4_1_1/rMATS/rmats.py", line 19, in <module>
>     from rmatspipeline import run_pipe
> ModuleNotFoundError: No module named 'rmatspipeline'
> srun: error: midway2-bigmem01: task 0: Exited with exit code 1
> ```
> 
> in the directory of rMATs, I have the following files:
> 
> ```
> (/scratch/midway2/caiqi/conda_env_rmat_4_1_1) [caiqi@midway2-login2 rMATS]$ ls
> __pycache__        rMATS_P   rmatspipeline.cpython-39-x86_64-linux-gnu.so
> cp_with_prefix.py  rMATS_R
> rMATS_C            rmats.py
> ```
> 
> What should I do to make it work?

I think I may get it run by changing the last step as:
conda_env_rmat_4_1_1/bin/python /scratch/midway2/caiqi/conda_env_rmat_4_1_1/rMATS/rmats.py --b1 /scratch/midway2/caiqi/Activity_rmats_analysis/b1.txt --b2 /scratch/midway2/caiqi/Activity_rmats_analysis/b2.txt --gtf /scratch/midway2/caiqi/gencode_ref_ms/transcripts.gtf -t paired --readLength 101 --nthread 4 --od /scratch/midway2/caiqi/Activity_rmats_analysis/DRB_vs_DRB_and_Bic/ --tmp /scratch/midway2/caiqi/Activity_rmats_analysis/tmp_output >log001 2>error001 &

It is running now. I will close the issue If I got it through to the end. 
Thank you
