### ISSUE TITLE
 not found in and Fail to open *.bam 

### ISSUE THREAD

**Issue by liaoshengyou** [Xinglab/rmats-turbo#116]
**hi, when i process my bam file running by hisat2,  the rmats.py get a error in my log file;  below this:**

 not found in .rmats filesect/2021/20210408__mRNA/2.alignment/bam/M145/M145_sort.bam

Fail to open */Project/2021/20210408__mRNA/2.alignment/bam/M145/M145_sort.bam

**and the *_read_outcomes_by_bam.txt file have the log:**
*/Project/2021/20210408__mRNA/2.alignment/bam/M145/M145_sort.bam
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 0
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 0
TOTAL_FOR_BAM: 0

 
**Then, i was  check the error cause:**
first, use --task inte to check , found a bam file =0, 

**input bam files with no associated prep output:**
/20210408__mRNA/2.alignment/bam/M145/M145_sort.bam
bam files not in input but associated with prep output:
/20210408__mRNA/2.alignment/bam/M145/M145_sort.bam

**and then i check  prep_count_by_bam dict in rmats.py, i found the result have a error,**

![image](https://user-images.githubusercontent.com/17425185/117392528-d6a8c400-af24-11eb-8a9d-b104a6e289a7.png)

**the cause is get_args  function in rmats.py not deal with "\r", so edit the function:** 

![image](https://user-images.githubusercontent.com/17425185/117392580-f04a0b80-af24-11eb-8280-4bc336f15f5a.png)

args.b1 = fp.read()**.strip()**.strip(' ,\n')
args.b2 = fp.read()**.strip()**.strip(' ,\n')

thanks

**Comment by EricKutschera** [comment]
Thanks for reporting this issue. rmats testing/development is done in a linux environment where line endings are '\n' and this issue would not be noticed. I've opened a pull request based on your change
