### ISSUE TITLE
How to get the sample name in *MATS* file

### ISSUE THREAD

**Issue by YangShi-PKU** [Xinglab/rmats-turbo#118]
Hello,
First thanks for developing such an awesome tool. I've run rMATS on my data and wanted to calculate PSI of all splicing events for each sample. I noted that I can use the info from *MATS* file to achieve this goal, but there are only read count separated by ',' without sample name for each value. Could you please tell me where to find the corresponding sample names for there ',' separated counts?

Thanks

Yang

**Comment by EricKutschera** [comment]
The comma separated values correspond to the input files listed in --b1 and --b2 (or --s1 and --s2). The values in IJC_SAMPLE_1 and SJC_SAMPLE_1 are in the same order as given in --b1. The values in IJC_SAMPLE_2 and SJC_SAMPLE_2 are in the same order as given in --b2

Example:
--b1
```
sample_a.bam,sample_b.bam
```

--b2
```
sample_c.bam,sample_d.bam
```

SE.MATS.JC.txt
```
ID	GeneID	{...}	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	{...}
1	"a_gene_id"	{...}	10,11	12,13	14,15	16,17	{...}
```

* sample_a: (inclusion: 10, skipping: 12)
* sample_b: (inclusion: 11, skipping: 13)
* sample_c: (inclusion: 14, skipping: 16)
* sample_d: (inclusion: 15, skipping: 17)

**Comment by YangShi-PKU** [comment]
Got it! Thank you very much!
