### ISSUE TITLE
rmats not finding STAR script

### ISSUE THREAD

**Issue by Biojenifer** [Xinglab/rmats-turbo#119]
Hi!

I am trying to run rmats from fastq files. But I am getting the following error:`error detail: /bin/sh: STAR: command not found
`

Before running the script I add STAR's path to my PATH: `export PATH=$PATH:/mnt/netapp2/programs/external/STAR/bin/Linux_x86_64/STAR`

Do you know how can I solve it?

**Comment by EricKutschera** [comment]
I think the issue may be that PATH expects a directory, but you are giving the full path to the executable STAR. You could try dropping the trailing `/STAR`:

```
export PATH=$PATH:/mnt/netapp2/programs/external/STAR/bin/Linux_x86_64
```

**Comment by Biojenifer** [comment]
Thanks a lot Eric! It worked.
