### ISSUE TITLE
separating what is development clutter from core source code

### ISSUE THREAD

**Issue by leipzig** [Xinglab/rmats-turbo#12]
I am still seeing a lot of stuff from the development and testing of rMATS kind of scattered around:
```
GLM_MS_unpaired 3.04.01 PM.py
analysis.py 
diff_result1.txt 
output.txt
rMATS_Result_P.txt
rMATS_Result_P_backup.txt
test.c
test.txt
test_output.txt
trans.exe
```

From a Q&A standpoint it's now possible (thanks to the open sourcing) to point people to the core statistics behind rMATS e.g. https://www.biostars.org/p/444274/
but it's fairly difficult to isolate the relevant parts of rMATS with all this clutter.

Is it possible to segregate these files in some other directory or branch?

**Comment by EricKutschera** [comment]
I agree that the rMATS_C directory would benefit from a clean up. A lot of those files should probably be removed. I haven't spent much time looking into that part of the code and since it wasn't causing any errors I didn't want to mess with it.

Do you want to open a pull request to remove the files you think are just clutter?

**Comment by leipzig** [comment]
OK I will try removing files until something breaks

**Comment by fklirono** [comment]
Also could you please indicate in the README what are the differences between `rmats_turbo_v4_1_0.tar.gz`, `rmats_turbo_v4_1_0_python_3_6.tar.gz` and `Source code (tar.gz)` and which one should a sane user download in order to build and install rMATS?

**Comment by EricKutschera** [comment]
I've updated the description on the release page to explain the differences: https://github.com/Xinglab/rmats-turbo/releases/tag/v4.1.0
