### ISSUE TITLE
run_rmats changes directory

### ISSUE THREAD

**Issue by HaraldWilhelmi** [Xinglab/rmats-turbo#120]
When using the run_rmats script with relative paths in the arguments it fails with errors like:

FileNotFoundError: [Errno 2] No such file or directory:

It seems that this is caused by a 'cd' command in run_rmats. The surrounding code suggests that the actual change of the working directory is unintended and most likely not needed. If that is the case I
suggest this patch for a nicer behavior:
```
--- run_rmats.orig	2021-05-18 14:19:20.000000000 +0200
+++ run_rmats	2021-05-18 14:20:44.000000000 +0200
@@ -2,8 +2,7 @@
 
 function set_script_dir() {
   local REL_SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})" || return 1
-  cd "${REL_SCRIPT_DIR}" || return 1
-  SCRIPT_DIR="$(pwd)" || return 1
+  SCRIPT_DIR="$( cd "${REL_SCRIPT_DIR}" && pwd )" || return 1
 }
 
 # build_rmats can create a conda environment. Use it if it exists.
```

**Comment by EricKutschera** [comment]
Thanks for identifying this issue and providing a solution. I've merged a pull request to address this
