### ISSUE TITLE
Solving NOT_NH_1 and EXON_NOT_MATCHED_TO_ANNOTATION reads

### ISSUE THREAD

**Issue by Biojenifer** [Xinglab/rmats-turbo#122]
Hi!

I am getting empty files after running rmats.py because no read is being used. The cause of this is the following:

```
/home/STAR_RNAseq/2_alignment/sampleA/Aligned.sortedByCoord.out.bam
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 40019742
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 5854966
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 0
TOTAL_FOR_BAM: 45874708
/home/STAR_RNAseq/2_alignment/sampleB/Aligned.sortedByCoord.out.bam
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 63578284
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 6893878
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 0
TOTAL_FOR_BAM: 70472162
```
After reading previous issues I understand these problems, but I am still not sure about how to solve them.

1. Regarding EXON_NOT_MATCHED_TO_ANNOTATION: the problem is caused because the annotation gtf which STAR uses present '1' instead of 'chr1' formatting for chromosomes. In addition, mitocondrial chromosome is formatted 'MT', instead of 'M'.
If I try to run rmats using this gtf file I get a `Segmentation fault` error, while if I use the not formatted gtf it works. Do you know if there is a way for rmats understanding this formating? 

2. Regarding NOT_NH_1 I consulted STAR logs, I'll paste here just the output for the first bam:
```
                          Number of input reads |       15446001
                      Average input read length |       302
                                    UNIQUE READS:
                   Uniquely mapped reads number |       13652927
                        Uniquely mapped reads % |       88.39%
                          Average mapped length |       297.58
                       Number of splices: Total |       12044081
            Number of splices: Annotated (sjdb) |       11909437
                       Number of splices: GT/AG |       11936839
                       Number of splices: GC/AG |       74604
                       Number of splices: AT/AC |       9788
               Number of splices: Non-canonical |       22850
                      Mismatch rate per base, % |       0.28%
                         Deletion rate per base |       0.02%
                        Deletion average length |       1.32
                        Insertion rate per base |       0.01%
                       Insertion average length |       1.60
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       759146
             % of reads mapped to multiple loci |       4.91%
        Number of reads mapped to too many loci |       1988
             % of reads mapped to too many loci |       0.01%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |       0
       % of reads unmapped: too many mismatches |       0.00%
            Number of reads unmapped: too short |       1025537
                 % of reads unmapped: too short |       6.64%
                Number of reads unmapped: other |       6403
                     % of reads unmapped: other |       0.04%
                                  CHIMERIC READS:
                       Number of chimeric reads |       225290
                            % of chimeric reads |       1.46%
```

As you can see, 88.39 % of the reads were uniquely mapped and just 4,92 % are multimapped. So, I am not sure why does rmats does not detect uniquely mapped reads. 

PD: I know this is regarding read lengths, but just in case this is important, I am using: `--allow-clipping` and `--variable-read-length` arguments.

Do you know how can I solve this? Thanks!

**Comment by EricKutschera** [comment]
rMATS should handle either 'chr1' or '1'. It will prepend 'chr' if it is lacking from either the gtf or bam (or both). There is no special handling for other naming difference like MT instead of M. I would guess that the difference in coordinates is what causes EXON_NOT_MATCHED_TO_ANNOTATION, not the difference of chr1 and 1. It would be ideal to use the same gtf file with STAR and rmats. I don't know any reason that rmats would have a `Segmentation fault`, but if you can provide your input files and command line arguments then I can try to reproduce and debug that error

For NOT_NH_1, I agree that the STAR log shows that most of the reads are uniquely mapped. Is that log file for one of the bams that you posted rmats output for? The STAR log has: `Number of input reads | 15446001`, but the rmats output has `TOTAL_FOR_BAM: 45874708` and `TOTAL_FOR_BAM: 70472162`

**Comment by Biojenifer** [comment]
Thanks for your answer!

Regarding the segmentation fault, this is the output after running the command line with gdb:

`Program received signal SIGSEGV, Segmentation fault.
0x00007fffe8653439 in __pyx_f_5rmats_13rmatspipeline_parse_gtf(_object*, std::unordered_map<int, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, rmats::Gene, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, rmats::Gene> > >&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, rmats::SupInfo, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, rmats::SupInfo> > >&) ()
   from /home/environments/python/rMATS/rmats_turbo_v4_1_1/rmatspipeline.cpython-36m-x86_64-linux-gnu.so`
   
   
This is a fragment of the gtf:

`#description: evidence-based annotation of the human genome (GRCh38), version 35 (Ensembl 101), mapped to GRCh37 with gencode-backmap
#provider: GENCODE
#contact: gencode-help@ebi.ac.uk
#format: gff3
#date: 2020-06-03
chr1    HAVANA  gene    11869   14409   .       +       .       gene_id "ENSG00000223972.5_4"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; hgnc_id "HGNC:37 102"; havana_gene "OTTHUMG00000000961.2_4"; remap_status "full_contig"; remap_num_mappings 1; remap_target_status "overlap";
chr1    HAVANA  transcript      11869   14409   .       +       .       gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_num_mappings 1; remap_status "full_contig"; remap_target_status "overlap";
chr1    HAVANA  exon    11869   12227   .       +       .       gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 1; exon_id "ENSE00002234944.1_1"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_original_location "chr1:+:11869-12227"; remap_status "full_contig";
chr1    HAVANA  exon    12613   12721   .       +       .       gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 2; exon_id "ENSE00003582793.1_1"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_original_location "chr1:+:12613-12721"; remap_status "full_contig";
chr1    HAVANA  exon    13221   14409   .       +       .       gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 3; exon_id "ENSE00002312635.1_1"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_original_location "chr1:+:13221-14409"; remap_status "full_contig";
chr1    HAVANA  transcript      12010   13670   .       +       .       gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000450305.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-201"; level 2; transcript_support_level "NA"; hgnc_id "HGNC:37102"; ont "PGO:0000005"; ont "PGO:0000019"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000002844.2_1"; remap_num_mappings 1; remap_status "full_contig"; remap_target_status "overlap";
`

This is the not formatted gtf:

`#description: evidence-based annotation of the human genome (GRCh38), version 35 (Ensembl 101), mapped to GRCh37 with gencode-backmap
#provider: GENCODE
#contact: gencode-help@ebi.ac.uk
#format: gff3
#date: 2020-06-03
1 HAVANA gene 11869 14409 . + . gene_id "ENSG00000223972.5_4"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; hgnc_id "HGNC:37102"; havana_gene "OTTHUMG00000000961.2_4"; remap_status "full_contig"; remap_num_mappings 1; remap_target_status "overlap";
1 HAVANA transcript 11869 14409 . + . gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_num_mappings 1; remap_status "full_contig"; remap_target_status "overlap";
1 HAVANA exon 11869 12227 . + . gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 1; exon_id "ENSE00002234944.1_1"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_original_location "chr1:+:11869-12227"; remap_status "full_contig";
1 HAVANA exon 12613 12721 . + . gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 2; exon_id "ENSE00003582793.1_1"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_original_location "chr1:+:12613-12721"; remap_status "full_contig";
1 HAVANA exon 13221 14409 . + . gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000456328.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 3; exon_id "ENSE00002312635.1_1"; level 2; transcript_support_level 1; hgnc_id "HGNC:37102"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000362751.1_1"; remap_original_location "chr1:+:13221-14409"; remap_status "full_contig";
1 HAVANA transcript 12010 13670 . + . gene_id "ENSG00000223972.5_4"; transcript_id "ENST00000450305.2_1"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-201"; level 2; transcript_support_level "NA"; hgnc_id "HGNC:37102"; ont "PGO:0000005"; ont "PGO:0000019"; tag "basic"; havana_gene "OTTHUMG00000000961.2_4"; havana_transcript "OTTHUMT00000002844.2_1"; remap_num_mappings 1; remap_status "full_contig"; remap_target_status "overlap";`

**Comment by EricKutschera** [comment]
I created two gtf files based on the fragments you posted and I was able to run both without a segfault. When copying the text you posted into an actual file I needed to replace the spaces between the fields with tabs and remove the blank lines in order to run rmats without an error. Your actual files may not have had those issues

Can you post the full file that causes a segfault either as an attachment or a link that I can use to download the file? That way I can hopefully reproduce the error

**Comment by Biojenifer** [comment]
You are right, the problem was in the spaces between the columns in the formated file. I replace them by tabs and now it is working. 

Regarding NOT_NH_1 reads, I figured out that the problem was that the bam file I was using was aligned to the transcriptome. Now I have used the bam aligned to the reference genome (sorted by coordinates) and the performing of rmats has improved.

So, after correcting this 2 issues my output looks like this:

`/home/STAR_RNAseq/2_alignment/sampleA/Aligned.sortedByCoord.out.bam
USED: 21886425
NOT_PAIRED: 0
NOT_NH_1: 2856300
NOT_EXPECTED_CIGAR: 809380
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 809322
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 66221
CLIPPED: 0
TOTAL_FOR_BAM: 26427648
/home/STAR_RNAseq/2_alignment/sampleB/Aligned.sortedByCoord.out.bam
USED: 26081495
NOT_PAIRED: 0
NOT_NH_1: 3308300
NOT_EXPECTED_CIGAR: 679708
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 456655
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 87996
CLIPPED: 0
TOTAL_FOR_BAM: 30614154`

And this is the output of STAR for sampleA:

`                            Started job on |       Jan 11 13:49:48
                             Started mapping on |       Jan 11 13:58:19
                                    Finished on |       Jan 11 14:02:32
       Mapping speed, Million of reads per hour |       188.42

                          Number of input reads |       13241821
                      Average input read length |       302
                                    UNIQUE READS:
                   Uniquely mapped reads number |       11785674
                        Uniquely mapped reads % |       89.00%
                          Average mapped length |       298.36
                       Number of splices: Total |       6649072
            Number of splices: Annotated (sjdb) |       6549190
                       Number of splices: GT/AG |       6575422
                       Number of splices: GC/AG |       46176
                       Number of splices: AT/AC |       6011
               Number of splices: Non-canonical |       21463
                      Mismatch rate per base, % |       0.30%
                         Deletion rate per base |       0.02%
                        Deletion average length |       1.32
                        Insertion rate per base |       0.01%
                       Insertion average length |       1.61
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       629856
             % of reads mapped to multiple loci |       4.76%
        Number of reads mapped to too many loci |       7153
             % of reads mapped to too many loci |       0.05%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |       0
       % of reads unmapped: too many mismatches |       0.00%
            Number of reads unmapped: too short |       803621
                 % of reads unmapped: too short |       6.07%
                Number of reads unmapped: other |       15517
                     % of reads unmapped: other |       0.12%
                                  CHIMERIC READS:
                       Number of chimeric reads |       178365
                            % of chimeric reads |       1.35%
`
So, the performance has improved, but I am still confused about why number of input reads for STAR ir `13241821` while total for bam in sample A is `26427648`. In addition, I have now not expected cigar reads.

**Comment by EricKutschera** [comment]
I think the main source of difference between the STAR and rmats total counts is that STAR is counting the number of input read pairs, but rmats is counting the number of individual reads (two reads in each pair). Another difference is that (by default) STAR does not output unmapped reads. Also rmats will count each of the alignments for a multimapped read toward the NOT_NH_1 total

Here's an attempt to account for the difference:
```
rmats_total = 26427648
rmats_not_nh_1 = 2856300

star_total = 13241821
star_multi = 629856
star_not_mapped_too_many_loci = 7153
star_not_mapped_too_short = 803621
star_not_mapped_other = 15517

# 826291
star_not_mapped = (star_not_mapped_too_many_loci
                   + star_not_mapped_too_short
                   + star_not_mapped_other)
# 12415530
star_output = star_total - star_not_mapped

# 1596588
rmats_extra_not_nh_1 = rmats_not_nh_1 - (star_multi * 2)
# 26427648 == rmats_total
(star_output * 2) + rmats_extra_not_nh_1
```

NOT_EXPECTED_CIGAR means that the alignment involved more operations than what rmats expects. rmats can only handle exon reads that have a CIGAR string with a single match operation (M) and junction reads that have a CIGAR string with alternating match and skip operations (MNM[NM...]). The alignments labeled as NOT_EXPECTED_CIGAR may have insertion, deletion, or mismatch operations

**Comment by Biojenifer** [comment]
Ok, I understand! So, if an integration of some sequence (a virus, for example) in a specific exon or intron is causing an splicing event, rmats wouldn´t detect it because the reads spanning that region would contain an insertion?

**Comment by EricKutschera** [comment]
That seems correct to me. If the reads that are needed to support the splicing event include the inserted sequence then rmats will not be able to use those reads and rmats will not detect the event.

There might be some cases where an inserted sequence has an indirect effect that changes splicing and rmats might detect some of those cases. But I agree that rmats is not good at detecting events in the region of the insertion

**Comment by Biojenifer** [comment]
I see. Thanks a lot for all your help!
