### ISSUE TITLE
A small fraction of reads were used

### ISSUE THREAD

**Issue by YangShi-PKU** [Xinglab/rmats-turbo#123]
Hi Eric,
I've run rmats-turbo on my RNA-seq data but my result seems strange. I'm seeking help from you and any advice would be appreciated.
Data information: 105 tumor samples sequenced by 150bp paired end RNA-seq. Adapters trimmed by Trimmomatic and alignment finished by STAR using hg38. I divided these samples into two groups according to their response to a anti-tumor drug, 70 samples for group1 and 35 samples for group2.

Software:
rmats 4.1.1 installed from Anaconda

Command: 
```
GTFFILE=/shared/ref_genome/STAR2.7a_GRCh38/Homo_sapiens.GRCh38.97.gtf
source activate rmats
rmats.py --b1 ${BAMLIST1} --b2 ${BAMLIST2} --gtf ${GTFFILE} -t paired --readLength 150 --nthread ${NCORE} --od ${OUTDIR} --tmp ${OUTDIR}/tmp
source deactivate
```
Strange result:
First I found there is almost no AS event with significant difference between two groups. Here is the result from summary.txt:
```
EventType       TotalEventsJC   TotalEventsJCEC SignificantEventsJC     SigEventsJCSample1HigherInclusion       SigEventsJCSample2HigherInclusion       SignificantEventsJCEC   SigEventsJCECSample1HigherInclusion     SigEventsJCECSample2HigherInclusion
SE      126415  128298  0       0       0       2       2       0
A5SS    6504    6515    0       0       0       0       0       0
A3SS    10070   10075   0       0       0       1       1       0
MXE     27122   27428   0       0       0       0       0       0
RI      5692    5697    1       1       0       1       1       0
```
and then I found a lot of zeros in *RMATS* files which suggests a lot of AS event are not detected. So I checked the STDOUT from rmats.py and found a lot of reads are not used:
```
gtf: 18.813377380371094
There are 60617 distinct gene ID in the gtf file
There are 226788 distinct transcript ID in the gtf file
There are 36731 one-transcript genes in the gtf file
There are 1363230 exons in the gtf file
There are 25243 one-exon transcripts in the gtf file
There are 22505 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.741327
Average number of exons per transcript is 6.011032
Average number of exons per transcript excluding one-exon tx is 6.638651
Average number of gene per geneGroup is 8.455232
statistic: 0.0316922664642334

read outcome totals across all BAMs
USED: 1103184455
NOT_PAIRED: 455606356
NOT_NH_1: 35462918
NOT_EXPECTED_CIGAR: 184926269
NOT_EXPECTED_READ_LENGTH: -1281961840
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 11328917
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 23541633
CLIPPED: 1961198846
total: -1801679742
outcomes by BAM written to: /shared/yangshi/A317_102/rmats_result_conda_wihout_rlclip/tmp/2021-05-23-08:41:02_949363_read_outcomes_by_bam.txt

novel: 2031.611924648285
The splicing graph and candidate read have been saved into /shared/yangshi/A317_102/rmats_result_conda_wihout_rlclip/tmp/2021-05-23-08:41:02_949363_*.rmats
save: 37.78797125816345
loadsg: 1.0628077983856201

==========
Done processing each gene from dictionary to compile AS events
Found 110794 exon skipping events
Found 17172 exon MX events
Found 19659 alt SS events
There are 11819 alt 3 SS events and 7840 alt 5 SS events.
Found 7170 RI events
==========

ase: 4.014789342880249
count: 66.58584952354431
Processing count files.
Done processing count files.

```
I noted that there are many reads labeled as "NOT_EXPECTED_READ_LENGTH" and "CLIPPED", so I add --variable-read-length and --allow-clipping to my command and run it again, and the STDOUT actually make me confused:
```
gtf: 18.368732213974
There are 60617 distinct gene ID in the gtf file
There are 226788 distinct transcript ID in the gtf file
There are 36731 one-transcript genes in the gtf file
There are 1363230 exons in the gtf file
There are 25243 one-exon transcripts in the gtf file
There are 22505 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.741327
Average number of exons per transcript is 6.011032
Average number of exons per transcript excluding one-exon tx is 6.638651
Average number of gene per geneGroup is 8.455232
statistic: 0.03137540817260742

read outcome totals across all BAMs
USED: 388143152
NOT_PAIRED: 461389772
NOT_NH_1: 995651078
NOT_EXPECTED_CIGAR: 222840085
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 57771081
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 367492386
CLIPPED: 0
total: -1801679742
outcomes by BAM written to: /shared/yangshi/A317_102/rmats_result_conda/tmp/2021-05-21-15:57:30_247791_read_outcomes_by_bam.txt

novel: 2058.469147205353
The splicing graph and candidate read have been saved into /shared/yangshi/A317_102/rmats_result_conda/tmp/2021-05-21-15:57:30_247791_*.rmats
save: 87.63092970848083
loadsg: 1.984689712524414

==========
Done processing each gene from dictionary to compile AS events
Found 146976 exon skipping events
Found 28678 exon MX events
Found 21258 alt SS events
There are 12742 alt 3 SS events and 8516 alt 5 SS events.
Found 7251 RI events
==========

ase: 5.174456834793091
count: 131.8912615776062
Processing count files.
Done processing count files.
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

```

As you can see, the number of "USED" reads decreases from to 1103184455 to 388143152 after I allowed clipped reads and variable read length. And reads labeled as 'NH_1' increases dramatically. How could that be?

BTW, I found there is a '-' before total reads, what does that mean?

Thanks in advance!

BRs
Yang

**Comment by EricKutschera** [comment]
The negative numbers reported for read outcomes are due to integer overflow. Here's a similar reported issue: https://github.com/Xinglab/rmats-turbo/issues/84#issuecomment-814166234 and this is some of the relevant code: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L841

The 32 bit integer used to total the read outcomes would overflow at around 2 billion alignments and start counting up from around negative 2 billion. The overflow is not necessarily a problem since the counts are just for debugging, but it does cause confusion. The counts for the individual bam files in `{datetime}_read_outcomes_by_bam.txt` in the `--tmp` dir should be accurate as long as each individual bam did not exceed 2 billion alignments so you could check there to get a better idea of what is preventing reads from being used

**Comment by beaferbl** [comment]
Hi,
I run rMATS twice with distinct GTF files, one from GENCODE and the other one a custom GTF. The read outcome totals across all BAMs is the following:

**With GENCODE GTF**:
USED: 2121793686
NOT_PAIRED: 536576865
NOT_NH_1: 1127826873
NOT_EXPECTED_CIGAR: 64522885
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 625198733
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 66132207
CLIPPED: -1808336716
total: -1561252763

**With custom GTF**:
USED: -1672676596
NOT_PAIRED: 536576865
NOT_NH_1: 1127826873
NOT_EXPECTED_CIGAR: 64522885
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 134496124
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 56337802
CLIPPED: -1808336716
total: -1561252763

My doubts are:
1. As there are more reads in EXON and JUNCTION_NOT_MATCHED_TO_ANNOTATION in the first case, I would expect the number of used reads to be lower than in the second one, as NOT_PAIRED, NOT_NH_1, NOT_EXPECTED_CIGAR and CLIPPED are the same (as expected).
2.  For what I understand in this thread, the fact that the numbers are negative is not so important. I checked that NOT_PAIRED, NOT_NH_1, NOT_EXPECTED_CIGAR, CLIPPED and TOTAL_FOR_BAM are the same for each BAM file, with both strategies. So I think my results are ok, but just wanted to be sure.

Thank you.

**Comment by EricKutschera** [comment]
I think your results are ok. The negative numbers indicate that there was 32-bit integer overflow when showing the summary counts which is not a serious issue. It just makes it hard to interpret the overall summary counts. All the numbers in the actual result files should still be correct. In particular you can check the summary counts for each individual bam file in `{datetime}_read_outcomes_by_bam.txt`

In the first case: (junction: 66132207), (exon: 625198733), (used: 2121793686). In the second: (junction: 56337802), (exon: 134496124), (used: -1672676596). The second case has (66132207 - 56337802 = 9794405) fewer junction not matched and (625198733 - 134496124 = 490702609) fewer exon not matched for a total of (9794405 + 490702609 = 500497014) fewer not matched. Overflow happens at (2\*\*31 = 2147483648). The first case had a used value (2147483648 - 2121793686 = 25689962) below the overflow. The second case had a used value that had already passed the overflow and gone up from (-2\*\*31 = -2147483648) by (2147483648 - 1672676596 = 474807052). The total of reaching the overflow and then going over is (25689962 + 474807052 = 500497014). So the additional not matched reads in the first case did lead to fewer used reads (both 500497014), but the overflow makes that hard to see

**Comment by beaferbl** [comment]
Ok, I was missunderstanding the number of used reads in the second case, it is not the real number, now it is very clear. Thank you so much!
