### ISSUE TITLE
IOError：Errno 22 invalid mode （‘wt’） or filename:

### ISSUE THREAD

**Issue by FLY-Fiancee** [Xinglab/rmats-turbo#127]
When I used rMATS for variable shear analysis, I encountered the following error:
python2 /home/fly/miniconda3/envs/python27/rMATS/rmats.py --b1 b1.txt --b2 b2.txt --gtf /media/fly/有参RNA-seq/result/BAM/mm.gtf --od AS1 --tmp AS2 -t paired --readLength 151 --cstat 0.0001 --nthread 4
## THE ERROR:
IOError: [Errno 22] invalid mode ('wt') or filename: 'AS2/2021-06-10-21:35:59_370153_read_outcomes_by_bam.txt'
Exception IOError: (22, "invalid mode ('wt') or filename", 'AS2/2021-06-10-21:35:59_370153_read_outcomes_by_bam.txt') in 'rmats.rmatspipeline.output_read_outcomes' ignored
novel: 610.933357
Traceback (most recent call last):
  File "/home/fly/miniconda3/envs/python27/rMATS/rmats.py", line 536, in <module>
    main()
  File "/home/fly/miniconda3/envs/python27/rMATS/rmats.py", line 507, in main
    run_pipe(args)
  File "rmatspipeline/rmatspipeline.pyx", line 3795, in rmats.rmatspipeline.run_pipe
  File "rmatspipeline/rmatspipeline.pyx", line 3449, in rmats.rmatspipeline.save_job
IOError: [Errno 22] invalid mode ('wt') or filename: 'AS2/2021-06-10-21:35:59_370153_0.rmats'
and I don't understand why it doesn‘t works. Any suggestions?

**Comment by EricKutschera** [comment]
That seems like it might be related to this issue: https://github.com/Xinglab/rmats-turbo/issues/106

You could try the code change mentioned in that issue to see if it resolves the error you are seeing
