### ISSUE TITLE
.bam files fail to open

### ISSUE THREAD

**Issue by bgansemer** [Xinglab/rmats-turbo#128]
I'm trying to run rmats_turbo_v4_1_1 with bam files that were previously aligned with STAR. When running it, I get no errors and it completes, but when looking at the stdout file (running on university computing cluster) it says that all of the bam files fail to open. The gtf file appears to be opened and processed correctly. 

Here is what is in the stdout file:

```
gtf: 5.4281675815582275
There are 32883 distinct gene ID in the gtf file
There are 41078 distinct transcript ID in the gtf file
There are 27496 one-transcript genes in the gtf file
There are 311360 exons in the gtf file
There are 10067 one-exon transcripts in the gtf file
There are 9737 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.249217
Average number of exons per transcript is 7.579726
Average number of exons per transcript excluding one-exon tx is 9.715682
Average number of gene per geneGroup is 4.041000
statistic: 0.011981964111328125
Fail to open ~/deafratrnaseq/data/alignments/P60Hearing1_merged_trimmed.Aligned.out.mapped.coordSorted.bam
Fail to open ~/deafratrnaseq/data/alignments/P60Hearing3_merged_trimmed.Aligned.out.mapped.coordSorted.bam
Fail to open ~/deafratrnaseq/data/alignments/P60Deaf2_merged_trimmed.Aligned.out.mapped.coordSorted.bam
Fail to open ~/deafratrnaseq/data/alignments/P60Hearing2_merged_trimmed.Aligned.out.mapped.coordSorted.bam
Fail to open ~/deafratrnaseq/data/alignments/P60Deaf3_merged_trimmed.Aligned.out.mapped.coordSorted.bam
Fail to open ~/deafratrnaseq/data/alignments/P60Deaf1_merged_trimmed.Aligned.out.mapped.coordSorted.bam

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 0
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 0
total: 0
outcomes by BAM written to: /nfsscratch/Users/bgansemer/tmp_out/2021-06-10-15:52:18_842822_read_outcomes_by_bam.txt

novel: 0.002887248992919922
The splicing graph and candidate read have been saved into /nfsscratch/Users/bgansemer/tmp_out/2021-06-10-15:52:18_842822_*.rmats
save: 0.020667314529418945
loadsg: 0.004349470138549805

Done processing each gene from dictionary to compile AS events
Found 1998 exon skipping events
Found 199 exon MX events
Found 589 alt SS events
There are 364 alt 3 SS events and 225 alt 5 SS events.
Found 417 RI events

ase: 0.3473174571990967
count: 0.04015016555786133
Processing count files.
Done processing count files.
```

Here's the command I'm using to run rmats:

```
 ~/deafratrnaseq/packages/rmats/rmats_turbo_v4_1_1/run_rmats --b1 ~/deafratrnaseq/analysis/rmats/P60H.txt \
        --b2 ~/deafratrnaseq/analysis/rmats/P60D.txt \
        --gtf ~/deafratrnaseq/data/genome/Rattus_norvegicus.Rnor_6.0.95.gtf \
        -t paired --readLength 100 --nthread 4 \
        --od /nfsscratch/Users/bgansemer/out \
        --tmp /nfsscratch/Users/bgansemer/tmp_out \
```

I installed rmats with conda and everything checked out when running `./test_rmats`.

If I replace `~/` with `/Users/bgansemer/` in the bam file paths I get a segmentation fault error:

`/Users/bgansemer/deafratrnaseq/packages/rmats/rmats_turbo_v4_1_1/run_rmats: line 19:  9460 Segmentation fault      python "${SCRIPT_DIR}/rmats.py" "$@"`

Any help you can provide would be much appreciated.

Thanks!

**Comment by EricKutschera** [comment]
I think those "Fail to open" errors are from this line: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L712

I tried testing with some bam files I put in my `~/` directory and I also get failed to open errors. The errors did not happen anymore if I replaced `~/` with `/home/{my_user_name}`. It seems that you solved that issue by using `/Users/bgansemer`

That still leaves the segfault. See this thread for suggestions related to that: https://github.com/Xinglab/rmats-turbo/issues/18 . I think that the segaults are caused by running out of memory (although so far no users have confirmed that). If you are able to watch the memory usage on your system (maybe with `htop`) while running rmats you might be able to see the memory filling up

**Comment by bgansemer** [comment]
Thanks! Your first test confirmed that the "Fail to open" was a directory specification issue and that I could focus on the segfault issue. After looking at issue #18 and the suggestions provided there I tried changing `--nthread 4` to `--nthread 1` and that solved the segfault. Everything seems to have run smoothly and there are data in the output files.  Not sure how it affected runtime (took ~1hr for 6 bam files ~6GB each), but I'm not too concerned with that. 

Thanks again!
