### ISSUE TITLE
number of threads not working when performing the prep step alone

### ISSUE THREAD

**Issue by carynhale** [Xinglab/rmats-turbo#129]
Hi Eric-
Thanks for the update to rMATs, so far we've found it to be a great improvement to an already great piece of software!  

We're particularly interested in the ability to run the prep and post processing steps properly, but we're having an issue.  When we run the prep step alone, we cannot get the software to use more than one CPU, no matter what number we use for the nthreads flag. We've seen this on two different machines, both of which installed rMATs via bioconda. 

I ran the test that was described previously (here: [https://github.com/Xinglab/rmats-turbo/issues/104]) and I can confirm that for this test set, we can get multiple threads to run. But for some reason it's not working when we run just the prep step. 

I am using rMATs installed with bioconda on Ubuntu 20.04.2 LTS.

**Comment by EricKutschera** [comment]
The prep step can use at most one CPU per input bam file. If you are already running each bam in a separate prep step, then setting --nthread greater than 1 will not help. If you are using multiple bams in a single prep step then I would expect multiple CPUs to be used. If that's the case, could you share your command line and input files?

The post step also can use at most one CPU per input bam file. The statistical step can use one CPU per detected event, so it is easier to make use of many CPUs in --task stat as compared to --task prep or -task post

**Comment by carynhale** [comment]
Even when we run more than one file, we're still only using one CPU.  Here's the code that we used:

(base) ubuntu@ip-10-0-128-98:~/rmats-turbo/test_data$ cat b1.txt
231ESRP.25K.rep-1.bam,231ESRP.25K.rep-2.bam
(base) ubuntu@ip-10-0-128-98:~/rmats-turbo/test_data$ rmats.py --b1 b1.txt --gtf Homo_sapiens.GRCh38.99.gtf -t paired --readLength 50 --nthread 2 --od output_conda --tmp /tmp/ --task prep
gtf: 21.507893085479736
There are 60676 distinct gene ID in the gtf file
There are 227818 distinct transcript ID in the gtf file
There are 36763 one-transcript genes in the gtf file
There are 1376499 exons in the gtf file
There are 25269 one-exon transcripts in the gtf file
There are 22508 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.754664
Average number of exons per transcript is 6.042099
Average number of exons per transcript excluding one-exon tx is 6.671126
Average number of gene per geneGroup is 8.463790
statistic: 0.04250788688659668
 
read outcome totals across all BAMs
USED: 78562
NOT_PAIRED: 0
NOT_NH_1: 15636
NOT_EXPECTED_CIGAR: 372
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 1346
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 166
CLIPPED: 0
total: 96082
outcomes by BAM written to: /tmp/2021-06-15-13:35:44_305766_read_outcomes_by_bam.txt
 
novel: 0.5784463882446289
The splicing graph and candidate read have been saved into /tmp/2021-06-15-13:35:44_305766_*.rmats
save: 0.05218791961669922
(base) ubuntu@ip-10-0-128-98:~/rmats-turbo/test_data$ nproc
4
 
Above test only used one CPU, but we had 2 bam files and nthreads set to 2.
 
This command from another github issue, uses all 4 cores.
rmats.py --od ./test_stat_thread_input --tmp ./tmp_dir --tstat 4 --task stat

**Comment by EricKutschera** [comment]
The printed output has a few lines that show timing information

```
gtf: 21.507893085479736
statistic: 0.04250788688659668
novel: 0.5784463882446289
save: 0.05218791961669922
```

The time spent in the portion of the prep step that can use multiple threads is part of `novel: 0.5784463882446289`. If you are manually watching `htop` to see how many CPUs are used then it would be hard to notice. Most of the time is spent with a single thread parsing the gtf file

You could make larger bam files by duplicating the alignments so that each of the 2 threads has at least a few seconds of work:

```
samtools view -h 231ESRP.25K.rep-1.bam > 231ESRP.25K.rep-1.sam
samtools view 231ESRP.25K.rep-1.bam >> 231ESRP.25K.rep-1.sam  # repeat many times
samtools view -b 231ESRP.25K.rep-1.sam > 231ESRP.25K.rep-1_extra.bam
```

Then you should be able to see the two threads working
