### ISSUE TITLE
count filtering

### ISSUE THREAD

**Issue by YZYwoazzzzz** [Xinglab/rmats-turbo#130]
Hi Eric,
I noticed an updating in version v4.1.1.  The log or --tmp contain bam counts, like this:

> read outcome totals across all BAMs
> USED: 38
> NOT_PAIRED: 0
> NOT_NH_1: 2
> NOT_EXPECTED_CIGAR: 2
> NOT_EXPECTED_READ_LENGTH: 0
> NOT_EXPECTED_STRAND: 0
> EXON_NOT_MATCHED_TO_ANNOTATION: 0
> JUNCTION_NOT_MATCHED_TO_ANNOTATION: 32
> CLIPPED: 0
> total: 74

This is an example of one gene. so the read counts are few.
Here are the questions：
1. Is the filtering criteria changed between v4.1.0 and v4.1.1? I run in those two version and get different results. PS: v4.1.0 did not contain the details about how many counts are used. But the results in rMats/SE.MATS.JC.txt show different supporting counts. If it is, what is the criteria of v4.1.0?
2. Could I  extract the reads from bam file that support the AS event and separate the reads that support inclusion or exclusion AS. So that I can use IGV to visulize it. PS: rmats2sashimiplot is a good tools in most conditions, but somtimes IGV is more objective.

Best,
Yzy

**Comment by EricKutschera** [comment]
Here are the release notes for v4.1.1 which should include anything that would change the output: https://github.com/Xinglab/rmats-turbo/releases

This bullet point from the release notes could explain the difference you are seeing:
* Bug fix of strand specific read filtering

In v4.1.0, only exon reads had the strand checked against the annotated strand for the gene. In v4.1.1, both exon and junction reads have their strand checked. The "JUNCTION_NOT_MATCHED_TO_ANNOTATION: 32" could be from junction reads that did not match the annotated strand. The strand checking does not apply with --libType fr-unstranded (which is the default)

**Comment by EricKutschera** [comment]
2. rMATS doesn't keep track of which specific reads from the BAM count toward each isoform. I can't think of a good way to extract reads from the BAM so that the inclusion and exclusion reads are cleanly separated

**Comment by YZYwoazzzzz** [comment]
Thanks for your quick response! 
But I set Fr-unstranded.  And I  checked the strand info in bam files. All reads match the gene strand from annotation.  Any other filters cause this?

**Comment by YZYwoazzzzz** [comment]
> 1. rMATS doesn't keep track of which specific reads from the BAM count toward each isoform. I can't think of a good way to extract reads from the BAM so that the inclusion and exclusion reads are cleanly separated

So I can just filter the bam file with the same criteria of  rmats and manually check it, right?

**Comment by EricKutschera** [comment]
I don't think any other filter changed from v4.1.0 to v4.1.1. If you can provide your input files and command line arguments then I can try to debug

Yes, you can manually filter the bam file

**Comment by YZYwoazzzzz** [comment]
I finially found this differences were from my negligence. The reduntant files in --tmp file cause  the repeat counts. I delect it and the rerun results  were the same in two version.
