### ISSUE TITLE
Interpreting rMATs output 

### ISSUE THREAD

**Issue by fidibidi** [Xinglab/rmats-turbo#132]
Hello!

First off, let me say that I love this program, it's easy to use, and the results are great!
Thanks for the hard work!

I just had a question regarding the rMATS output. 

There are many scenarios where the exon start and end (ie exon) are similar between several different events (for a given gene) picked up by rMATS but the difference is in the upstream and downstream ES and EE.

Sometimes, the differences between these events seems to be incredibly small. 

Could you please elaborate alittle bit more on what those are and why they are being recognized as different splicing events even though it’s the same exon?

Is it possible to merge these results?

Below is an example of such occurrence...

Thanks!

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/fidibidi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/fidibidi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

56847 | ENSG00000078487 | ZCWPW1 | chr7-100016733-100016812-100013597-100013717-100017252-100017506 | chr7 | - | 100016733 | 100016812 | 100013597 | 100013717 | 100017252 | 100017506 | 56847 | 0,4,1,0,0,0,2,2,4,2 | 0,0,0,0,0,0,0,0,0,0 | 1,0,0,1,4,1,3,2,4,2 | 0,0,0,0,1,3,0,0,0,0 | 162 | 83 | 9.88E-01 | 9.99E-01 | NA,1.0,1.0,NA,NA,NA,1.0,1.0,1.0,1.0 | 1.0,NA,NA,1.0,0.672,0.146,1.0,1.0,1.0,1.0 | 0.148 | 0.148
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
56848 | ENSG00000078487 | ZCWPW1 | chr7-100016733-100016812-100013597-100013720-100017252-100017506 | chr7 | - | 100016733 | 100016812 | 100013597 | 100013720 | 100017252 | 100017506 | 56848 | 0,4,1,0,0,0,2,2,2,3 | 0,0,0,0,0,0,0,0,0,0 | 1,1,0,1,4,1,3,2,4,2 | 1,0,0,0,3,0,0,0,0,0 | 162 | 83 | 9.99E-01 | 9.99E-01 | NA,1.0,1.0,NA,NA,NA,1.0,1.0,1.0,1.0 | 0.339,1.0,NA,1.0,0.406,1.0,1.0,1.0,1.0,1.0 | 0.139 | 0.139
117246 | ENSG00000078487 | ZCWPW1 | chr7-100016733-100017420-100013597-100013720-100018244-100018301 | chr7 | - | 100016733 | 100017420 | 100013597 | 100013720 | 100018244 | 100018301 | 117246 | 0,0,0,0,0,0,0,0,1,1 | 0,0,0,0,0,0,0,0,0,0 | 0,1,1,0,0,0,0,0,0,0 | 0,0,0,0,0,3,0,0,0,0 | 166 | 83 | NA | NA | NA,NA,NA,NA,NA,NA,NA,NA,1.0,1.0 | NA,1.0,1.0,NA,NA,0.0,NA,NA,NA,NA | 0.333 | 0.333

</body>

</html>

**Comment by EricKutschera** [comment]
rMATS will define a new event if any of the splice sites except the upstream start or downstream end are different. In other words, it will merge events where the only different coordinates are the upstream start or downstream end. The diagram here (https://github.com/Xinglab/rmats-turbo/tree/v4.1.1#output) shows how rMATS counts reads toward events. If any of the splice sites (besides upstream start and downstream end) change, then it will change which reads "count"

In your example, ID=56847 and ID=56848 only have a different coordinate for upstream end (100013717, 100013720). For ID=117246 the exon end is different (100017420), upstream end is the same as ID=56848, and the downstream start and end are different (100018244, 100018301). As a result of the different coordinates for the different event IDs, the counts are different as well

I don't think there is a good way to merge the results. From the diagram, if some of the splice sites are the same then some of the reads will be counted toward both events. Depending on how you use the results, it may make sense to pick one event out of the set of "similar" events and then ignore the others. It might also make sense to treat all the events as being distinct
