### ISSUE TITLE
rMATS not running with fastq.gz files location in s1 and s2

### ISSUE THREAD

**Issue by OnkarMulay** [Xinglab/rmats-turbo#136]
Hi,

I have zipped fastq files.
rMATS not running with fastq.gz files location in s1 and s2

Is there any command that needs to be changed or written to this?

python3 rmats-turbo-4.1.0/rmats.py --s1 a_s1.txt --s2 b_s2.txt --gtf HomoSapiens/Homo_sapiens.GRCh37.72.gtf --bi Starindexv2_72 --variable-read-length -t paired --readLength 200 --nthread 4 --od rMtas_sampl --tmp tmp_output_sampl

Error:
Aug 02 14:52:10 ..... started STAR run
Aug 02 14:52:11 ..... loading genome
Aug 02 14:53:49 ..... processing annotations GTF
Aug 02 14:53:59 ..... inserting junctions into the genome indices
Aug 02 14:55:12 ..... started mapping

ReadAlignChunk_processChunks.cpp:201:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or >

Aug 02 14:55:14 ...... FATAL ERROR, exiting

**Comment by EricKutschera** [comment]
It looks like you are using version 4.1.0, but support for fastq.gz files was not added until 4.1.1. The code change to allow fastq.gz files is only a few lines and you could directly edit your copy of rmats.py. Here's the code change: https://github.com/Xinglab/rmats-turbo/pull/19/files

**Comment by OnkarMulay** [comment]
Awesome!! If you are sure replacing the file in rMATS 4.1.0 is not an issue...
Then thanks I'll use it and closing the issue
