### ISSUE TITLE
Using rmats-turbo on PacBio data

### ISSUE THREAD

**Issue by aa9gj** [Xinglab/rmats-turbo#137]
Hello, thanks in advance for taking the time to respond to this. I am attempting to run rmats on PacBio long reads directly using the varying read length option. I am wondering if that's feasible? I am going to be generating a corrected reference using lr2rmats pipeline and rerun my short read data on that also. Thanks again

**Comment by EricKutschera** [comment]
rmats was designed to work on short read data and while you may get some results with PacBio reads there are some potential issues. PacBio reads are likely to fail some of the filters in rmats. rmats filters out multi-mapped reads and also reads that have an insertion, deletion, or mismatch operation in the CIGAR. rmats also uses an effective length calculation when determining the inclusion levels (PSI values) and that might not make sense for PacBio reads

Using lr2rmats to get a GTF from the PacBio reads and then using that GTF to run rmats on short read data makes sense

**Comment by aa9gj** [comment]
Thanks for the prompt response Eric. Bummer! By any chance are there any recommendation for an awesome software similar to rmats but compatible with PacBio reads that you would recommend? Thanks again

**Comment by EricKutschera** [comment]
We are working on a tool to quantify isoforms from long read data, but it is not available yet: https://github.com/Xinglab/rmats-turbo/issues/98

Here is similar thread that mentions a few long read tools: https://github.com/Xinglab/rmats-turbo/issues/109#issuecomment-816666479

**Comment by wenronchen** [comment]
Hello, I wonder whether the rMATS which is compatible with PacBio long reads data is available or not. Thank you.

**Comment by EricKutschera** [comment]
We have released a new tool for long read data. See this post for more details: https://github.com/Xinglab/rmats-turbo/issues/98#issuecomment-1099257299
