### ISSUE TITLE
Query on interpreting read outcome

### ISSUE THREAD

**Issue by hoggdog** [Xinglab/rmats-turbo#140]
Hi Eric, thanks for all you do with providing support for rmats!!

Wondering if you would consider my 'read outcomes' acceptable, or if it's worth trying to improve. Here's a representative example:
```
USED: 1233437722
NOT_PAIRED: 1113703
NOT_NH_1: 236058522
NOT_EXPECTED_CIGAR: 5814482
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 70901259
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 2284405
CLIPPED: 0
total: 1549610093
```

So ```1233437722/1549610093*100= 79.59%``` of reads were used, which seems reasonable.

The percentage of NOT_PAIRED ```(0.07%)```, NOT_EXPECTED_CIGAR ```(0.37%)```, JUNCTION_NOT_MATCHED_TO_ANNOTATION ```(0.147%)```, and EXON_NOT_MATCHED_TO_ANNOTATION ```(4.57%)``` seem low enough.

NOT_NH_1 accounts for ```15.23%``` of the reads, indicating multi-mapping reads from my alignment with STAR. It seems there are options to reduce the number of alignments for these multi-mapping reads, for example from the STAR manual:

```--outSAMmultNmax 1 will output exactly one SAM line for each mapped read. Note that NH:i: tag in STAR will still report the actual number of loci that the reads map to, while the the number of reported alignments for a read in the SAM file is min(NH,--outSAMmultNMax).``` Based on this wording, I'm not 100% sure if this will solve the NH>1 issue.

Is this an approach you might recommend? And, more importantly, would you predict this would meaningfully increase the number of reads that are utilized by rmats?

Thanks,
Simon

**Comment by EricKutschera** [comment]
Your read outcomes seem ok to me. NOT_NH_1 of `15.23%` is reasonable and does not necessarily indicate a problem

You might be able to disable or work around the NOT_NH_1 filter, but it's up to you to decide if you want those reads to be counted. One reason to filter out reads with NH > 1 is so that rmats will not count a read multiple times. Another reason is that there is less confidence about a multi-mapped read since the aligner found multiple possible alignments

I don't think that `--outSAMmultNmax 1` by itself will allow those reads to pass the NOT_NH_1 filter. All the reads that were failing the filter with your original settings will continue to fail. But now for each original read sequence, only the alignment with the highest score will be in the SAM file. Having one alignment per read addresses the issue of rmats counting a read multiple times. However, those alignments will still have an NH tag greater than 1 which is what rmats checks for the NOT_NH_1 filter

After aligning with `--outSAMmultNmax 1` you could process the SAM file that STAR outputs and set all the NH tag values to 1 before using that SAM file with rmats. That would essentially disable the NOT_NH_1 filter. Those reads might then be caught be another filter like EXON_NOT_MATCHED_TO_ANNOTATION but some may end up as USED

**Comment by hoggdog** [comment]
Thanks for the previous answer, @EricKutschera!

I do also have one more related query from a separate dataset, which has me stumped.

I have mapped reads using STAR (```v2.7.8a```) to Hg19 (GRCh37.p13) using FASTA & GTF annotation directly from GENCODE. Here is a representative example of the STAR log, where ```Uniquely mapped reads``` account for ```85.90%``` of total, which seemed fine.

``` 
                          Number of input reads |       111538039
                      Average input read length |       289
                                    UNIQUE READS:
                   Uniquely mapped reads number |       95814985
                        Uniquely mapped reads % |       85.90%
                          Average mapped length |       287.54
                       Number of splices: Total |       94785038
            Number of splices: Annotated (sjdb) |       93794336
                       Number of splices: GT/AG |       93792414
                       Number of splices: GC/AG |       561072
                       Number of splices: AT/AC |       102833
               Number of splices: Non-canonical |       328719
                      Mismatch rate per base, % |       0.33%
                         Deletion rate per base |       0.02%
                        Deletion average length |       2.08
                        Insertion rate per base |       0.01%
                       Insertion average length |       1.78
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       8408776
             % of reads mapped to multiple loci |       7.54%
        Number of reads mapped to too many loci |       37371
             % of reads mapped to too many loci |       0.03%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |       0
       % of reads unmapped: too many mismatches |       0.00%
            Number of reads unmapped: too short |       7250343
                 % of reads unmapped: too short |       6.50%
                Number of reads unmapped: other |       26564
                     % of reads unmapped: other |       0.02%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%
```

Next, I use these files as input to rMATS (```v4.1.1```) with the following parameters: ```--b1 drug.txt --b2 control.txt --gtf $gtfFile --novelSS --variable-read-length --allow-clipping --tmp $outDir --od $outDir -t paired --libType fr-firststrand --nthread 12 --readLength 150 ```, where ```$gtfFile``` is the exact same GTF file from GENCODE used for the STAR ```genomeGenerate``` process. 

However I'm finding that only a small proportion of the reads are being utilized by rMATS- see below for output from ```read_outcomes_by_bam.txt``` on the same sample as above, where only ```(97593218/231814653)*100%=42%``` of reads are being used. It seems many reads are being excluded on the basis of EXON_NOT_MATCHED_TO_ANNOTATION (```22.2%```) & JUNCTION_NOT_MATCHED_TO_ANNOTATION (```16.3%```), which is surprising and a little confusing given the high % of uniquely mapped reads. Do you have any ideas/suggestions on what might be causing this behaviour?

```
USED: 97593218
NOT_PAIRED: 52827
NOT_NH_1: 40211744
NOT_EXPECTED_CIGAR: 4538439
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 51578378
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 37840047
CLIPPED: 0
TOTAL_FOR_BAM: 231814653
```

**Comment by EricKutschera** [comment]
I agree that having such a large percent of JUNCTION_NOT_MATCHED_TO_ANNOTATION seems wrong based on your STAR output. STAR said that almost all of the splice sites were annotated so I would expect almost all junction reads to be matched to the annotation
```
Number of splices: Total            | 94785038
Number of splices: Annotated (sjdb) | 93794336
```

One possible explanation is that the strand checking is not going as expected. In your command line you have: `--libType fr-firststrand`. In your `read_outcomes_by_bam.txt` the number of USED reads is close to the sum of NOT_MATCHED_TO_ANNOTATION reads:
```
USED: 97,593,218
EXON_NOT_MATCHED_TO_ANNOTATION: 51,578,378
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 37,840,047
51578378 + 37840047 = 89,418,425
```

Can you try running with `--libType fr-unstranded`? It might be that your reads actually do match to the annotation, but rmats is looking at the wrong strand about half of the time

**Comment by hoggdog** [comment]
You are absolutely right, @EricKutschera 

Re-running with ```--libType fr-unstranded``` greatly reduces reads excluded due to JUNCTION_NOT_MATCHED_TO_ANNOTATION, resulting in rMATS using ```78.99%``` of reads. Read outcomes for the file mentioned above are below.
```
USED: 183119549
NOT_PAIRED: 52827
NOT_NH_1: 40211744
NOT_EXPECTED_CIGAR: 4538439
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 3572392
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 319702
CLIPPED: 0
TOTAL_FOR_BAM: 231814653
```

As it turns out, I was given the wrong information & these libraries were actually prepared with a non-stranded library prep kit!

Thanks again!
