### ISSUE TITLE
Dose rMATS output upstream and downstream junction counts of an SE event separately?

### ISSUE THREAD

**Issue by dontkme** [Xinglab/rmats-turbo#141]
Hi Eric,

I'm focusing on the SE events research, and rMATS works very well in the SE events detection. But when I checked SE events in IGV or sashimi plots, I found that many MXE events were recognized as SE events. I think comparing the SE's upstream junction counts and downstream junction counts will help filter MXE from SE output. I didn't find an output have the up/downstream junction counts. Did I missed it?

Thank you in advance!
Best wishes,
Kaining

**Comment by dontkme** [comment]
Hi, 

I found the rMATS may output individualCounts.[AS].txt, which may meet my needs. But when I used rMATS v4.1.1 and started from bam files, the outputs don't contain individualCounts table. 
I used run command like this:
`python3 ./rmats_turbo_v4_1_1/conda_envs/rmats/bin/rmats.py --b1 E11.bams.txt --b2 E18.bams.txt --gtf ./genomes/GENCODE_M24_GRCm38.p6/gencode.vM25.annotation.gtf -t paired --readLength 101 --nthread 6 --od E11_E18_GENCODEM25_rmats_od --tmp E11_E18_tmp`
Do I need other options?

Best wishes,
Kaining

**Comment by EricKutschera** [comment]
There is a pull request to add code to output upstream and downstream junction counts in individualCounts.[AS].txt: https://github.com/Xinglab/rmats-turbo/pull/41

That pull request has not been merged yet and the code is not in v4.1.1. The change is fairly large and it has not been rigously tested yet, although I do not know of any problems with that code and I think it should work. If you want to try it out, you can clone the source code, switch to that branch, and follow the build instructions: https://github.com/Xinglab/rmats-turbo/tree/kutscherae-individual-counts#build

**Comment by dontkme** [comment]
Hi Eric,
Thank you for your response.  I will use other tools to count the junctions. Thanks again.
Best,
Kaining

**Comment by dontkme** [comment]
Hi Eric,
I built the branch, and the prep task seems worked well, the tmp files are fine. But most of counts of post task counts all '0', that's wired.

`python3 rmats-turbo-kutscherae-individual-counts/rmats.py --nthread 4 --gtf GENCODE_M24_GRCm38.p6/gencode.vM25.chr_patch_hapl_scaff.annotation.gtf -t paired --readLength 100 --variable-read-length --od combinded_post_out3 --tmp sb_combined.od/.tmp/ --b1 combindedbams.txt --task post`
gtf: 18.59574580192566
There are 56262 distinct gene ID in the gtf file
There are 144580 distinct transcript ID in the gtf file
There are 34821 one-transcript genes in the gtf file
There are 853569 exons in the gtf file
There are 27329 one-exon transcripts in the gtf file
There are 22127 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 2.569763
Average number of exons per transcript is 5.903783
Average number of exons per transcript excluding one-exon tx is 7.046763
Average number of gene per geneGroup is 7.492527
statistic: 0.023573637008666992
loadsg: 0.02755284309387207

==========
Done processing each gene from dictionary to compile AS events
Found 19201 exon skipping events
Found 748 exon MX events
Found 8470 alt SS events
There are 5401 alt 3 SS events and 3069 alt 5 SS events.
Found 4162 RI events
==========

ase: 0.9731369018554688
count: 3.7733917236328125
Processing count files.
Done processing count files.

The screen information also shows fine. But the output are all in 0.

head individualCounts.SE.txt
ID	upstream_to_target_count	target_to_downstream_count	target_count	upstream_to_downstream_count
0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0
1	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0
2	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0
3	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0
4	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0
5	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0


more SE.MATS.JC.txt

ID	GeneID	geneSymbol	chr	strand	exonStart_0base	exonEnd	upstreamES	upstreamEE	downstreamES	downstreamEE	ID	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen	PValue	FDR	IncLevel1	IncLevel2	IncLevelDifference	upstream_to_target_count	target_to_downstream_count	target_count	upstream_to_downstream_count
0	"ENSMUSG00000116431.1"	"Slfn3"	chrWSB_EIJ_MMCHR11_CTG3	+	218206	218373	215470	215546	236483	237553	0	0,0,0,0,0,0	0,0,0,0,0,0			198	99	NA	NA	NA,NA,NA,NA,NA,NA		NA	0,0,0,0,0,0	0,0,0,
0,0,0	0,0,0,0,0,0	0,0,0,0,0,0
1	"ENSMUSG00000103326.4"	"Ctla4"	chrKK082441.1	+	244897	245007	244101	244449	246273	247494	1	0,0,0,0,0,0	0,0,0,0,0,0			198	99	NA	NA	NA,NA,NA,NA,NA,NA		NA	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0
2	"ENSMUSG00000115963.1"	"Abhd18"	chrMG89_PATCH	+	300757	300809	300462	300547	305093	305194	2	0,0,0,0,0,0	0,0,0,0,0,0			151	99	NA	NA	NA,NA,NA,NA,NA,NA		NA	0,0,0,0,0,0	0,0,0,
0,0,0	0,0,0,0,0,0	0,0,0,0,0,0

Maybe something wrong with the output process? Need you help!

Thank you very much.

Best,
Kaining

**Comment by EricKutschera** [comment]
Do all the rows in `individualCounts.SE.txt` have only zero counts? Or do some have non-zero counts? Since you ran the post step with just one sample group (--b1 without --b2) rMATS does not filter the output files. That could result in a lot of events that were detected just based on the GTF file without any supporting reads and with zero counts

How do the `{datetime}_read_outcomes_by_bam.txt` files from the prep steps look. If only a small number of reads passed the filters in the prep step then the zero counts are expected in the post step

**Comment by dontkme** [comment]
Hi Eric,

Thank you very much for your quick reply.
I checked the `individualCounts.SE.txt`, it don't have non-zero counts. 

Two samples of {datetime}_read_outcomes_by_bam.txt looks like these below.

E11_2_Aligned.sortedByCoord.out.bam

USED: 112871037
NOT_PAIRED: 0
NOT_NH_1: 28997962
NOT_EXPECTED_CIGAR: 2676870
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 89426070
JUNCTION_NOT_MATCHED_TO_ANNOTATION:   74535449
CLIPPED: 0
TOTAL_FOR_BAM: 308507388

E14_1_Aligned.sortedByCoord.out.bam
USED: 104829543
NOT_PAIRED: 0
NOT_NH_1: 22666690
NOT_EXPECTED_CIGAR: 2466539
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 82342167
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 64043673
CLIPPED: 0
TOTAL_FOR_BAM: 276348612

P.S. I also run the individual count version rmats.py with `--task both` and one group input `--b1 bams.txt`, the output SE.MATE.JCEC.txt have non-zero cells, but only in 'IJC_SAMPLE_1' and 'target_count' columns; the 'SJC_SAMPLE_1',  'upstream_to_target_count',	'target_to_downstream_count' and 'upstream_to_downstream_count' columns are still all be '0,0,0,0,0,0'

Best,
Kaining

**Comment by EricKutschera** [comment]
For both examples from read_outcomes_by_bam only about 38% of the reads are USED with about 29% EXON_NOT_MATCHED_TO_ANNOTATION and 23% JUNCTION_NOT_MATCHED_TO_ANNOTATION

That indicates that the GTF used with rMATS does not match up well with the reference data used to create the BAM files. Seeing only `target_count` columns in the JCEC file as non-zero could be because it is easier for the different coordinates between the BAMs and the GTF to randomly overlap for an exon read as compared to randomly getting the two endpoints of a junction read to match exactly

In a previous post you had a command line with:
`--gtf ./genomes/GENCODE_M24_GRCm38.p6/gencode.vM25.annotation.gtf`
Then later you had a command line with:
`--gtf GENCODE_M24_GRCm38.p6/gencode.vM25.chr_patch_hapl_scaff.annotation.gtf`

Maybe only one of those GTFs is compatible with the BAM files

**Comment by dontkme** [comment]
Thanks Eric, I will try to switch the GTF.

**Comment by Gilbert-Giri** [comment]
@EricKutschera has the code for getting individual inclusion counts for upstream and downstream exons been incorporated in the 4.2 release? I was trying to get them but don't see them in temp or output files. Or is there a way I could extract them from any of the tmp/output files?

**Comment by EricKutschera** [comment]
The code for outputting the individual counts is still in pull request: https://github.com/Xinglab/rmats-turbo/pull/41

Hopefully that code will be merged for the next release. There's no way to get those counts from the v4.2.0 output. Essentially the current release doesn't do anything to distinguish the upstream and downstream junctions and stores the counts as a single number

**Comment by EricKutschera** [comment]
`--individual-counts` is in v4.3.0
