### ISSUE TITLE
 error: unrecognized arguments: --tmp

### ISSUE THREAD

**Issue by wanle159** [Xinglab/rmats-turbo#142]
I have tried to use different directories as tmp. All of them came back this error. Would you please suggest which tmp that I should use? 
 error: unrecognized arguments: --tmp

Thank you

**Comment by EricKutschera** [comment]
That error doesn't look like it depends on the value you give after --tmp. It seems to indicate that --tmp is not expected at all regardless of value

Do you know what version of rmats you have (you could try running rmats with `--version`)? My guess is that you are running a version before v4.1.0

**Comment by wanle159** [comment]
Thank you for the reply. I installed rmats via conda on my cluster node. Yes, It's v3.1.0.

**Comment by EricKutschera** [comment]
I would recommend using v4.1.1. I think these commands should install that version to a new conda environment:
```
conda create --prefix /path/to/new_conda_env
conda activate /path/to/new_conda_env
conda install -c conda-forge -c bioconda rmats=4.1.1
```

**Comment by wanle159** [comment]
Thank you for the detailed information. The app runs now!!

**Comment by yutaixian** [comment]
> I would recommend using v4.1.1. I think these commands should install that version to a new conda environment:
> 
> ```
> conda create --prefix /path/to/new_conda_env
> conda activate /path/to/new_conda_env
> conda install -c conda-forge -c bioconda rmats=4.1.1
> ```

hi  I am a new user. I installed rMATS through conda according to the method you provided. but  when I run it, it reported an error:  [2]+  段错误               (吐核)nohup python rmats.py --b1 /mnt/sdb1/users.......

How can I solve this problem?

**Comment by EricKutschera** [comment]
Do you have a specific error message? I would recommend using the latest version `rmats=4.3.0` which may give a better error message
