### ISSUE TITLE
result interpretation

### ISSUE THREAD

**Issue by elva0328** [Xinglab/rmats-turbo#145]
hello, rmats is a wonderful tool. I've already got the result and visualized the result, but I'm confused about how to interpret the result, could you help with this.
for example:
![splicing](https://user-images.githubusercontent.com/53468690/131538730-051e1476-29f3-4275-8f19-75cac8369b98.png)
in this skipped exon event, we have samples 1-3,  which sample has the SE event? or which sample has the increased SE event?  and what additional information we can see from the result?
appreciate your response.

**Comment by EricKutschera** [comment]
See https://github.com/Xinglab/rmats2sashimiplot/issues/68
