### ISSUE TITLE
Bam.bai not created in temporary folder

### ISSUE THREAD

**Issue by OnkarMulay** [Xinglab/rmats-turbo#147]
I have run rMATS and I get the outputs. 
But when I look into temporary directory I don't see only bam.bai files

What could be the issue?

Does this mean the outputs are also wrong?

**Comment by EricKutschera** [comment]
rMATS does not create or use bam.bai files

**Comment by OnkarMulay** [comment]
Is it so? The previous version I got them.
But no issues at all. Thanks for addressing the issue. 👍
