### ISSUE TITLE
empty  output 

### ISSUE THREAD

**Issue by DerekTerry** [Xinglab/rmats-turbo#15]
my  run code like following,   to compare two paired-groups A and D:

```
srun  ./software/wrapped_rmats.sh  \
./'sheepH_A_bamlist.txt'    ./'sheepH_D_bamlist.txt'   \  #bam file path of  two group 
./human.gtf     \                                                              #gtf  annotation
48  \                                                                                #threads
. /outputdir/AS_AD_compare2A   \                                 #outputfile  
./temp_dir/tmp_$RANDOM    >log_AD 2>&1 &            #temp_file randomly named 
```

my output file only has header:  [AS type ].MATS.JCEC.txt

```
ID	GeneID	geneSymbol	chr	strand	1stExonStart_0base	1stExonEnd	2ndExonStart_0base	2ndExonEnd	upstreamES	upstreamEE	downstreamES	downstreamEE	ID	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen	PValue	FDR	IncLevel1	IncLevel2	IncLevelDifference

```

the log file 

```
module add R-3.6.1
gtf: 4.323092699050903
There are 27054 distinct gene ID in the gtf file
There are 29118 distinct transcript ID in the gtf file
There are 25073 one-transcript genes in the gtf file
There are 239130 exons in the gtf file
There are 6070 one-exon transcripts in the gtf file
There are 6070 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.076292
Average number of exons per transcript is 8.212446
Average number of exons per transcript excluding one-exon tx is 10.111940
Average number of gene per geneGroup is 4.199280
statistic: 0.010064125061035156
novel: 483.66304659843445
The splicing graph and candidate read have been saved into /public1/home/sc30941/transcription_analysis/ay_sheep/pj1_sheepNative_res/tmp_2738/2020-06-24-17:33:46_053614.rmats
save: 0.006211042404174805
loadsg: 0.001512765884399414

==========
Done processing each gene from dictionary to compile AS events
Found 364 exon skipping events
Found 39 exon MX events
Found 385 alt SS events
There are 329 alt 3 SS events and 56 alt 5 SS events.
Found 216 RI events
==========

ase: 0.25577592849731445
count: 0.25571632385253906
Processing count files.
Done processing count files.

```

**Comment by EricKutschera** [comment]
Are you using the --readLength argument? In 4.1.0 all reads are required to match --readLength unless --variable-read-length is used. Using --variable-read-length causes reads that do not match --readLength to also be counted.

**Comment by DerekTerry** [comment]
Yes,  --readLength  was set as 150(using Ilumina platform，read length：PE150) -------- 原始邮件 --------发件人： Eric Kutschera <notifications@github.com>日期： 2020年6月24日周三 晚上8:41收件人： Xinglab/rmats-turbo <rmats-turbo@noreply.github.com>抄送： Durian <dedicatedforsss@163.com>, Author <author@noreply.github.com>主    题： Re: [Xinglab/rmats-turbo] empty  output  (#15)
Are you using the --readLength argument? In 4.1.0 all reads are required to match --readLength unless --variable-read-length is used. Using --variable-read-length causes reads that do not match --readLength to also be counted.

**Comment by EricKutschera** [comment]
You could try running with both `--variable-read-length` (to disable read length filtering) and `--statoff` (to disable this filtering: https://github.com/Xinglab/rmats-turbo/blob/master/rmats.py#L248)

If the \*.MATS.\*.txt files are still empty then rMATS is not able to find reads in your BAMs to support alternative splicing based on the transcripts in your gtf. Maybe there is an issue with one of the input BAMs or the gtf

**Comment by DerekTerry** [comment]
> You could try running with both `--variable-read-length` (to disable read length filtering) and `--statoff` (to disable this filtering: https://github.com/Xinglab/rmats-turbo/blob/master/rmats.py#L248)
> 
> If the *.MATS.*.txt files are still empty then rMATS is not able to find reads in your BAMs to support alternative splicing based on the transcripts in your gtf. Maybe there is an issue with one of the input BAMs or the gtf

Thanks for your reply!
The output was  quite odd ;  I have add the two parameters as instruction,  and all  [AS type ].MATS.JCEC.txt  files is no longer empty rather like following:
  ```
#raw.input.RI.txt
ID	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen
0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	187	148
1	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	296	148
2	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	296	148
3	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	152	148

#A5SS.MATS.JCEC.txt
ID	GeneID	geneSymbol	chr	strand	longExonStart_0base	longExonEnd	shortES	shortEE	flankingES	flankingEE	ID	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen	PValue	FDR	IncLevel1	IncLevel2	IncLevelDifference
0	"ENSOARG00000002238"	NA	chrAMGL01125088.1	-	2293	2397	2296	2397	2237	2291	0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	151	148	NA	NA	NA,NA,NA,NA,NA,NA	NA,NA,NA,NA,NA,NA	NA
1	"ENSOARG00000016505"	"CPT1A"	chr21	-	45471143	45471342	45471146	45471342	45468077	45468266	1	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	0,0,0,0,0,0	151	148	NA	NA	NA,NA,NA,NA,NA,NA	NA,NA,NA,NA,NA,NA	NA
2	"ENSOARG00000008574"	"RASGRP2"	chr21	-	42291211	42291317	42291214	42291317	42290623	42290686	2

```

my gtf file downloaded from ensembl, and BAM file was derived from STAR aligner using 2-PASS strategy, which can successively output the expression matrix of whole genome by  STAR's built-in function.

I was confused that it seems rmats get  the reads  which lengths 151bp  (`IncFormLen`), and skip 148bp (`SkipFormLen`). What's more, any splicing event was undetectable.

**Comment by EricKutschera** [comment]
IncFormLen and SkipFormLen are calculated based on the splicing event, --readLength, and --anchorLength as described here: https://github.com/Xinglab/rmats-turbo#output . The IncFormLen and SkipFormLen calculations are not based on the reads from the BAM files and do not indicate that rmats saw any reads with those lengths. Those numbers are only used to normalize the read counts when calculating the inclusion level.

The zero counts in the output files indicate that all the AS events were detected based on the gtf without any supporting reads from the BAMs. It may be that the reads in the BAMs are not uniquely mapped (NH tag != 1: https://github.com/Xinglab/rmats-turbo/blob/master/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L207). Or maybe the reads in the BAMs are not mapped to the exons defined in the gtf

**Comment by Lyuzu** [comment]
I met the same problem and I noticed the running time was abnormally short (about <5 min) . The files in output folder were almost empty except fromGTF files.

**Comment by Lyuzu** [comment]
While gtf file and bam files are absolutely the same, different versions of rMATS gave different output. 
rMATS 4.1.0 
`(python37) python rmats.py --paired-stats --b1 b1.txt --b2 b2.txtt --gtf gencode.v34.primary_assembly.annotation.gtf -t paired --readLength 90 --nthread 4 --od /home/ --tmp /home/tmp --task post`
![image](https://user-images.githubusercontent.com/42428287/87849479-a4898f80-c91b-11ea-95f7-abc8f6068585.png)
rMATS 4.0.2
`(python27)python /home/rmats.py --b1 b1.txt --b2 b2.txt --gtf gencode.v34.primary_assembly.annotation.gtf --od /home/ -t paired --readLength 90 --cstat 0.0001 --libType fr-unstranded`
![image](https://user-images.githubusercontent.com/42428287/87849523-e1ee1d00-c91b-11ea-8712-53b7682aacc3.png)

**Comment by EricKutschera** [comment]
The command you posted for 4.1.0 has `--task post`. Did you have any issue with the `--task prep` step or did you try without `--task` (which defaults to both)? 4.0.2 did not have `--task` and always behaved like `--task both`

In 4.0.2 there was a bug were --readLength was only checked for reads that did not span a splice junction. In 4.1.0 all reads are required to match --readLength unless --variable-read-length is used. You could try adding `--variable-read-length` to your 4.1.0 command

Can you include what is printed to the terminal after running the 4.1.0 command?

**Comment by Lyuzu** [comment]
> The command you posted for 4.1.0 has `--task post`. Did you have any issue with the `--task prep` step or did you try without `--task` (which defaults to both)? 4.0.2 did not have `--task` and always behaved like `--task both`
> 
> In 4.0.2 there was a bug were --readLength was only checked for reads that did not span a splice junction. In 4.1.0 all reads are required to match --readLength unless --variable-read-length is used. You could try adding `--variable-read-length` to your 4.1.0 command
> 
> Can you include what is printed to the terminal after running the 4.1.0 command?
Thank you so much for your reply. I tried without `--task` and solved the problems about PAIRADISE version ( because firstly I installed new rMATS by anaconda and manually installed a wrong version of PAIRADISE). The output seemed normal. 
Thanks again,  the update of  paired statistical analysis is really helpful
