### ISSUE TITLE
transcript specific IDs in output file?

### ISSUE THREAD

**Issue by joeellis1331** [Xinglab/rmats-turbo#155]
Is there any way to output specific transcript_IDs in addition to gene_IDs? I am not sure whether providing a different GTF file can fix this or its just not part of the current framework.  

Some target events have very specific/important alternatively spliced exons which depending on its splicing outcome completely changes the function of the coded protein. Having the specific transcript would allow us to ensure that between analysis/cell lines/experiments/etc. we are referring to the same exon as the 'exon numbers' are transcript dependent.

**Comment by joeellis1331** [comment]
I saw a previous request, my apologies  for missing it

**Comment by NayeliGutierrez** [comment]
Hi @joeellis1331 , 

I am also interested in obtaining specific transcript_IDs. How did you retrieve them? I looked for the previous request you mentioned but couldn't find it. Could you point me in the right direction?

Thanks!
Nayeli

**Comment by joeellis1331** [comment]
Hi @NayeliGutierrez,

The request I was referencing was #148 . There is a script that Eric uses but was not part of the pipeline (probably is still not?) to identify isoforms. So you will have to likely modify it to work with your workflow. Hope that helps!

Best
-Joe

**Comment by NayeliGutierrez** [comment]
Thank you so much, that is exactly what I was looking for! 

Best,
Nayeli
