### ISSUE TITLE
Questions on --novelSS

### ISSUE THREAD

**Issue by lennartraman** [Xinglab/rmats-turbo#156]
Hi devs,

Thanks for rmats-turbo!

I was wondering, using --novelSS, how are _de novo_ events annotated (SE, RI, A5SS, ...)? Is this based on the distance to known splice sites? In this context, how is a _de novo_ A5SS differentiated from an alternative transcription start site (or similar, an A3SS to alternative poly adenylation)?

Thanks a lot for your valuable insight!

Best, Lennart

**Comment by EricKutschera** [comment]
rMATS detects events based on the exons and splice junctions it knows about. It starts with the exons and splice junctions defined by transcripts in the GTF file. When rMATS processes a read from a BAM file, if that read contains a splice junction which is not in the GTF but the two endpoints of the junction match with exons in the GTF, then rMATS will define a novel junction going between those two exons. Any event that requires such a junction to be detected ends up in a fromGTF.novelJunction.[AS_Event].txt file

If rMATS is run with --novelSS, when it processes a read from a BAM file with a splice junction which is not in the GTF and only one endpoint of the junction matches with any exon in the GTF, then rMATS will consider the other exons that are annotated as being in a transcript with any of the exons that have the annotated splice site. If an exon is found that can have one of its splice sites adjusted to form a novel exon that fits the junction from the read, then rMATS will use that novel exon (and novel junction). Novel exons created this way are only used if their length is at most --mel (max exon length: default 500) and the junction used to form the novel exon is at least --mil (min intron length: default 50). Any event that required such a junction to be detected ends up in a fromGTF.novelSpliceSite.[AS_Event].txt file

After rMATS parses the BAM files, it has a final set of exons and splice junctions that potentially includes novel junctions and novel splice sites. Then it detects events based on those exons and junctions. rMATS basically tries to find combinations of exons and junctions that fit the pattern of the event definitions in this diagram: https://github.com/Xinglab/rmats-turbo/tree/v4.1.1#output

Here's the code for detecting A3SS and A5SS events: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L1676

For A5SS, rMATS looks at all pairs of connected exons it knows about that have the same start coordinate and where both exons have a splice junction to the same downstream exon. A3SS is similar but with things going in the other direction.

Given the way that rMATS defines novel exons with novel splice sites and the way it detects A3SS and A5SS events, I don't think it will detect an alternative transcription start site or alternative polyadenylation site. The splice site that is "alternative" has to be part of an exon-exon junction so the splice site can't be the start or end of the transcript

**Comment by lennartraman** [comment]
Hi @EricKutschera 

Thanks a lot for the detailed answer! This makes sense.
