### ISSUE TITLE
Method to shrink IncLevelDifference?

### ISSUE THREAD

**Issue by adippolito12** [Xinglab/rmats-turbo#157]
Hello,

I was wondering if you could offer any guidance on approaches to shrink IncLevelDifference values in a way that is analogous to lfcShrink in a DESeq workflow. Moderated effect sizes would be useful for interpreting splicing events across
range of read counts.

Thanks!
Tony

**Comment by EricKutschera** [comment]
I'm not very familiar with shinking for effect sizes. You may have better luck posting in the rmats google group: https://groups.google.com/g/rmats-user-group

**Comment by adippolito12** [comment]
Thanks for the link, Eric! I'll take a look there.

Tony
