### ISSUE TITLE
Different output of direct sample comparison vs. statoff followed by stat

### ISSUE THREAD

**Issue by mapawlak** [Xinglab/rmats-turbo#160]
I get different output when I compare two groups of bam files directly as b1 and b2, and when I run rmats with `--statoff` on all bam files in my experiment followed by `prepare_stat_inputs` and `rmats.py task --stat`. To be more precise I have more splicing events and more significantly changed events in the latter method. There are overlapping sites between those two methods. What can be a reason for that?

**Comment by EricKutschera** [comment]
If you run all of your bams and then later use `prepare_stat_inputs` to compare a subset of the bams then rmats gets to use all of the reads to detect events. If you run two groups of bam files with b1 and b2, then rmats will not detect any events which require reads from some other bam(s) to support novel junctions/splice sites. The main issue is that the rmats output shows counts of inclusion reads and skipping reads. Once rmats detects an event based on the annotation and the input reads, it is possible for the output to show a high inclusion count for a bam even if all the inclusion reads for that bam are for only one of the possible inclusion junctions

This comment from a different issue has more details about this: https://github.com/Xinglab/rmats-turbo/issues/82#issuecomment-767627653
and there is a code change that can help with this issue: https://github.com/Xinglab/rmats-turbo/pull/41

**Comment by mapawlak** [comment]
@EricKutschera many thanks for your prompt reply. It all make sense. Thank you.
