### ISSUE TITLE
Problem when combining different groups into one

### ISSUE THREAD

**Issue by XXXXXuan** [Xinglab/rmats-turbo#164]
Hi rMATS, 

I have a problem while using rMATS. 3 replicates of wildtype as --b2, and other conditions with 3 replicates as --b1, respectively, and I got different results of WT. So if I want to combine them into one matrix to build a heatmap, how could I do? 

Sorry that my poor coding level cannot give me any idea about this. Hoping to get your help. 

Thank you for noticing this question!

**Comment by EricKutschera** [comment]
I'm not sure if I understand your question correctly, but you can compare multiple groups following these instructions: https://github.com/Xinglab/rmats-turbo/tree/v4.1.1#running-the-statistical-model-separately

With that procedure, the event ID for each splicing event will be consistent among the different group comparisons. That way you can use the event ID column in the output files to combine results

**Comment by XXXXXuan** [comment]
Thank you very much! You are so genius that seems easily to understand my poor expression. I'll try it now! 
Hope you can have a nice day:)
