### ISSUE TITLE
error in statistical analysis part -PAIRADISE

### ISSUE THREAD

**Issue by wlqtriumph** [Xinglab/rmats-turbo#167]
Hello, I recently ran into some problem with PAIRADISE when I use **--paired-stats** parameter(rmats v4.1.1 and STAR 2.7.9a) to analyze differential alternative spling events. Here is the command :
rmats.py --od /home/data/t040203/02_project/02_opllSeq/09_isoform/out2 --b1 b1.txt --b2 b2.txt --paired-stats --nthread 8 --gtf /home/data/t040203/03_reference/DNA/Homo_sapiens.GRCh38.104.gtf --readLength 150 --variable-read-length --tmp /home/data/t040203/02_project/02_opllSeq/09_isoform/tmp2

b1.txt and b2.txt are the results of STAR
And this is the  error
![image](https://user-images.githubusercontent.com/95834424/145662585-6d52f770-05bb-4914-84d0-47da5930dda8.png)
 
I am a beginner of this issue, hope to see your reply soon，thank you very very very much.

**Comment by wlqtriumph** [comment]
![image](https://user-images.githubusercontent.com/95834424/145663561-d08a6356-3083-4fbf-b8f7-711c3aef4870.png)
This is  JCEC.raw.input.A3SS.txt

**Comment by EricKutschera** [comment]
That error happens if an old version of PAIRADISE is installed. You can uninstall PAIRADISE and then install the latest version from github. Here is a similar post with some more details: https://groups.google.com/g/rmats-user-group/c/y-6SVjMaW0A/m/ISl802qUAQAJ

**Comment by wlqtriumph** [comment]
Thank you Eric! The problem has been solved successfully. I think of a preach of Confucius, the most famous philosopher in our country: '**不愤不启，不悱不发，举一隅不以三隅反，则不复也**'
