### ISSUE TITLE
Results come out without  summary or SE.MATS.JCEC contents in output file

### ISSUE THREAD

**Issue by ZTP1111** [Xinglab/rmats-turbo#172]
Dear Eric Kutschera：

 

I adore you. I adore you on the other side of the earth.

 

Right now I am using rMATS to analyze my RNA-seq data，however, I am getting stuck in the last stage of this analysis. After using the methods you teach me in the web, I give the machine the following order:

 

python rmats.py --b1 /mnt/e/rna/b1.txt --b2 /mnt/e/rna/b2.txt --gtf /mnt/e/rna/gencode.vM28.annotation.gtf -t paired --readLength 50 --nthread 4 --od /mnt/e/rna/output --tmp /mnt/e/rna/tmp_output

 

I get the following results:

 

gtf: 24.450958728790283

There are 55357 distinct gene ID in the gtf file

There are 142376 distinct transcript ID in the gtf file

There are 34320 one-transcript genes in the gtf file

There are 841979 exons in the gtf file

There are 26910 one-exon transcripts in the gtf file

There are 21835 one-transcript genes with only one exon in the transcript

Average number of transcripts per gene is 2.571960

Average number of exons per transcript is 5.913771

Average number of exons per transcript excluding one-exon tx is 7.058952

Average number of gene per geneGroup is 7.457536

statistic: 0.0233154296875

 

read outcome totals across all BAMs

USED: 0

NOT_PAIRED: 81614274

NOT_NH_1: 82495648

NOT_EXPECTED_CIGAR: 1883486

NOT_EXPECTED_READ_LENGTH: 263589255

NOT_EXPECTED_STRAND: 0

EXON_NOT_MATCHED_TO_ANNOTATION: 0

JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0

CLIPPED: 33097348

total: 462680011

outcomes by BAM written to: /mnt/e/rna/tmp_output/2022-01-09-01_18_09_426119_read_outcomes_by_bam.txt

 

novel: 410.79426741600037

The splicing graph and candidate read have been saved into /mnt/e/rna/tmp_output/2022-01-09-01_18_09_426119_*.rmats

save: 0.02637004852294922

loadsg: 0.0071010589599609375

 

==========

Done processing each gene from dictionary to compile AS events

Found 19004 exon skipping events

Found 734 exon MX events

Found 8341 alt SS events

There are 5311 alt 3 SS events and 3030 alt 5 SS events.

Found 4082 RI events

==========

 

ase: 0.9009499549865723

count: 0.31037449836730957

Processing count files.

Done processing count files.

 

It seems like I have successfully get the final results, however, after I checked into the output file, I did not see any results in summary or SE.MATS.JC. Although a total number of exon skipping events has been calculated, I cannot determine the exact TOP10 of exon skipping events with specific gene names based on the above results. This problem still exits when I am using the test data that you share with me on the web.

 

I am using Ubuntu 20.04 and miniconda3 to install and run rMATS. BAM files were produced by hisat2 and have been sorted. I download mouse gencode.vM28.annotation.gtf from https://www.gencodegenes.org/mouse/. I have also attached some relevant screenshots for you.

 

This problem has bothered me almost a week. I had no way but to ask you for help, only you can help me. Please. Looking forward to your kindly reply.

**Comment by EricKutschera** [comment]
The output shows that no reads were used and also the reasons why:
```
USED: 0
NOT_PAIRED: 81614274
NOT_NH_1: 82495648
NOT_EXPECTED_CIGAR: 1883486
NOT_EXPECTED_READ_LENGTH: 263589255
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 33097348
total: 462680011
```

About half of the reads are `NOT_EXPECTED_READ_LENGTH: 263589255`. You could try adding `--variable-read-length` to your rmats command
