### ISSUE TITLE
question about "IncFormLen" and "SkipFormLen" in the output files

### ISSUE THREAD

**Issue by capricy** [Xinglab/rmats-turbo#179]
Hi rMATS support,

My command line for the run was:

rmats.py --b1 AMT.txt --b2 b2.txt --gtf /hpcdata/bcbb/gaoxn/pipelines/SASHIMI/2022_Jan_JMD/gencode.v19.annotation.gtf -t single --readLength 50 --nthread=8 --od output_AMT --tmp tmp_output_AMT

When I checked the output, I found that majority of the column "IncFormLen" has number 98 from multiple output files and all the column 'SkipFromLen' has number 49. Please see examples below:

![image](https://user-images.githubusercontent.com/18124356/154160112-25723a2a-8a0f-4eaf-8be4-25870a763090.png)

Is it normal? 

Thanks.

C.

**Comment by EricKutschera** [comment]
See this similar question about SkipFormLen values being the same: https://groups.google.com/g/rmats-user-group/c/0KB458mFbWU/m/3jEOTlsrBQAJ

The calculations can change for different exon sizes and whether the output file is JC or JCEC, but the core of the calculation is:
SkipFormLen: `(read_length - 2*anchor_length + 1) -> (50 - 2*1 + 1) -> 49`
IncFormLen: `2*(read_length - 2*anchor_length + 1) -> 2*(49) -> 98`

So yes, that output is normal

**Comment by capricy** [comment]
Thank you very much
