### ISSUE TITLE
rMATS Differential vs Alternative splicing PSI Values (output from rMATS)

### ISSUE THREAD

**Issue by OnkarMulay** [Xinglab/rmats-turbo#190]
Hi,

Regarding output from rMATS:
![image](https://user-images.githubusercontent.com/47315377/159308591-2eeb06d0-8ed6-4fdb-a291-bafb0c88cc32.png)

Here let's say I had 10 samples for 2 conditions. So, I got 20 PSI values. If I change the samples, i.e. swap 5 samples from condition1 to condition2 and similarly swap 5 samples from condition2 to condition1, will the PSI values of the samples change, because the groups are different?

Or it doesn't matter which sample is in which group PSI value of that sample will always remain the same?

Regards,
Onkar

**Comment by EricKutschera** [comment]
Moving a BAM file from --b1 to --b2 or moving the BAM file to a different position within one of --b1 or --b2 will not change the PSI value for that BAM

**Comment by OnkarMulay** [comment]
Thanks for the explanation. 
It means that the differential splicing information is only in Inclusion level difference and InclLevel1 and Inclevel2 are just PSI values, which don't depend on the group of samples in --b1 or --b2.

I hope this interpretation is correct. Appreciate your time and patience
Regards,
Onkar

**Comment by EricKutschera** [comment]
If you only have 1 group then you can run rMATS with all of your BAMs in --b1 and also use --statoff

Also, with a large number of BAMs you may want to run the prep and post steps separately: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#running-prep-and-post-separately

**Comment by OnkarMulay** [comment]
I already have STAR aligned and sorted bam files, I was planning to run rMATS on those bam files. can't I run it directly, without prep and posts steps?

**Comment by EricKutschera** [comment]
You can run with --task both (the default) and get the same results as running prep and post separately. --task both is essentially the same as running --task prep and then running --task post. It may be more efficient to run prep and post separately, but both ways are correct

The prep step can run with bam files. The prep step summarizes the alignment information in the bam files for later use in the post step. The reason for running prep and post steps separately is to split the work across multiple machines by splitting up the bam files for the prep step

**Comment by OnkarMulay** [comment]
Ok, thanks, this helps
