### ISSUE TITLE
Using test files can not find anything

### ISSUE THREAD

**Issue by aojielian** [Xinglab/rmats-turbo#193]
Hi, i want use the test file to do learn how to run it, this is my command line
nohup rmats.py --b1 b1.txt --b2 b2.txt --gtf /home/a1lian/gencode.v19.annotation.gtf -t paired --readLength 50 --nthread 4 --od /home/a1lian/rmats_test/od --tmp /home/a1lian/rmats_test/tmp &
 
The log file shows:
read outcome totals across all BAMs
USED: 92459
NOT_PAIRED: 0
NOT_NH_1: 29482
NOT_EXPECTED_CIGAR: 715
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 53911
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 13225
CLIPPED: 0
total: 189792
outcomes by BAM written to: /home/a1lian/rmats_test/tmp/2022-04-20-14_42_40_259065_read_outcomes_by_bam.txt

novel: 0.284109830856
The splicing graph and candidate read have been saved into /home/a1lian/rmats_test/tmp/2022-04-20-14_42_40_259065_*.rmats
save: 0.105509996414
loadsg: 0.000523090362549

==========
Done processing each gene from dictionary to compile AS events
Found 38134 exon skipping events
Found 2040 exon MX events
Found 12653 alt SS events
There are 7727 alt 3 SS events and 4926 alt 5 SS events.
Found 5558 RI events
==========

ase: 1.87092804909
count: 0.698647022247
Processing count files.
Done processing count files.

But in summary.txt, there is  nothing
EventType       TotalEventsJC   TotalEventsJCEC SignificantEventsJC     SigEventsJCSample1HigherInclusion       SigEventsJCSample2HigherInclusion       SignificantEventsJCEC   SigEventsJCECSample1HigherInclusion     SigEventsJCECSample2HigherInclusion
SE      0       0       0       0       0       0       0       0
A5SS    0       0       0       0       0       0       0       0
A3SS    0       0       0       0       0       0       0       0
MXE     0       0       0       0       0       0       0       0
RI      0       0       0       0       0       0       0       0

Is that normal??

Thanks

**Comment by EricKutschera** [comment]
Running with v4.1.2 using the test data (https://sourceforge.net/projects/rnaseq-mats/files/MATS/testData.tgz/download) should give a few events in the summary file. It looks like you used gencode.v19.annotation.gtf. Along with the test data there is this gtf: https://sourceforge.net/projects/rnaseq-mats/files/MATS/Homo_sapiens.GRCh37.75.tgz/download

If you run with that gtf I think you should get this output in the summary file
```
EventType	TotalEventsJC	TotalEventsJCEC	SignificantEventsJC	SigEventsJCSample1HigherInclusion	SigEventsJCSample2HigherInclusion	SignificantEventsJCEC	SigEventsJCECSample1HigherInclusion	SigEventsJCECSample2HigherInclusion
SE	3	4	0	0	0	1	1	0
A5SS	0	0	0	0	0	0	0	0
A3SS	1	1	0	0	0	0	0	0
MXE	0	1	0	0	0	0	0	0
RI	1	2	0	0	0	0	0	0

```

**Comment by aojielian** [comment]
Thanks Eric,
But today i ran it with your given testdata and gtf files, the log file shows:
/home/a1lian/anaconda3/envs/isoform/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/a1lian/anaconda3/envs/isoform/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/home/a1lian/rmats_test/od/tmp/JC_SE/rMATS_result_P-V.txt'

In my lib directory(/home/a1lian/anaconda3/envs/isoform/lib), i only have libgsl.so and libgsl.so.27 , MISSING libgsl.so.25
What should i do? and here is my command line:
nohup rmats.py --b1 b1.txt --b2 b2.txt --gtf Homo_sapiens.GRCh37.75.gtf -t paired --readLength 50 --nthread 4 --od /home/a1lian/rmats_test/od --tmp /home/a1lian/rmats_test/tmp > log

**Comment by aojielian** [comment]
Cool, Thanks Eric, that's work for me
