### ISSUE TITLE
outputs for retained intron

### ISSUE THREAD

**Issue by capricy** [Xinglab/rmats-turbo#196]
Hi rMATS support,

I have a significant record from RI.MATS.JC.txt:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/gaoxn/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/gaoxn/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72" lang=EN-US style='tab-interval:.5in;
word-wrap:break-word'>

ID | GeneID | geneSymbol | chr | strand | riExonStart_0base | riExonEnd | upstreamES | upstreamEE | downstreamES | downstreamEE | ID | IJC_SAMPLE_1 | SJC_SAMPLE_1 | IJC_SAMPLE_2 | SJC_SAMPLE_2 | IncFormLen | SkipFormLen | PValue | FDR | IncLevel1 | IncLevel2 | IncLevelDifference
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
151012 | "ENSG00000148290.10" | "SURF1" | chr9 | - | 133352056 | 133356485 | 133352056 | 133354957 | 133356399 | 133356485 | 151012 | 4,6,5 | 1,0,0 | 3,11,5,12,3 | 0,2,2,1,4 | 124 | 62 | 7.90E-05 | 0.01663568 | 0.667,1.0,1.0 | 1.0,0.733,0.556,0.857,0.273 | 0.205

</body>

</html>

The corresponding IGV screenshot at this region (I labeled the riExonStart_0base and riExonEnd coordinates in red):
<img width="960" alt="image" src="https://user-images.githubusercontent.com/18124356/165630433-c8845361-b9cd-4475-805c-00fac7cccfe3.png">

My question is:

Does the result mean that the group1 samples have a SURF1 transcript containing all the intronic regions except for the first one? And the corresponding expression levels are significantly higher in group1 than in group2?

Thanks a lot.

C.

**Comment by EricKutschera** [comment]
This diagram shows what counts as an inclusion read or skipping read for RI events: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#output

From the output you posted:
riExonStart_0base = upstreamES = 133352056
upstreamEE = 133354957
downstreamES = 133356399
riExonEnd = downstreamEE = 133356485

I drew the counting diagram based on where I think those coordinates are in your screenshot. Only `upstreamEE = 133354957` and `downstreamES = 133356399` are used for counting. The other two coordinates are needed to detect the event

<img width="960" alt="rmats_github_issue_ri_edited" src="https://user-images.githubusercontent.com/3375309/165763961-3bab9e36-730d-454d-b1f7-61670cd6e949.png">

There isn't necessarily a SURF1 transcript containing all the intronic regions except for the first one. rMATS is counting according to the diagram with reads that cover the colored parts of the diagram. This post has more details why a particular RI event is detected by rMATS or not: https://github.com/Xinglab/rmats-turbo/issues/17

`IncLevelDifference = 0.205` means `average(IncLevel1) - average(IncLevel2) = 0.205` so group 1 has a higher inclusion level. From `IJC_SAMPLE_1 = 4,6,5` and `IJC_SAMPLE_2 = 3,11,5,12,3` both groups have a decent amount of inclusion counts, but from `SJC_SAMPLE_1 = 1,0,0` and `SJC_SAMPLE_2 = 0,2,2,1,4` group 1 only has 1 skipping count

**Comment by capricy** [comment]
Thank you very much for the explanation. 

So may I say that the significant event here is only related to the intron you labeled as orange line?

Since the upstreamES = 133352056 and upstreamEE = 133354957 for this event, may I say this is a novel exon detected by the rMATS (since it is not annotated in the provided .gtf)?

Thanks.

C.

**Comment by EricKutschera** [comment]
The PValue is calculated using the counts which are all based on the intron with the orange line (and the endpoints of that intron) so in that sense the significance of the event is only related to that intron

Yes, that upstream exon looks to be a novel exon based on the IGV screenshot. If that exon is not in the .gtf file then it is a novel exon detected by rMATS

**Comment by capricy** [comment]
I read the https://github.com/Xinglab/rmats-turbo/issues/17 and it looks like the RI events would only consider the reads mapped to junction sites (split ones or non-split ones), but not the reads mapped to the intronic region. In contrast, the SE event would consider reads mapped to the junction site or the exotic region. Is it correct?

Thanks.

C.

**Comment by EricKutschera** [comment]
I'm not sure if I understand your question correctly, but this diagram shows what rMATS counts as inclusion and skipping reads for each event type: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/docs/rmats_diagram.png

The red and blue lines are junction reads which contribute to both the JC.txt and JCEC.txt files. The orange and green lines are exon reads which only contribute to the JCEC.txt files: https://github.com/Xinglab/rmats-turbo/issues/45#issuecomment-688843471

Here is the code for counting reads for RI events: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L2298
Here is the code for counting reads for SE events: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L1930

In both of those functions the reads that were aligned to a junction (have an 'N' cigar operation: https://samtools.github.io/hts-specs/SAMv1.pdf) are counted separately from the reads which were aligned to a continuous region (an 'M' cigar operation)

For RI events, if the junction ('N' operation) spans the junction shown as the blue line in the diagram then that read counts toward the skipping isoform. If the initial 'M' operation of a junction read crosses the boundary between the intron and the downstream exon (red line in the diagram) then it counts toward the inclusion isoform. If the final 'M' operation of a junction read crosses the boundary between the upstream exon and the intron (other red line in the diagram) then it counts toward the inclusion isoform. If a read with a single 'M' operation crosses one of the boundaries shown by the red lines in the diagram then that read counts toward the inclusion isoform. If a read with a single 'M' operation falls within the orange line in the diagram without touching the boundaries with the red lines then it counts toward the inclusion isoform but only in the JCEC file

For SE events, if the junction ('N' operation) spans the junction shown as the blue line in the diagram then that read counts toward the skipping isoform. If a read has two consecutive 'N' operations that match exactly with the red lines in the diagram then it counts toward the inclusion isoform. If the initial 'M' operation of a junction read starts in the exon (orange line) and the first 'N' operation spans the junction between the middle exon and downstream exon (red line) then it counts toward the inclusion isoform. If the final 'N' operation spans the junction between the upstream exon and middle exon (other red line) and the final 'M' operation of that read ends in the exon (orange line) then it counts toward the inclusion isoform. If a read with a single 'M' operation falls within the orange line in the diagram without touching the boundaries with the red lines then it counts toward the inclusion isoform but only in the JCEC file

**Comment by capricy** [comment]
Thank you very much for the detailed explanations, EricKutschera.
