### ISSUE TITLE
output only with a header

### ISSUE THREAD

**Issue by treblegaia** [Xinglab/rmats-turbo#200]
hi, sorry to trouble you, but i have puzzled by this question for a long time.
the issue is that rmats.py cannot run statistical analysis normally.
if i use --statoff, i got results with NA in column pvalue and so on. if not, i got empty output with only a header.
but it is important to run statistical analysis.

i ran the command:
rmats.py --b1 b1.txt --b2 b2.txt --gtf ./rna-seq-test/gencode.v39.chr_patch_hapl_scaff.annotation.gtf -t paired --readLength 50 --variable-read-length --od ./rmats --tmp ./rmats/tmp 

and log file:
gtf: 29.43813920021057
There are 67928 distinct gene ID in the gtf file
There are 266064 distinct transcript ID in the gtf file
There are 41168 one-transcript genes in the gtf file
There are 1672965 exons in the gtf file
There are 29332 one-exon transcripts in the gtf file
There are 24969 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.916853
Average number of exons per transcript is 6.287829
Average number of exons per transcript excluding one-exon tx is 6.943012
Average number of gene per geneGroup is 8.938947
statistic: 0.031169652938842773

read outcome totals across all BAMs
USED: 149472
NOT_PAIRED: 0
NOT_NH_1: 29482
NOT_EXPECTED_CIGAR: 715
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 9831
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 292
CLIPPED: 0
total: 189792
outcomes by BAM written to: ./rmats/tmp/2022-05-07-17_07_01_877367_read_outcomes_by_bam.txt

novel: 13.354143381118774
The splicing graph and candidate read have been saved into ./rmats/tmp/2022-05-07-17_07_01_877367_*.rmats
save: 0.26987481117248535
loadsg: 0.008358955383300781

==========
Done processing each gene from dictionary to compile AS events
Found 58914 exon skipping events
Found 4371 exon MX events
Found 22081 alt SS events
There are 13488 alt 3 SS events and 8593 alt 5 SS events.
Found 9980 RI events
==========

ase: 4.175574779510498
count: 0.9816064834594727
Processing count files.
paste: ./rmats/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JC_RI/rMATS_result_FDR.txt: No such file or directory
paste: ./rmats/tmp/JCEC_RI/rMATS_result_FDR.txt: No such file or directory
Done processing count files.

can you help me with this? really appreciated

**Comment by EricKutschera** [comment]
For the error:
`paste: ./rmats/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory`

The commands that should have generated that file are: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rmats.py#L428
`./rMATS_C/rMATSexe -i ./rmats/JC.raw.input.SE.txt -t 1 -o ./rmats/tmp/JC_SE/rMATS_result_P-V.txt -c 0.0001`
`python ./rMATS_P/FDR.py ./rmats/tmp/JC_SE/rMATS_result_P-V.txt ./rmats/tmp/JC_SE/rMATS_result_FDR.txt`

When `rmats.py` runs those commands it doesn't print the output (because it can be very verbose). If you try running those commands manually, hopefully there will be an error message that explains the problem

**Comment by treblegaia** [comment]
> 

Thank you for your suggestion. After run thses commands  manually, I found the problem and solved it.
