### ISSUE TITLE
when should I use --fixed-event-set?

### ISSUE THREAD

**Issue by rgarcia27** [Xinglab/rmats-turbo#201]
Hey!
I'm running rmats on my data set, which consists in 4 tissues with ~19 donors each. I want to be able to look to a specific splicing event for all the pairwise comparisons. And I have been following the steps described in the "Run the statistical step separately" because that fits what I want to do. But, reading at the parameters I'm wondering if adding the --fixed-event-set is what I need to do to be able to compare the same event across tissues.

**Comment by rgarcia27** [comment]
Thank you so much, this was really helpful.

**Comment by pintoa1-mskcc** [comment]
Are there any downsides to using --fixed-event-set?

What is the best dataset to use for --fixed-event-set? Can any dataset be used, even a potentially empty set, or would it be best to use a comprehensive set?

Our clinical team is interested in using this option to allow for easy comparisons between datasets, however I am concerned that on the research side of things, if the dataset used for --fixed-event-set is missing some novel or important splicing events, rmats may not detect them?
