### ISSUE TITLE
Behaviour of fixed-event-set argument

### ISSUE THREAD

**Issue by beaferbl** [Xinglab/rmats-turbo#202]
Hi,
I've recently begun to use to the --fixed-event-argument, but I don't get how it works. Let's say I have four groups: A and B from dataset 1 and C and D from dataset 2. The idea is that I want to see if the results of the comparisons between groups in the dataset 1 can be validated in dataset 2, so I run rMATS in this way allowing --novelSS:
--b1 A --b2 B : I get 3,843,355 total events
**--b1 C --b2 D**: I get **1,499,876** total events
The number of common events is low, maybe because of differences between datasets in read length, coverage and library type.
However, I tried the following comparison:
**--b1 C --b2 D** using the **--fixed-event-set** /path/to/fromGTF.[AS].txt files from --b1 A --b2 B output, and I get **2,326,138** events
I don't understand how --fixed-event-set forces rMATS to quantify these events, because, for some reason they weren't found in the comparison without this argument, so how can they now be quantified?
Regards,
Bea

**Comment by EricKutschera** [comment]
Here's the part of the rMATS code that changes with --fixed-event-set: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L3870
With --fixed-event-set, the set of splicing events is read from the existing files. Without that argument rMATS would look at the exons and junctions from the GTF file and also from the input reads and search through those exons and junctions to find events that look like the events in the diagram from the README: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#output

Once rMATS has the event set, then for each event it counts up reads that support each isoform of the event (basically reads that match the colored lines in the digram). The reason --fixed-event-set allows events to be quantified that would not be detected without that argument is that rMATS requires more information to detect an event than it requires to quantify the event. To detect the event it needs to have all the exons and junctions in the event defined (either from the GTF or the reads)

As an example for an SE event, it could happen that all 3 exons are defined in the GTF but there is no transcript in the GTF that supports the inclusion junctions. The first data set could have reads that support all of the junctions and so rMATS is able to detect the event. The second data set might only have reads that support the skipping junction and just 1 of the inclusion junctions. In that case there is no evidence for the other inclusion junction and the event cannot be detected, but if the event is given with --fixed-event-set then it can still be quantified using the 1 inclusion junction that has read support

The reason all the events from the --fixed-event-set are not reported is that the output files are filtered if there is no evidence to support the event from one of the input groups or if there is no evidence for 1 of the isoforms: https://github.com/Xinglab/rmats-turbo/issues/96#issuecomment-847847715

**Comment by beaferbl** [comment]
Thanks for your answer, Eric. As for this sentence, "The second data set might only have reads that support the skipping junction and just 1 of the inclusion junctions", would you say that events quantified only with --fixed-events-set are less confident?

**Comment by EricKutschera** [comment]
If an event was detected with one set of input reads, but required --fixed-event-set for another set of input reads then that second set of reads is missing some info about the event that rMATS needs. It would be reasonable to say that those events are lower confidence than other events

Even for events that are detected without --fixed-event-set, it could be that the events were only detected due to 1 or a few reads that supported some aspect of the event definition. The code in this open pull request shows the individual junction counts in the output which could be considered when deciding if an event is high confidence: https://github.com/Xinglab/rmats-turbo/pull/41

**Comment by beaferbl** [comment]
Makes sense to me, thank you!
