### ISSUE TITLE
No .rmats file in tmp_outpu_post (when run for 3 groups)

### ISSUE THREAD

**Issue by time0225** [Xinglab/rmats-turbo#208]
Hello, sorry to bother you again. I have a problem when I want to run prep and post steps for 3 groups.
Firstly, I run the prep step for each group separately, and when I run the post step and put the 3 groups into s1.txt, the problem happened, rMATS said there is no .rmats file. I have run the "cp_with_prefix.py" script, but I seem to misplace them. Which directory I should put the .rmats files?
Thanks for your any suggestion.

**Comment by EricKutschera** [comment]
The .rmats files should be copied to the directory that you give as the --tmp argument to the post step. Here is an example from the README: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#running-prep-and-post-separately

You mentioned that you are using s1.txt for the post step. The s1.txt file is for fastq files which works for --task prep or --task both. Any fastq files would have been aligned during the prep step and so the post step needs b1.txt. You can see the paths to the bam files in the .rmats files created by the prep steps. The paths to the bam files given in b1.txt for the post step need to match what is in the .rmats files

**Comment by time0225** [comment]
Thanks for your suggestion! I have solved the problem.
