### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by xbx-xbx-1208** [Xinglab/rmats-turbo#209]
IndexError: string index out of range
Exception ignored in: 'rmats.rmatspipeline.parse_gtf'
Traceback (most recent call last):
  File "/home/.../miniconda3/envs/rmats/bin/rmats.py", line 563, in main
    run_pipe(args)
IndexError: string index out of range
gtf: 0.00041794776916503906
There are 1 distinct gene ID in the gtf file
There are 1 distinct transcript ID in the gtf file
There are 1 one-transcript genes in the gtf file
There are 9 exons in the gtf file
There are 0 one-exon transcripts in the gtf file
There are 0 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.000000
Average number of exons per transcript is 9.000000
Average number of exons per transcript excluding one-exon tx is 9.000000
ZeroDivisionError: float division
Exception ignored in: 'rmats.rmatspipeline.statistic'
Traceback (most recent call last):
  File "/home/MCY/miniconda3/envs/rmats/bin/rmats.py", line 563, in main
    run_pipe(args)
ZeroDivisionError: float division
 Hello! I got my rmats from conda, when I run it the rmats.py, I got an error like this, could you please tell me how can I do to fix it?

**Comment by EricKutschera** [comment]
That error can happen if there is a blank line in the file you use as --gtf. You can check which lines (if any) are blank with this command: `grep -n '^$' /path/to/file.gtf`

**Comment by wu116** [comment]
Hi! I got a similar error like xbx's one. But there are no blank in my gtf, and rmats cannot read gene count in gtf file correctly.
```
gtf: 0.8900265693664551
There are 0 distinct gene ID in the gtf file
There are 0 distinct transcript ID in the gtf file
There are 0 one-transcript genes in the gtf file
There are 0 exons in the gtf file
There are 0 one-exon transcripts in the gtf file
There are 0 one-transcript genes with only one exon in the transcript
ZeroDivisionError: float division
Exception ignored in: 'rmats.rmatspipeline.statistic'
Traceback (most recent call last):
  File "/home/shu/miniconda3/envs/rmats4/bin/rmats.py", line 563, in main
    run_pipe(args)
ZeroDivisionError: float division
statistic: 0.0003924369812011719
```
I have two gtf files, one is original while another has been updated from the original one by PASA. I can correctly run rmats with the original one but get this error if I run rmats with the updated one. Could you please give me some advices?

**Comment by wu116** [comment]
Thanks!! I check my file and find attributes losing is the cause.
