### ISSUE TITLE
EXITING because of fatal input ERROR: could not open readFilesIn=\

### ISSUE THREAD

**Issue by danphillips28** [Xinglab/rmats-turbo#212]
Hello Eric,
Thank you for making rMATS, I've had a great time learning how to use it and am looking forward to trying out it's other features soon! 

Running a new analysis, I have run into the following error [for context, I am starting from fastq files - input code is at the end]; 

mapping sample_0,  \ is done with status 102
error in mapping sample_0,  \: 102
error detail:
EXITING because of fatal input ERROR: could not open readFilesIn=\

Jul 03 12:40:55 ...... FATAL ERROR, exiting
Traceback (most recent call last):
  File "/home/ocdm0351/.conda/envs/rMATS/bin/rmats.py", line 536, in <module>
    main()
  File "/home/ocdm0351/.conda/envs/rMATS/bin/rmats.py", line 502, in main
    args = get_args()
  File "/home/ocdm0351/.conda/envs/rMATS/bin/rmats.py", line 197, in get_args
    args.b1, args.b2 = doSTARMapping(args)
  File "/home/ocdm0351/.conda/envs/rMATS/bin/rmats.py", line 81, in doSTARMapping
    raise Exception();
Exception

Before this error, it looks like I had all 59 of my samples finish successfully;

mapping sample_0,  \
/data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/trimmed.reads/abdominal/ABD7352_1_val_1.fq.gz /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/trimmed.reads/abdominal/ABD7352_2_val_2.fq.gz is done with status 0
        STAR --chimSegmentMin 2 --outFilterMismatchNmax 3 --alignEndsType EndToEnd --runThreadN 4 --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate --alignSJDBoverhangMin 6 --alignIntronMax 299999 --genomeDir /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/STAR/GRCh38.Index/ --sjdbGTFfile /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/STAR/gencode.v38.primary_assembly.annotation.gtf --outFileNamePrefix /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/rMATS/tmp.rmats/2022-07-02-14:22:30_907921_bam1_59/ --readFilesIn /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/trimmed.reads/abdominal/ABD7352_1_val_1.fq.gz /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/trimmed.reads/abdominal/ABD7352_2_val_2.fq.gz --readFilesCommand zcat
        STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
Jul 03 12:11:59 ..... started STAR run
Jul 03 12:11:59 ..... loading genome
Jul 03 12:12:16 ..... processing annotations GTF
Jul 03 12:12:31 ..... inserting junctions into the genome indices
Jul 03 12:17:20 ..... started mapping
Jul 03 12:39:22 ..... finished mapping
Jul 03 12:39:23 ..... started sorting BAM
Jul 03 12:40:55 ..... finished successfully

Here is the code used (using a conda installation on HPC, #SBATCH --cpus-per-task=16);
                rmats.py \
          --s1 /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/rMATS/male.abdominal.reads.rMATS.txt \
          --s2 /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/rMATS/male.gluteal.reads.rMATS.txt \
          --gtf /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/STAR/gencode.v38.primary_assembly.annotation.gtf \
          --paired-stats -t paired --readLength 150 --variable-read-length --nthread 8 --od /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/rMATS/Output/ \
          --bi /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/STAR/GRCh38.Index/ \
          --nthread 16 \
          --tmp /data/ocdm-adipose-gene-function/ocdm0351/OxiBank.Project/rMATS/tmp.rmats/ \

I'm not at all sure of what I've done wrong. Can you give any pointers?

Thanks again,
Dan

**Comment by EricKutschera** [comment]
Here's the line for the exception: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rmats.py#L81

Based on `error in mapping sample_0, : 102` it looks like it had the `pair` variable as just a space `' '` when it should be a list of two fastq files

My guess is that one of the files that you used as `--s1` or `--s2` has some extra commas or whitespace at the end of the file. If you are unable to resolve the error, can you post those two files?

**Comment by danphillips28** [comment]
Hi Eric, 
Yes you were right - I found some empty spaces on the last lines of my --s1 and --s2 files. The same code now runs without meeting this error, but unfortunately I am now running up against a timeout issue (limited to <24 hours on my HPC), using;

(59 [paired] samples per group)
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=10000
--nthread 32

If you're able to answer: In 24 hours my tmp folder was populated with bam1_1:59 but only bam2_1:5, how long would you expect for the whole process to run i.e. including the steps after the last bam2 file is processed? I may have to have a rethink of my overall approach. 

Thanks again

**Comment by EricKutschera** [comment]
It sounds like about 60 bam files were created in 24 hours (`bam1_1 -> bam1_59, bam2_1 -> bam2_5`). It might take about 48 hours just to create the bam files if there are also 59 replicates in `--s2`. If you are limited to a single job running for only 24 hours then you can try splitting the work into multiple jobs following: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#running-prep-and-post-separately

Since you are starting with fastq files you can use `--s1` and `--s2` for `--task prep`, but you'll need to switch to `--b1` and `--b2` for `--task post`. The bam file paths in `--b1` and `--b2` need to match with the top line in each .rmats file. You can check the .rmats files in the `--tmp` directory to get the correct paths for the post step

I think each prep step should take less than 1 hour per replicate. The final post step with all the bam files should only take a few hours, but the time can vary a lot if you use `--novelSS`
