### ISSUE TITLE
Problem with evaluate log likelihood (step 4) of an exon

### ISSUE THREAD

**Issue by ycl6** [Xinglab/rmats-turbo#216]
Hi, I have a particular exon (exon ID 61750) in JCEC.raw.input.SE.txt that is causing an error when running rmats.

```
ID      IJC_SAMPLE_1    SJC_SAMPLE_1    IJC_SAMPLE_2    SJC_SAMPLE_2    IncFormLen      SkipFormLen
61750   0,1,11,4,4,6,4,0,0,0,2,1        0,0,1,0,0,0,0,0,0,0,0,0 1,3,5,9,6,16,1,2,2,2,2,1        0,0,0,0,0,0,0,0,0,0,0,3 331     149
```

I tried to run the particular step (`paired_model.R`) that shows this error, and worked out the problem lies in the code snippet shown below. 

```sh
Starting analysis.
Error in { : task 1 failed - "missing value where TRUE/FALSE needed"
Calls: <Anonymous> -> %dopar% -> <Anonymous>
Execution halted
```

```r
      ll.new.u <- loglikelihood(M, I1, S1, I2, S2, l.iI, l.iS, logit.psi1.u[t,], logit.psi2.u[t,], alpha.u[t,], s1.u[t], s2.u[t], s.u[t], mu.u[t], delta.u[t])
      ll.new.c <- loglikelihood(M, I1, S1, I2, S2, l.iI, l.iS, logit.psi1.c[t,], logit.psi2.c[t,], alpha.c[t,], s1.c[t], s2.c[t], s.c[t], mu.c[t], delta.c[t])

      if((abs(ll.new.u - ll.old.u) < tol) & (abs(ll.new.c - ll.old.c) < tol)){
        break
      }
```

It ran for 14 iterations in total. In the 2nd iteration, the loglikelihood of `ll.new.u` is `Inf` and from then onwards almost all the `ll.old.u` and subsequent `ll.new.u` are `Inf`. In the 14th iteration, we ended up with a if/else statement like below. The second condition is met but the first condition `abs(Inf - Inf) < 0.01` is `NA` and throws out the `missing value where TRUE/FALSE needed` error.

```
if((abs(Inf - Inf ) < 0.01) & (abs(-11.3000040969134 - -11.2871817388366) < 0.01))
```

**Comment by EricKutschera** [comment]
That looks to be the same issue as in: https://github.com/Xinglab/PAIRADISE/pull/4

The original developer of PAIRADISE didn't respond to that PR. I merged it just now. If you reinstall PAIRADISE from the updated master branch then I think that error should not happen anymore

**Comment by ycl6** [comment]
Thanks @EricKutschera, the PR indeed fixed my issue.
