### ISSUE TITLE
Bioconda - OSX

### ISSUE THREAD

**Issue by WardDeb** [Xinglab/rmats-turbo#22]
Hi,

Thanks for the work getting rmats into bioconda.
For now rmats in bioconda sits at version 4.1.0, but for OSX bioconda version is still at 3.2.5.
Are there any plans to have the OSX version updated as well ?

Kind regards,

Warddeb

**Comment by EricKutschera** [comment]
The bioconda recipe for rmats was just updated to fix the bug that was causing the OSX build to fail for 4.1.0: https://github.com/bioconda/bioconda-recipes/pull/23147

https://anaconda.org/bioconda/rmats is now showing 4.1.0 for both linux and OSX

**Comment by WardDeb** [comment]
Thanks again for the work and the quick update.

Kind regards

Warddeb
