### ISSUE TITLE
How to  manually calculate IncFormLen and SkipFormLen

### ISSUE THREAD

**Issue by iammrtza** [Xinglab/rmats-turbo#223]
Dear,

I used rMATS and one of the RI events that I have is:
```
IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen	PValue	FDR	IncLevel1	IncLevel2	IncLevelDifference
18,11,7	7,0,1	6,13,4	0,0,0	530	79	1.95558076979e-05	0.003250945067717389	0.277,1.0,0.511	1.0,1.0,1.0	-0.404
```

Based on the original paper and also[ here](https://www.biostars.org/p/256949/) I tried to manually calculate the IncFormLen and SkipFormLen but I get a different value than the reported one with rMATS. 

I used --readLength 80 and   --variable-read-length options as well.

so if the junction length is calculated by j= 2*(reads length - anchor length) then j will be 2*(80-8)=144. And to calculate IncFormLrn I used 2*(j-r+1) formula which will be 2*(144-80+1)=130. But the IncFormLen in the rMATS output shows 530. 

Could you please help with understanding why I get a different number than the reported one by rMATS for the IncFormLen? Thanks.

**Comment by EricKutschera** [comment]
The calculation for each event type is shown in this diagram from the README:
https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#output

For RI events the length calculations are:
```
I_jc = r - 2*a + 1 + min(e, r - 2*a + 1)
S_jc = r - 2*a + 1

I_jcec = I_jc + max(0, e - r + 1)
S_jcec = S_jc
```

Your output shows IncFormLen=530 and SkipFormLen=79. With --readLength 80 and the default --anchorLength 1 the SkipFormLen is: `80 - 2*1 + 1 = 79`

I think you are using the JCEC file and so the IncFormLen is: `80 - 2*1 + 1 + min(e, 80 - 2*1 + 1) + max(0, e - 80 + 1) = 79 + min(e, 79) + max(0, e - 79)`
With `e=451` that's `79 + 79 + 451 - 79 = 530`

You can find the exon length `e` from the coordinate columns in the output file

**Comment by iammrtza** [comment]
Great thanks a lot Eric - that was really helpful.
