### ISSUE TITLE
JC.txt and JCEC.txt, only titles

### ISSUE THREAD

**Issue by jojobmz** [Xinglab/rmats-turbo#227]
Dear teacher,
I used conda install rmats,
My command line is as follows:
【rmats.py --b1 ./b1.txt --b2 ./b2.txt --gtf ./final_gene.gtf --od output_rmats -t paired --nthread 4 --readLength 150 --tmp /path/to/tmp_output --paired-stats】

but when i checked my results , i found that the contents of JC.txt and JCEC.txt files only have titles. 

this is `summary.txt`

【EventType       TotalEventsJC   TotalEventsJCEC SignificantEventsJC     SigEventsJCSample1HigherInclusion       SigEventsJCSample2HigherInclusion       SignificantEventsJCEC   SigEventsJCECSample1HigherInclusion     SigEventsJCECSample2HigherInclusion
SE      0       0       0       0       0       0       0       0
A5SS    0       0       0       0       0       0       0       0
A3SS    0       0       0       0       0       0       0       0
MXE     0       0       0       0       0       0       0       0
RI      0       0       0       0       0       0       0       0】

and `nohup.out` ：

【gtf: 1.6974573135375977
There are 31379 distinct gene ID in the gtf file
There are 61968 distinct transcript ID in the gtf file
There are 19484 one-transcript genes in the gtf file
There are 378532 exons in the gtf file
There are 12968 one-exon transcripts in the gtf file
There are 10837 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.974824
Average number of exons per transcript is 6.108508
Average number of exons per transcript excluding one-exon tx is 7.460490
Average number of gene per geneGroup is 4.997233
statistic: 0.014716625213623047
Fail to open ./Deno_785_dta.bam
Fail to open ./Deno_786_dta.bam
Fail to open ./Deno_788_dta.bam

read outcome totals across all BAMs
USED: 50452793
NOT_PAIRED: 8949649
NOT_NH_1: 8810943
NOT_EXPECTED_CIGAR: 1395306
NOT_EXPECTED_READ_LENGTH: 1030540
NOT_EXPECTED_STRAND: 0】

Please help me solve the problems ,thank you!

**Comment by EricKutschera** [comment]
In a previous edit of this post the output included:
```
error in paired model
Rscript execution error: No such file or directory
```
I'm not sure if you are still having that error, but you could remove `--paired-stats` from your command and just use the default statistical model. Also this post has info about installing the paired model: https://github.com/Xinglab/rmats-turbo/issues/203#issuecomment-1142194772

The current post includes:
```
Fail to open ./Deno_785_dta.bam
Fail to open ./Deno_786_dta.bam
Fail to open ./Deno_788_dta.bam
```
You could try using the absolute path for the bam files `/path/to/Deno_785_dta.bam` instead of the `./` relative paths in your b1.txt and b2.txt

The read outcomes show `USED: 50452793` so a lot of reads are being used, but the line showing the total number of reads is not shown

**Comment by jojobmz** [comment]
> In a previous edit of this post the output included:
> 
> ```
> error in paired model
> Rscript execution error: No such file or directory
> ```
> 
> I'm not sure if you are still having that error, but you could remove `--paired-stats` from your command and just use the default statistical model. Also this post has info about installing the paired model: [#203 (comment)](https://github.com/Xinglab/rmats-turbo/issues/203#issuecomment-1142194772)
> 
> The current post includes:
> 
> ```
> Fail to open ./Deno_785_dta.bam
> Fail to open ./Deno_786_dta.bam
> Fail to open ./Deno_788_dta.bam
> ```
> 
> You could try using the absolute path for the bam files `/path/to/Deno_785_dta.bam` instead of the `./` relative paths in your b1.txt and b2.txt
> 
> The read outcomes show `USED: 50452793` so a lot of reads are being used, but the line showing the total number of reads is not shown



Wow, thank you very much for your help!
I did have this problem before, but I was confused. So, I don't know which command made such an error.
```
error in paired model
Rscript execution error: No such file or directory
```
I modified the file according to your answer, and I found some errors in the file name.
Now, it has run successfully!!
Thank you very much for your help!

finally，It did not report an error, but `fromGTF.novelSpliceSite` only have titles . Is this normal?
These are the files size
```
-rwxrwxrwx. 1 root root  77K Sep  1 21:43 fromGTF.novelJunction.A3SS.txt
-rwxrwxrwx. 1 root root  62K Sep  1 21:43 fromGTF.novelJunction.A5SS.txt
-rwxrwxrwx. 1 root root 152K Sep  1 21:43 fromGTF.novelJunction.MXE.txt
-rwxrwxrwx. 1 root root 8.9K Sep  1 21:43 fromGTF.novelJunction.RI.txt
-rwxrwxrwx. 1 root root 918K Sep  1 21:43 fromGTF.novelJunction.SE.txt
-rwxrwxrwx. 1 root root  102 Sep  1 21:43 fromGTF.novelSpliceSite.A3SS.txt
-rwxrwxrwx. 1 root root  102 Sep  1 21:43 fromGTF.novelSpliceSite.A5SS.txt
-rwxrwxrwx. 1 root root  140 Sep  1 21:43 fromGTF.novelSpliceSite.MXE.txt
-rwxrwxrwx. 1 root root  108 Sep  1 21:43 fromGTF.novelSpliceSite.RI.txt
-rwxrwxrwx. 1 root root  104 Sep  1 21:43 fromGTF.novelSpliceSite.SE.txt
-rwxrwxrwx. 1 root root  374 Sep  1 21:44 summary.txt
drwxrwxrwx. 1 root root 4.0K Sep  1 21:44 tmp
```

**Comment by EricKutschera** [comment]
Yes, that is expected. Here is the description from the README:
> fromGTF.novelSpliceSite.[AS_Event].txt: This file contains only those events which include an unannotated splice site. Only relevant if --novelSS is enabled

**Comment by jojobmz** [comment]
> Yes, that is expected. Here is the description from the README:
> 
> > fromGTF.novelSpliceSite.[AS_Event].txt: This file contains only those events which include an unannotated splice site. Only relevant if --novelSS is enabled

OK! 
Thank you very much for your help!
I will study this software carefully.
