### ISSUE TITLE
trouble with pre-built version for Python 3.6

### ISSUE THREAD

**Issue by showteeth** [Xinglab/rmats-turbo#23]
I got some trouble when using the pre-built version `rmats_turbo_v4_1_0_python_3_6.tar.gz`:
```bash
python rmats.py -h
Traceback (most recent call last):
  File "rmats.py", line 16, in <module>
    from rmatspipeline import run_pipe
ModuleNotFoundError: No module named 'rmatspipeline'
```

The code I got `rmats_turbo_v4_1_0_python_3_6.tar.gz`:
```bash
get https://github.com/Xinglab/rmats-turbo/releases/download/v4.1.0/rmats_turbo_v4_1_0_python_3_6.tar.gz
tar -zxvf rmats_turbo_v4_1_0_python_3_6.tar.gz
```

**Comment by EricKutschera** [comment]
What version of Python are you using? I'm able to use rmats_turbo_v4_1_0_python_3_6.tar.gz with
```
$ python --version
Python 3.6.8
```

But I get the error you reported with Python 2.7.5. The pre-built version may not be compatible with your environment even if you are using the correct Python version. You can try one of these instead:

* building from rmats_turbo_v4_1_0.tar.gz or the latest master commit
* installing from bioconda: conda install -c conda-forge -c bioconda rmats=4.1.0
* Using the docker image: https://hub.docker.com/r/xinglab/rmats

**Comment by showteeth** [comment]
I installed from bioconda, it worked!
Thanks
