### ISSUE TITLE
No rmatspipeline module 

### ISSUE THREAD

**Issue by ceOSU** [Xinglab/rmats-turbo#237]
I installed rmats from conda using the code found here: https://github.com/Xinglab/rmats-turbo/issues/203#issuecomment-1142194772

Then I tried running it with this code: 

python rmats.py --b1 /fs/scratch/PAS1067/cmembree/rmat_test/b1.txt --b2 /fs/scratch/PAS1067/cmembree/rmat_test/b2.txt --gtf /fs/scratch/PAS1067/cmembree/rmat_test/Homo_sapiens.GRCh38.108.gtf --variable-read-length --od /fs/scratch/PAS1067/cmembree/rmat_test/outputdir --tmp /fs/scratch/PAS1067/cmembree/rmat_test/tempdir

Every time I run it I get the following error:

Traceback (most recent call last):
  File "/users/PAS1067/cmembree/Rmat/rmats/rMATS/rmats.py", line 19, in <module>
    from rmatspipeline import run_pipe
ModuleNotFoundError: No module named 'rmatspipeline'

**Comment by EricKutschera** [comment]
If you installed with conda then you should be able to run using the version of python in the conda environment and the rmats.py file from the conda environment. Can you try with full paths to python and rmats.py like in this post: https://github.com/Xinglab/rmats-turbo/issues/67

**Comment by ceOSU** [comment]
Using the full paths worked, thank you!
