### ISSUE TITLE
rMATS-STAT with rmats-turbo

### ISSUE THREAD

**Issue by lmurba** [Xinglab/rmats-turbo#24]
With previous versions of rMATS we used rMATS-STAT to estimate p-values. I would like to run rmats-turbo with --statoff and then perform statistics after the rMATS analysis. Can rMATS-STAT still be used? Is there a different method you would recommend?

**Comment by EricKutschera** [comment]
Yes you can run rmats-turbo with --statoff and then use the JC[EC].raw.input.[AS_Event].txt files with https://github.com/Xinglab/rMATS-STAT. The format of those count files has not changed

rMATS-STAT is basically just some files from rMATS 3.2.5 which is the old Python implementation. In the latest version of rmats-turbo the default statistical model is a faster C implementation of the unpaired model from 3.2.5. Also in the latest version you can use --paired-stats to run https://github.com/Xinglab/PAIRADISE which replaces the paired model from 3.2.5
