### ISSUE TITLE
rMATS install error

### ISSUE THREAD

**Issue by edwardfu11** [Xinglab/rmats-turbo#248]
Hi team,
I tried to build rMATS with --conda in a lunix server, but failed.  I have anaconda3 installed under my home folder. The error is:

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate /export/home/xfu1/rmats_turbo_v4_1_2/conda_envs/rmats
#
# To deactivate an active environment, use
#
#     $ conda deactivate

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Can you please help me out?
Many thanks!
Eddie

**Comment by EricKutschera** [comment]
The main error is:
`CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.`

The `build_rmats` script tries to run the setup that `conda init` writes to `~/.bashrc`. `build_rmats` sources `setup_environment.sh` which sources the .bashrc: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/build_rmats#L86
https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/setup_environment.sh#L21

If you check your .bashrc you should have a section written by `conda init`. If not, you could try running `conda init bash`

**Comment by edwardfu11** [comment]
Hi Eric,

Thank you for your reply.  Indeed, I solved this conda issue by copying the content in .bash_profile to .bashrc.  After build, I had a new error when run the run_rmats scripts as below:

Traceback (most recent call last):
  File "/export/home/xfu1/rmats_turbo_v4_1_2/rmats.py", line 19, in <module>
    from rmatspipeline import run_pipe
ImportError: /fcrbiouatappn01/home/xfu1/rmats_turbo_v4_1_2/rmatspipeline.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK8BamTools12BamAlignment14SetErrorStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_

I then created a conda environment: conda create -n py36 python=3.6 anaconda, and then activate this environment before re-run the run_rmats, but still encountered the same error.  Can you please help me to fix this?
Thanks!
-Eddie

**Comment by EricKutschera** [comment]
That error looks similar to the one from https://github.com/Xinglab/rmats-turbo/issues/21

The issue is that different compiler versions were used in different parts of the build. You should be able to set the compiler paths here (https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/setup_environment.sh#L27) and then build from a clean copy of the source code so that it rebuilds everything

**Comment by edwardfu11** [comment]
Awesome, Eric, it worked!  Thank you so much for your help!
Best
-Eddie
