### ISSUE TITLE
Can't install rMATS4.1.0

### ISSUE THREAD

**Issue by Oliverfeudj** [Xinglab/rmats-turbo#251]
Hello
Whenever I try to install rMATS it gives me this error:

make clean make[2]: Entering directory '/rmats-turbo/rMATS_C' # 
rm -rf util.o myfunc.o cthreadpool.o *.o */*.o */*/*.o *~ */*~ */*/*~ 
rm -rf util.o myfunc.o cthreadpool.o *.o src/*.o lbfgs_scipy/*.o 
rm -rf rMATS.Rcheck make[2]: Leaving directory '/rmats-turbo/rMATS_C' make[1]: 
Leaving directory '/rmats-turbo/rMATS_C' cd rMATS_pipeline; 
python setup.py build_ext; Traceback (most recent call last): File "setup.py", line 4, in <module> from Cython.Build import cythonize ImportError: No module named Cython.Build make: *** [Makefile:5: build] Error 1

I downloaded the tar file and ran ./build_rmats, my version of python is 3.10.0
Thank you for helping me

**Comment by EricKutschera** [comment]
The error `ImportError: No module named Cython.Build` happens because the build requires the Cython package to be installed in your python environment. I was able to build using the latest version of the Cython package from conda (v0.29.32 https://anaconda.org/anaconda/cython/files)

**Comment by Oliverfeudj** [comment]
Thank you very much for your answer but I rather got another error

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages(package$name, repos = repos) :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages(package$name, repos = repos) : 
  unable to install packages
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘foreach’
Execution halted

**Comment by EricKutschera** [comment]
That error is from build_rmats trying to install R dependencies for the paired statistical model. If you don't plan to run rmats with `--paired-stats` then you can disable that part of the install with `./build_rmats --no-paired-model`

If you do want to install the R dependencies then you could try running the install with `sudo` to get permissions on the directory from the error: `/usr/local/lib/R/site-library`. You could also try running `export R_LIBS='/path/to/a/directory_with_permissions'` and creating that directory. That should let it install R libraries to that directory

**Comment by Oliverfeudj** [comment]
Here is what I get whenever I try to run `python rmats.py` 

Traceback (most recent call last):
  File "/opt/rmats_turbo_v4_1_2/rmats.py", line 19, in <module>
    from rmatspipeline import run_pipe
ModuleNotFoundError: No module named 'rmatspipeline'

**Comment by Oliverfeudj** [comment]
`rmatspipeline.cpython-310-x86_64-linux-gnu.so  rmats.py` I have this .so file and the version of python is 2.7.8

How do I make them compatible or which cython should I download please?
Thank you

**Comment by EricKutschera** [comment]
You should be able to run the rmats.py that's in the same directory as that .so file using the same version of python that was used to compile that .so file. It looks like it should be python 3.10 based on `cpython-310`

If you want to use python 2.7.8 then you could start with a clean copy of the code and build with the version of python that you want to use
