### ISSUE TITLE
error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory Traceback (most recent call last):

### ISSUE THREAD

**Issue by archana433** [Xinglab/rmats-turbo#256]
I am getting errors while loading shared libraries:
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_SE/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_SE/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_MXE/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_MXE/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_A3SS/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_A3SS/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_A5SS/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_A5SS/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_RI/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_RI/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_RI/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_RI/rMATS_result_FDR.txt: No such file or directory
Done processing count files.
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_SE/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_SE/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_MXE/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_MXE/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_A3SS/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_A3SS/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_A5SS/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_A5SS/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JC_RI/rMATS_result_P-V.txt'
paste: output_trail/tmp/JC_RI/rMATS_result_FDR.txt: No such file or directory
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "envs/rmat_exon/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_trail/tmp/JCEC_RI/rMATS_result_P-V.txt'
paste: output_trail/tmp/JCEC_RI/rMATS_result_FDR.txt: No such file or directory
Done processing count files

Please help with this issue.
Thank you

**Comment by EricKutschera** [comment]
The main error is:
```
envs/rmat_exon/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
```

rmats requires GSL as a dependency. How did you install rmats? If you installed rmats from conda then you should have libgsl.so.25 in your environment `/path/to/conda_env/lib/libgsl.so.25`. If you compiled rmats yourself then you would have needed that library for the build to succeed. You could try adding the library path with `export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/path/to/directory_with_libgsl`

**Comment by archana433** [comment]
Hi, Thanks for the reply.
I installed rmats with bioconda. and in the lib there is this version  - libgsl.so.27.0.0 present, not the libgsl.so.25. Do I specifically need libgsl.so.25(this version).

**Comment by EricKutschera** [comment]
The error says that it specifically wants libgsl.so.25. I tested installing rmats from conda now with a new environment:
```
conda create --prefix ./test_rmats_env
conda activate ./test_rmats_env
conda install -c conda-forge -c bioconda rmats=4.1.2
```

In `./test_rmats_env/conda-meta` I found `./test_rmats_env/conda-meta/gsl-2.7-he838d99_0.json` with:
`lib/libgsl.so.25`
`"url": "https://conda.anaconda.org/conda-forge/linux-64/gsl-2.7-he838d99_0.tar.bz2"`

Also `./test_rmats_env/conda-meta/rmats-4.1.2-py310h75648e9_4.json` with:
`"gsl >=2.7,<2.8.0a0"`
`"url": "https://conda.anaconda.org/bioconda/linux-64/rmats-4.1.2-py310h75648e9_4.tar.bz2"`

The rmats package seems to be built against a gsl-2.7 package, but that package actually uses libgsl.so.25. Maybe you can install that specific gsl package or check what you have in `conda-meta/`

**Comment by archana433** [comment]
Hi, Thanks for the reply.
It resolved the problem, I have installed libgsl.so.25 and removed libgsl.so.27.
