### ISSUE TITLE
No output to [ASevent].MAT.[JC/JCEC].txt Files 

### ISSUE THREAD

**Issue by gnatowskie** [Xinglab/rmats-turbo#261]
Hello,

I have tried several of the troubleshooting steps from former issues and cannot generate an output in the [ASevent].MAT.[JC/JCEC].txt and the summary.txt file is all zeros. All other files such as "fromGTF" or "raw.input" contain information. 

**Here is the conda environment code:**
conda create --prefix /home/gnatowskie/miniconda3/envs/rmats412
conda activate /home/gnatowskie/miniconda3/envs/rmats412
conda install -c conda-forge -c bioconda rmats=4.1.2

**Here is the rmats command code:**
python /home/gnatowskie/miniconda3/envs/rMATs/rMATS/rmats.py --b1 /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/B6_bam.txt \
--b2 /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/D2_bam.txt \
--gtf /home/projects/MilesLab/teamshare/C57BL6J_genome_release_108/index/primary_assembly/Mus_musculus.GRCm39.108.gtf \
-t paired --readLength 150 --nthread 128 --variable-read-length \
--od /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out \
--tmp /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/tmp/ \
--cstat 0.0001 --novelSS --task both --allow-clipping

**Here are the outputs/errors:**
gtf: 31.1547141075
There are 56980 distinct gene ID in the gtf file
There are 149482 distinct transcript ID in the gtf file
There are 35461 one-transcript genes in the gtf file
There are 868961 exons in the gtf file
There are 28186 one-exon transcripts in the gtf file
There are 22766 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 2.623412
Average number of exons per transcript is 5.813148
Average number of exons per transcript excluding one-exon tx is 6.931597
Average number of gene per geneGroup is 7.528109
statistic: 0.0225431919098

read outcome totals across all BAMs
USED: 2456104212
NOT_PAIRED: 10
NOT_NH_1: 313010356
NOT_EXPECTED_CIGAR: 46014184
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 73055650
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 2536282
CLIPPED: 0
total: 2890720694
outcomes by BAM written to: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/tmp/2023-02-23-08_30_02_212709_read_outcomes_by_bam.txt

novel: 1914.35706306
The splicing graph and candidate read have been saved into /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/tmp/2023-02-23-08_30_02_212709_*.rmats
save: 8067.69521403
loadsg: 4.24416399002

Done processing each gene from dictionary to compile AS events
Found 243454 exon skipping events
Found 98584 exon MX events
Found 247817 alt SS events
There are 148096 alt 3 SS events and 99721 alt 5 SS events.
Found 38332 RI events

ase: 23.3841290474
count: 1649.70513701
Processing count files.
Done processing count files.

**Here are the errors:**
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JC_RI/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/home/gnatowskie/miniconda3/envs/rMATs/rMATS/rMATS_P/FDR.py", line 4, in <module>
    import sys,re,os,numpy
ImportError: No module named numpy
paste: /home/projects/MilesLab/teamshare/B6D2_DeepSeq/H_rMATs/out/tmp/JCEC_RI/rMATS_result_FDR.txt: No such file or directory

Very much in need of help, Thanks!!!

**Comment by EricKutschera** [comment]
Based on the output it looks like the main error is: `ImportError: No module named numpy`. Your conda install command looks fine and I think that should install numpy to the conda environment

My guess is that the conda environment is not activated when you are running the code. It looks like you installed rmats to `/home/gnatowskie/miniconda3/envs/rmats412` but then ran `python /home/gnatowskie/miniconda3/envs/rMATs/rMATS/rmats.py --b1 ...`

If you have the conda environment activated then you can just run `rmats.py --b1 ...` and it should find the version installed to the conda environment

Actually, the numpy dependency isn't used in 4.1.2. The release for 4.1.2 still has the numpy import, but you can just remove numpy from the import line of rMATS_P/FDR.py: https://github.com/Xinglab/rmats-turbo/pull/220/files

**Comment by gnatowskie** [comment]
Haha sometimes it just takes a second pair of eyes to catch something you've been staring at for days! Thank you, I'll let you know if this resolves the issue!

**Comment by gnatowskie** [comment]
I got it to run thank you so much! I also had to include the path to python as well.
