### ISSUE TITLE
Anyway to find out what command was used to generate RMATs data? 

### ISSUE THREAD

**Issue by fidibidi** [Xinglab/rmats-turbo#264]
Hello!
Our lab has inherited some data that was previously run through RMATS v1.1.1, however, the data is missing a log of the commands used to generate the data. 

Is there some way to extract the exact command and parameters from the RMATs output? 

Thank you

**Comment by EricKutschera** [comment]
Maybe it is possible to figure out the command based on the output files, but I don't know much about the older versions of rmats. You could try looking through the old code and documentation

There are download links for old versions of rmats at https://sourceforge.net/projects/rnaseq-mats/files/MATS/

The oldest documentation on sourceforge seems to be for 1.2.0 at https://rnaseq-mats.sourceforge.net/mats1.2.0/

**Comment by fidibidi** [comment]
Thanks for the info, but just realized I made a typo!
It was run on **4.1.1** not 1.1.1 
Any hope!
