### ISSUE TITLE
File truncation and IOError: [Errno 22]

### ISSUE THREAD

**Issue by bbtn1993** [Xinglab/rmats-turbo#269]
Hi, the command worked well on another data set, but for our new data set we are getting output of raw input and fromGTF files but not the MATS files.  Some files are getting truncated and getting the error mentioned in the title:

root@pipeline-313495:/rmats# cd /rmats/
root@pipeline-313495:/rmats# python rmats.py --b1 /root/cloud-data/snf-mgln-ts-us/Science_Computing/Tony/PPP/rmats_Hs_myotubes/c1.txt --b2 /root/cloud-data/snf-mgln-t
s-us/Science_Computing/Tony/PPP/rmats_Hs_myotubes/b1.txt --gtf /root/cloud-data/snf-mgln-ts-us/Science_Computing/Tony/PPP/gencode.v42.annotation.gtf -t paired --rea
dLength 150 --nthread 10 --od /root/cloud-data/snf-mgln-ts-us/Science_Computing/Tony/PPP/rmats_Hs_myotubes/output_020823 --tmp /root/cloud-data/snf-mgln-ts-us/Science
_Computing/Tony/PPP/rmats_Hs_myotubes/tmp_output_020823
gtf: 117.751648903
There are 62696 distinct gene ID in the gtf file
There are 252416 distinct transcript ID in the gtf file
There are 38663 one-transcript genes in the gtf file
There are 1643237 exons in the gtf file
There are 26144 one-exon transcripts in the gtf file
There are 23346 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 4.026030
Average number of exons per transcript is 6.510035
Average number of exons per transcript excluding one-exon tx is 7.146677
Average number of gene per geneGroup is 8.660473
statistic: 0.0358180999756
read outcome totals across all BAMs
USED: 1490170132
NOT_PAIRED: 188829488
NOT_NH_1: 277436822
NOT_EXPECTED_CIGAR: 30028157
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 139035445
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 12558486
CLIPPED: 273000154
total: 2411058684
outcomes by BAM written to: /root/cloud-data/snf-mgln-ts-us/Science_Computing/Tony/PPP/rmats_Hs_myotubes/tmp_output_020823/2023-02-08-15_00_21_132094_read_outcomes_by
_bam.txt
novel: 7451.62764382
The splicing graph and candidate read have been saved into /root/cloud-data/snf-mgln-ts-us/Science_Computing/Tony/PPP/rmats_Hs_myotubes/tmp_output_020823/2023-02-08-15_00_21_132094_*.rmats
save: 86.1791069508
loadsg: 2.98725318909

==========
Done processing each gene from dictionary to compile AS events
Found 131619 exon skipping events
Found 21444 exon MX events
Found 27317 alt SS events
There are 16436 alt 3 SS events and 10881 alt 5 SS events.
Found 10100 RI events
==========

ase: 9.5257101059
count: 60.0831158161
Processing count files.
Traceback (most recent call last):
  File "rmats.py", line 595, in <module>
    main()
  File "rmats.py", line 583, in main
    args.paired_stats, python_executable, root_dir)
  File "rmats.py", line 371, in process_counts
    filter_countfile(istat)
  File "rmats.py", line 344, in filter_countfile
    fp.truncate()
IOError: [Errno 22] Invalid argument
root@pipeline-313495:/rmats#

**Comment by EricKutschera** [comment]
This is the line for that error message: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rmats.py#L344

The code wants to truncate the file. It finds the rows that it wants to keeps in the file (files like JC.raw.input.SE.txt), overwrites the beginning lines of the file with those rows, and finally truncates the file to remove any extra lines. I don't see why there would be an error at the truncate call since by that point the code had already done both seek and write operations on the file

I'm not sure why you would get an IOError there. Maybe you could try running in a different directory or on a different machine?

**Comment by bbtn1993** [comment]
Thanks for your help.  We will give that a try.  I was wondering if our gtf file could also be a problem since there seem to be a lot of exons and junctions not mapped to the annotation.

**Comment by EricKutschera** [comment]
The gtf doesn't seem like a problem based on the read outcomes. The `NOT_MATCHED_TO_ANNOTATION` outcomes are not too large compared to the total number of reads:
```
EXON_NOT_MATCHED_TO_ANNOTATION: 5.7%
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0.5%
```

**Comment by bbtn1993** [comment]
Great, thanks again!
