### ISSUE TITLE
rMATS for data with variable read length

### ISSUE THREAD

**Issue by shibiaowan** [Xinglab/rmats-turbo#27]
Hi,

We have some paired-end RNA-seq samples. The read length of them before trimming is 150.  We trimmed pair-end reads by trim_galore. The reads in the raw fastq files do not have the same length. 

We then used STAR to align the trimmed fastqs using --alignEndsType Local (default option with soft-clipping allowed).

My questions are:
(1) Can I run rMATS v4.1.0? With --variable-read-length –readLength 150 (length before trimming)?
(2) If not, should we trim the reads (R1, R2) to the same length (how long) and align them with STAR --alignEndsType EndToEnd?

Thanks and hope for your reply.

**Comment by EricKutschera** [comment]
Yes, you should be able to run rMATS v4.1.0 with --variable-read-length --readLength 150

--variable-read-length tells rMATS to process reads of any length so your reads do not need to have the same length. --readLength is used to determine IncFormLen and SkipFormLen needed for calculating PSI values. Using the length before trimming makes sense

**Comment by shibiaowan** [comment]
Thank you for your reply. That helps a lot.

**Comment by wangjiawen2013** [comment]
STAR aligner performs soft clipping by default which will generate variable read lengths. I used the resulting BAM files as input to rMATS.  Does rMATS ignores those alignments with soft or hard clipping by default? Do I need to use --allow-clipping ?

**Comment by EricKutschera** [comment]
rMATS ignores alignments with soft or hard clipping unless --allow-clipping is used. rMATS ignores alignments that do not match --readLength unless --variable-read-length is used. If you are using rMATS that was built from a recent commit then you can see how many alignments were ignored for read length or clipping in the file `tmp/{datetime}_read_outcomes_by_bam.txt`
