### ISSUE TITLE
 rMATS error /bin/sh: STAR: command not found

### ISSUE THREAD

**Issue by rezarahman12** [Xinglab/rmats-turbo#274]
Dear rMATS team
thanks for this excellent program for splicing analysis. 
I'm trying to run rMATS on fastq file using the below command-
module load rmats-turbo/4.1.2
run_rmats --s1 ko.txt --s2 con.txt \
 --gtf ./Mus_musculus.GRCm39.109.gtf \
 --bi .scratch/project_mnt_S0077/star \ 
 --od rMATS_results \
--tmp rMATS_results \
-t paired \
--readLength 101

**However, I'm getting the below error-**
Traceback (most recent call last):
  File "/sw/local/rocky8.6/epyc3/qcif/software/miniconda3/envs/rmats-turbo_4.1.2/opt/rmats-turbo/rmats.py", line 596, in <module>
    main()
  File "/sw/local/rocky8.6/epyc3/qcif/software/miniconda3/envs/rmats-turbo_4.1.2/opt/rmats-turbo/rmats.py", line 559, in main
    args = get_args()
  File "/sw/local/rocky8.6/epyc3/qcif/software/miniconda3/envs/rmats-turbo_4.1.2/opt/rmats-turbo/rmats.py", line 204, in get_args
    args.b1, args.b2 = doSTARMapping(args)
  File "/sw/local/rocky8.6/epyc3/qcif/software/miniconda3/envs/rmats-turbo_4.1.2/opt/rmats-turbo/rmats.py", line 82, in doSTARMapping
    raise Exception()
Exception

**below is the output file contents-**
mapping the first sample
mapping sample_0, mettl3ko-rep1_SRR5760146_1.fastq mettl3ko-rep1_SRR5760146_2.fastq is done with status 127
error in mapping sample_0, mettl3ko-rep1_SRR5760146_1.fastq mettl3ko-rep1_SRR5760146_2.fastq: 127
error detail: /bin/sh: **STAR: command not found**

I'll be grateful if you kindly let me know the solution to this problem.

Kind regards
Reza

**Comment by EricKutschera** [comment]
If you run with --s1 and --s2 then rMATS will try to align your fastq files with STAR. The error is showing that STAR is not installed. You could try to install STAR yourself:
github: https://github.com/alexdobin/STAR
bioconda: https://anaconda.org/bioconda/star

You could also try aligning your reads before running rMATS and then using --b1 and --b2 instead of --s1 and --s2

**Comment by rezarahman12** [comment]
Thanks a lot @EricKutschera. I really appreciate your time and help. Another questions to follow up this-

When I'm running after loading rmats-turbo and star both module, I do not receive error saying STAR:command not found.

I'm getting another error-
Traceback (most recent call last):
  File "/sw/local/rocky8.6/epyc3/qcif/software/miniconda3/envs/rmats-turbo_4.1.2/opt/rmats-turbo/rmats.py", line 19, in <module>
    from rmatspipeline import run_pipe
ImportError: /sw/auto/rocky8.6/epyc3/software/GCCcore/10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /sw/local/rocky8.6/epyc3/qcif/software/miniconda3/envs/rmats-turbo_4.1.2/opt/rmats-turbo/rmatspipeline.cpython-36m-x86_64-linux-gnu.so)

My rMATS command was given below-
module load rmats-turbo/4.1.2
module load star

run_rmats --s1 /scratch/project_mnt/S0077/splicing_publicdata/P7_splicing/mettl3ko.txt --s2 /scratch/project_mnt/S0077/splicing_publicdata/P7_splicing/mettlcon.txt \
 --gtf /scratch/project_mnt/S0077/splicing_publicdata/annotation_files/Mus_musculus.GRCm39.109.gtf \
 --bi /scratch/project_mnt/S0077/splicing_publicdata/P7_splicing/star \
 --od /scratch/project_mnt/S0077/splicing_publicdata/P7_splicing/rMATS_results_p7_GSE100528 \
--tmp /scratch/project_mnt/S0077/splicing_publicdata/P7_splicing/rMATS_results_p7\
-t paired \
--readLength 101

Could you please suggest whether it is rMATS-turbo installation issue?

Kind regards
Reza

**Comment by rezarahman12** [comment]
problem solved. thanks
