### ISSUE TITLE
can rmats analysis  alternative splicing of a single sample?

### ISSUE THREAD

**Issue by zhengyzh** [Xinglab/rmats-turbo#275]
Hi:
can rmats analysis  alternative splicing of a single sample?That is not for differential alternative splicing events from RNA-Seq data.
If possible, how to set parameters for the alternative splicing of a single sample?

Looking forward to your reply，thank you!

**Comment by EricKutschera** [comment]
You can run with a single input sample by using `--statoff` and just `--b1`. The statistical test will be skipped, but you can still get the read counts and inclusion levels for that single sample

**Comment by zhengyzh** [comment]
The problem has been solved, thank you very much！

**Comment by zhengyzh** [comment]
> You can run with a single input sample by using `--statoff` and just `--b1`. The statistical test will be skipped, but you can still get the read counts and inclusion levels for that single sample

The problem has been solved, thank you very much！
