### ISSUE TITLE
ValueError running rMATS with BAM

### ISSUE THREAD

**Issue by rna-guy** [Xinglab/rmats-turbo#278]
I am running rMATS after installing with conda 
conda create --prefix ./rmats_env
conda activate ./rmats_env
conda install -c conda-forge -c bioconda rmats=4.1.2

Python version 3.10.10

this is the code I used from the conda environment 
python rmats.py --b1 hc.txt --b2 dm.txt \
  --gtf ~/rna/nw/gencode.v42.primary_assembly.annotation.gtf \
  -t paired --readLength 101 --variable-read-length --allow-clipping --nthread 8 --novelSS \
  --od ~/rna/rmats_results --tmp ~/rna/rmats_results/tmp --libType fr-firststrand

the text files for bams are comma separated. When I run this code, it processes for a while, and it looks like the BAMs are being processed at least initially, then I get the error at the end. I'd appreciate your help with this

gtf: 21.72277808189392
There are 62750 distinct gene ID in the gtf file
There are 252475 distinct transcript ID in the gtf file
There are 38712 one-transcript genes in the gtf file
There are 1643438 exons in the gtf file
There are 26180 one-exon transcripts in the gtf file
There are 23382 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 4.023506
Average number of exons per transcript is 6.509310
Average number of exons per transcript excluding one-exon tx is 7.146680
Average number of gene per geneGroup is 8.662043
statistic: 0.044054508209228516

read outcome totals across all BAMs
USED: 531573454
NOT_PAIRED: 0
NOT_NH_1: 168564874
NOT_EXPECTED_CIGAR: 3547409
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 7332316
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 929129
CLIPPED: 0
total: 711947182
outcomes by BAM written to: /home/rna/rmats_results/tmp/2023-03-29-13_05_04_428329_read_outcomes_by_bam.txt

novel: 3465.4991483688354
The splicing graph and candidate read have been saved into /home/rna/rmats_results/tmp/2023-03-29-13_05_04_428329_*.rmats
save: 286.2633237838745
Traceback (most recent call last):
  File "/home/rna/rmats-turbo/rmats_env/rMATS/rmats.py", line 595, in <module>
    main()
  File "/home/rna/rmats-turbo/rmats_env/rMATS/rmats.py", line 563, in main
    run_pipe(args)
  File "rmatspipeline/rmatspipeline.pyx", line 3860, in rmats.rmatspipeline.run_pipe
  File "rmatspipeline/rmatspipeline.pyx", line 3723, in rmats.rmatspipeline.split_sg_files_by_bam
  File "rmatspipeline/rmatspipeline.pyx", line 3731, in rmats.rmatspipeline.split_sg_files_by_bam
ValueError: invalid literal for int() with base 10: '~/rna/bams/sorted503.bam'

**Comment by rna-guy** [comment]
Thank you for the quick response Eric. the txt files seemed fine, but I re-did them anyway, changed input to ./file.txt, and re-arranged the input code. not sure which one of these did it but now it works

May I ask a few more questions about the software in general that I did not see in the documentation:
1. Is novelSS still experimental? how does it work?
2.  the events in fromGTF.novelJunction.[AS_Event].txt and fromGTF.novelSpliceSite.[AS_Event].txt are included in fromGTF.[AS_Event].txt. but there are additional events in fromGTF.txt, what are those additional events? and how are they different from the others?
3. there are more events in fromGTF.[AS_Event].txt than [AS_Event].MATS.JCEC.txt. why were some events not statistically tested?
4. can technical replicates be incorporated in addition to biological replicates?
Thank you

**Comment by EricKutschera** [comment]
1. novelSS is experimental in the sense that we haven't done a rigorous analysis to validate that the code is correct. However I don't know of any issues or bugs with the novelSS code. This post describes how --novelSS works: https://github.com/Xinglab/rmats-turbo/issues/156#issuecomment-959826431

2. The events that are only in the fromGTF.[AS_Event].txt file (not the novel files) can be detected just from the transcripts defined in the --gtf. All the exons and junctions used in that event are defined in the --gtf

3. Here's the filter: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rmats.py#L335
It removes events before running the statistical test if the event does not have at least 1 read supporting each sample group and at least 1 read supporting each isoform (inclusion and skipping). If run with --statoff then the filter will be skipped and all events in the fromGTF file will be in the MATS output file

4. Yes, you can use technical replicates. The statistical model will take into account the variability among replicates when calculating the p-value. The rmats paper (http://dx.doi.org/10.1073/pnas.1419161111) mentions:
> variability among replicates due to biological or technical reasons

**Comment by rna-guy** [comment]
This is very helpful. One last question, do I need to tell rMATS which replicates are biological vs technical? or just list all of them in the input txt files?

**Comment by EricKutschera** [comment]
rMATS does not distinguish between technical and biological replicates. You can list them all in the input txt files. rMATS will then use the variability among all replicates in each sample group as part of the statistical model

**Comment by rna-guy** [comment]
Much appreciated Eric
