### ISSUE TITLE
libgomp: Out of memory allocating 962072674304 bytes

### ISSUE THREAD

**Issue by WangWaud** [Xinglab/rmats-turbo#279]
Hello, I'm new to alternative splicing, and it's the first time I use rMATs.

## code
I used conda to install rMATs and used the code below
``
rmats.py --b1 b1.txt --b2 b2.txt --gtf $gtf_dir/Arabidopsis_thaliana.TAIR10.56.gtf --od $data_dir/AS_result --tmp $data_dir/AS_tmp_result -t single --readLength 75 --cstat 0.0001 --libType fr-unstranded --nthread -6
``

b1.txt is
``
$data_dir/SRR847501.sort.bam,$data_dir/SRR847502.sort.bam
``

b2.txt is
``
$data_dir/SRR847503.sort.bam,$data_dir/SRR847504.sort.bam,$data_dir/SRR847505.sort.bam,$data_dir/SRR847506.sort.bam
``

## error
It ran for a while and then there came an error following
``
gtf: 2.1864871978759766
There are 32833 distinct gene ID in the gtf file
There are 54013 distinct transcript ID in the gtf file
There are 21918 one-transcript genes in the gtf file
There are 313952 exons in the gtf file
There are 10786 one-exon transcripts in the gtf file
There are 9638 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.645083
Average number of exons per transcript is 5.812527
Average number of exons per transcript excluding one-exon tx is 7.013348
Average number of gene per geneGroup is 3.381945
statistic: 0.007827520370483398
libgomp: Out of memory allocating 962072674304 bytes
``

I used htop to check the tasks and I found nobody is using it except me. (125G memory and more than 3T disk is left).

I really don't know how to fix it. I would be very appreciate if you can help me solve this. Thanks!!

**Comment by EricKutschera** [comment]
I think the error may be: `--nthread -6` where the 6 is negative. That may lead to the threading library allocating a very large number of threads by mistake

**Comment by WangWaud** [comment]
OMG!! I'm sorry, I reviewed the code before but didn't find this SMALL error! Thanks!
