### ISSUE TITLE
error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by qj009** [Xinglab/rmats-turbo#281]
Hello, I am running rmats but I got the error that it can not find libgsl.so.25. I install the rmats through conda:

conda create -n rmat -c bioconda rmats

I check the lib folder under my .conda/envs/rmat, it only have libsgsl.so.27, no libgsl.so.25. 
I tried ./build_rmats but it did not work. And since I worked on hpcc it is better to use conda to build a environment and install rmats there. 

Thank you so much for all your help.

**Comment by EricKutschera** [comment]
That conda environment somehow got the wrong version of libgsl. Here's a related post about the libgsl error: https://github.com/Xinglab/rmats-turbo/issues/256#issuecomment-1410497821

I think if you create a new conda environment and install with this command `conda install -c conda-forge -c bioconda rmats=4.1.2` then it should get the libgsl that it needs

The conda-forge package for gsl-2.7 has libgsl.so.25 which seems to be causing the confusion with 2.7 versus 2.5

**Comment by qj009** [comment]
Thank you Eric for quick response. I tried it but it still install the libgsl.so.27, not 25. And I tried to run rmats again and it still give out the same error.

**Comment by EricKutschera** [comment]
I was able to create a new conda env and install with that command and run rmats without an error. Maybe your conda config has something that causes it not to want the conda-forge gsl package with libgsl.so.25

Does `conda config --show-sources` show anything about channel preferences?

**Comment by qj009** [comment]
Hello, below is the results after I run : `conda config --show-sources`

auto_activate_base: False
envs_dirs:
  - ~/bigdata/.conda/envs
pkgs_dirs:
  - ~/bigdata/.conda/pkgs
channel_priority: disabled
channels:
  - auto
  - conda-forge
  - bioconda
  - r
  - defaults

The hpcc administrator helps me to create a file to specify the libgsl version in it. I successfully run through the rmats this week. However, still don't know why conda install the wrong version of libgsl.

**Comment by EricKutschera** [comment]
I think conda picked a gsl package from the default channel (https://anaconda.org/anaconda/gsl/files) instead of the one that rmats wants from the conda-forge channel (https://anaconda.org/conda-forge/gsl/files) because you have `channel_priority: disabled` in your config. With that config value I think conda will ignore that we told it to prefer conda-forge for this comand (with `-c conda-forge`) and just pick the package from the default channel

**Comment by qj009** [comment]
I see. To solve this, should I try to remove `disabled` fro `channel_priority`?

**Comment by EricKutschera** [comment]
Yes, I think that should work. I tested adding `channel_priority: disabled` to my config and when I installed rmats to a new environment it used gsl-2.7.1 from the default channel. That caused the error about libgsl.so.25. Then I removed the channel_priority line from my config, installed rmats to a new environment, and there was no error

**Comment by qj009** [comment]
Hello Eric, I removed `channel_priority: disabled `line in my conda config file `.condarc` and reinstall the rmats. The libgsl.so.25 is installed. Thank you for your help!
