### ISSUE TITLE
Running rMATS for more than 2 samples for pairwise differential splicing analysis

### ISSUE THREAD

**Issue by orbitalse** [Xinglab/rmats-turbo#282]
Hello,

I am working with a dataset that has 24 samples. The rMATS README provides information on how to run rMATS between any 2 samples, but if I do this pairwise for all of my samples, I would need to parse all of the resulting output files to find events in common. In addition, there are some inconsistencies in the number of AS events detected per sample if rMATS is run in this manner.

I am looking for a way in which I can use rMATS to detect AS events across ALL these samples first, and then do pairwise differential analysis afterwards. It is similar in a sense to the questions asked in issue #96 and issue #222 , but the solutions to these two questions differ and I am not sure which to use. I have tried both, but receive some error messages. 

Would you please be able to provide some more detailed guidance on how to run rMATS to detect AS events in more than 2 samples? 

Thank you very much for your help and time, it is much appreciated!

**Comment by EricKutschera** [comment]
I think you want to follow the steps in https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#running-the-statistical-model-separately which is the method from this post that you mentioned: https://github.com/Xinglab/rmats-turbo/issues/96

By running all of the data in a single `--task post` step with `--statoff` you can see all of the AS events for your dataset. Then you can use different subsets of that output to run the statistical model with `--task stat`

With that method you will get different output files for the different statistical comparisons, but the ID column can be used to match events in the different output files

**Comment by orbitalse** [comment]
Thanks for your reply.

I have tried the following:

1. I first run the "prep" step on each individual sample, using a command like the one below:

`singularity exec $DOCKER/rmats_turbo_v4_1_2.img python /rmats/rmats.py --b1 b1.txt --gtf gencode.v29.annotation.gtf -t single --readLength 100 --nthread 16 --od rmats_out --tmp rmats_tmp --task prep --statoff`

Let's say I have 3 samples, for the simple case. I rerun the above command for b1.txt, b2.txt, and b3.txt. The contents for each of the txt files is the full path to the bam files for each of the 3 respective samples.

The result is 2 files for each sample in the `rmats_tmp` directory: one with the extension `.rmats` and the other with the extension `read_outcomes_by_bam.txt`.

2. I run the "post" step on the combined samples, using a command like the following:

`singularity exec $DOCKER/rmats_turbo_v4_1_2.img python /rmats/rmats.py --b1 b4.txt --gtf gencode.v29.annotation.gtf -t single --readLength 100 --nthread 16 --od rmats_out --tmp rmats_tmp --task post --statoff`

The contents of b4.txt are the contexts of b1.txt, b2.txt, and b3.txt combined; in other words, the full path to the bam files for each of the 3 samples, one on each newline.

However, I get the following error:

gtf: 20.5235280991
There are 59526 distinct gene ID in the gtf file
There are 207507 distinct transcript ID in the gtf file
There are 36989 one-transcript genes in the gtf file
There are 1263774 exons in the gtf file
There are 25832 one-exon transcripts in the gtf file
There are 23220 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.485989
Average number of exons per transcript is 6.090272
Average number of exons per transcript excluding one-exon tx is 6.814047
Average number of gene per geneGroup is 7.964839
statistic: 0.028843164444
< full path to sample 1 bam >
< full path to sample 2 bam >
< full path to sample 3 bam > not found in .rmats filles

(In the above error message, I have only modified it to redact the actual path in <> , which contains personal information.)

Do you know what is causing this error? I am not sure if I have created the prep and post commands correctly.

Thanks!

**Comment by orbitalse** [comment]
That worked!

Thank you for your help with this matter.
