### ISSUE TITLE
Which BAM file should I use for rMATS after STAR alignment: Aligned.toTranscriptome.out.bam or Aligned.sortedByCoord.out.bam?

### ISSUE THREAD

**Issue by JiaGuangshuai** [Xinglab/rmats-turbo#283]
Hello everyone,

I recently ran an RNA-seq analysis using the STAR aligner and ended up with two BAM files: Aligned.toTranscriptome.out.bam and Aligned.sortedByCoord.out.bam. I would like to perform differential splicing analysis using rMATS, but I am unsure which of these two files I should use as input.

Can someone please help me understand the difference between these two files and advise me on which one would be more suitable for rMATS analysis? Any suggestions or recommendations would be greatly appreciated.

Thank you in advance for your help!

**Comment by EricKutschera** [comment]
From the STAR manual: https://github.com/alexdobin/STAR

> With --quantMode TranscriptomeSAM option STAR will output alignments translated into transcript coordinates in the Aligned.toTranscriptome.out.bam file (in addition to alignments in genomic coordinates in Aligned.*.sam/bam files). These transcriptomic alignments can be used with various transcript quantification software that require reads to be mapped to transcriptome

rMATS expects the alignments in genomic coordinates like Aligned.sortedByCoord.out.bam. Then rMATS will decide which reads to count toward which splicing events. If you try to use the Aligned.toTranscriptome.out.bam file with rMATS then I expect rMATS will not recognize the coordinate system and ignore most of the alignments or give an error

**Comment by JiaGuangshuai** [comment]
Hi Eric,

I now understand. Thank you for explaining it to me!
