### ISSUE TITLE
Lots of 'NA' in Inclusion Level column

### ISSUE THREAD

**Issue by bbtn1993** [Xinglab/rmats-turbo#290]
In my output for 2 different groups that I am comparing, I have a lot of 'NA' values that are primarily in the same column.  I have 5 different columns of sample data for each group.  I am wondering if that means the same sample frequently had 0 reads or if the 5 different values are listed randomly and not in the order of the sample to which they belong.  I used the text to column feature in Excel to get the values into separate columns.

**Comment by EricKutschera** [comment]
The output columns that have comma separated values (IJC_SAMPLE_1, SJC_SAMPLE_1, ...) have the values in the same order as the input --b1 and --b2 files: https://github.com/Xinglab/rmats-turbo/issues/263

If you are seeing NA in a particular position of IncLevel1, then you can check the corresponding values in IJC_SAMPLE_1 and SJC_SAMPLE_1 to see if the counts for that position are zero

**Comment by bbtn1993** [comment]
Yes, the 0's in IJC and SJC are aligned with the "NA" in my concerning samples.  I have 2 groups of samples, and samples in each group are replicates from the same cell line (Normal & Diseased lines), so it is very strange that just 1 sample in each group has far more "NA" than all the other samples in the same group.  I am wondering if you have ever seen this.  I did QC the RNAseq data, and it looked fine (samples clustered into their respective groups; very similar # total reads for all samples)
My command was the following:

/rmats# python /rmats/rmats.py --b1 /root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/XX1/rmats_Hs_myotubes/c1.txt --b2 /root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/XX1/rmats_Hs_myotubes/b1.txt --gtf /root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/XX1/gencode.v42.annotation.gtf -t paired --readLength 150 --nthread 16 --od /home/LIUDO02/GROUP-TS/ScienceComputing/Brenda/rmats/XX1/rmats_Hs_myotubes/outputc1b103292023 --tmp /home/LIUDO02/GROUP-TS/ScienceComputing/Brenda/rmats/XX1/rmats_Hs_myotubes/tmp_outputc1b103292023

[A3SS.MATS.JCEC.txt](https://github.com/Xinglab/rmats-turbo/files/11383882/A3SS.MATS.JCEC.txt)
Thanks so much for your help!  Please see my attached file at above location,
Brenda

**Comment by bbtn1993** [comment]
Ah yes, thank you, that is the case.

**Comment by bbtn1993** [comment]
I am starting to analyze my data now, and I can't find the information to answer my question, so hopefully you can direct me to a prior post if you already answered this...  I did 2 runs in rMATS for 2 comparisons I want to make with groups B1, B2, and C1 (each have 4 or 5 samples), B2 vs. B1 and C1 vs. B1.  As an example, ANK2 has several significant splicing events for each comparison (see attached file with data from MATS files/JCEC of the 2 different runs).  How do I choose which data to compare if I want to plot the inclusion level values on a graph as a visual for my results? Do I need to make sure all the exon position information matches up?  My group wants to see data that represents the splicing results for a set of about 40 genes.  I am assuming p-values and FDR of 0 are very small p-values close to 0.  Inclusion level differences can be either positive or negative by the same amount, depending on the row.  Thanks in advance for your help!
[example_rMATS_data.xlsx](https://github.com/Xinglab/rmats-turbo/files/11445912/example_rMATS_data.xlsx)

**Comment by EricKutschera** [comment]
Instead of doing 1 run for each pair of sample groups, you could use all the samples in a single --task post step and then run a separate --task stat step for each pair: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#running-the-statistical-model-separately
Here's a related post: https://github.com/Xinglab/rmats-turbo/issues/282

With --task stat, the event IDs will be the same for all sample groups. If you want to match up events from different --task post steps then only some of the coordinates need to match. See this post: https://github.com/Xinglab/rmats-turbo/issues/284

Yes, the p-values and FDR that are 0 should be small numbers close to 0, but are set to 0 due to floating point limitations

The sign of IncLevelDifference indicates which sample group has higher inclusion: `IncLevelDifference = average(IncLevel1) - average(IncLevel2)`

**Comment by bbtn1993** [comment]
Thanks so much Erik!  I really appreciate your being so responsive and sending such helpful information and examples.  rMATS is a great tool!
