### ISSUE TITLE
about read length

### ISSUE THREAD

**Issue by rezarahman12** [Xinglab/rmats-turbo#299]
Hi Eric,

I'm not quite sure about the average read length of our RNA-Sequencing data. The company we sent for RNA sequencing has written the below text " After cluster generation, the library preparations were sequenced on an Illumina platform and 125 bp/150 bp paired-end reads were generated.". So, I checked the bam files to find the read length using the below flags in samtools-
samtools view -f 0x40 -F 0x4 Ctr24_1_sorted.bam | awk '{ sum += length($10) } END { print sum / NR }'

I found average read length of 148.5 for all the bam files.  So, do I give the --readLength 150 or 148.5? Or can I give 148.5 and add another flag --variable-read-length?

I appreciate your time and opinion.

Kind regards
Reza

**Comment by EricKutschera** [comment]
rMATS needs an integer for --readLength so 148.5 would not work. You can use 150 and also --variable-read-length. Your samtools command is filtering for the first read in the pair. Maybe "125 bp/150 bp paired-end reads" means that the first read in the pair is 150bp and the second is 125?

Here is a related post about --readLength: https://github.com/Xinglab/rmats-turbo/issues/83
