### ISSUE TITLE
most output files with only a header

### ISSUE THREAD

**Issue by rstatistics** [Xinglab/rmats-turbo#3]
The output of rmats=4.1.0 with only header, pls check, thank you.
rmats.py --b1 b1.txt --b2 b2.txt --gtf ./gene.gtf --od ../rmats --tmp ./tmp
wc -l ../rmats/*
```
    1 A3SS.MATS.JCEC.txt
    1 A3SS.MATS.JC.txt
    1 A5SS.MATS.JCEC.txt
    1 A5SS.MATS.JC.txt
   29 fromGTF.A3SS.txt
   14 fromGTF.A5SS.txt
   14 fromGTF.MXE.txt
   ...
  ```

**Comment by EricKutschera** [comment]
It's difficult for me to guess what is happening without seeing the stdout/stderr and the input BAMs and GTF. Perhaps there was an error reading the BAM files, or the reads just didn't indicate any alternative splicing

**Comment by ywang1993** [comment]
It seems that you didn't provide --readLength parameter when running both rmats, and the default value is 0 for this parameter. Different from v4.0.2, v4.1.0 version will filter out all reads that not match the input read length (in this case 0). And this is the reason you only have the header in those output files. You can easily fix it by providing the --readLength parameter, or add --variable-read-length flag in v4.1.0 to allow variable read length from bam files. Thanks!

**Comment by rstatistics** [comment]
@ywang1993 It works with "--readLength 100 --variable-read-length " parameter, thank you for helping me out!
