### ISSUE TITLE
Multiple options for stranded

### ISSUE THREAD

**Issue by abhilashdasari** [Xinglab/rmats-turbo#303]
For example, if the Control samples are fr-firststrand, whereas diseased samples are fr-secondstrand.

Or two studies are combined and analysed, In which one of the dataset is  fr-firststrand and the second dataset is  fr-secondstrand.

To process such complicated datasets, please provide options like sample_data file to process them.

please take Input of the sample_data table
Bam_file_control_1.bam, control,  fr-firststrand
Bam_file_control_2.bam, control,  fr-firststrand
Bam_file_diseased_1.bam, diseased, fr-secondstrand
Bam_file_diseased_2.bam, diseased, fr-secondstrand

Else,
For the convenience of the user provide an AUTO strandedness option, In which the program samples 400-500 reads randomly and estimates the strandedness for each sample, and processes the results accordingly.

**Comment by EricKutschera** [comment]
In the current implementation, if individual samples have different strandedness then they need to be processed in separate `--task prep` steps. Each prep step can use the value of `--libType` needed for the sample(s) in that step. Then the output from the different prep steps can be combined in a single `--task post` step (the post step doesn't look at --libType): https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#running-prep-and-post-separately

Being able to specify different --libType values for different samples in the same step would be a nice feature, but I don't think I'll get a chance to work on that any time soon

**Comment by abhilashdasari** [comment]
Thank you so much
