### ISSUE TITLE
Threshold for incLevelDifference

### ISSUE THREAD

**Issue by klossaw** [Xinglab/rmats-turbo#306]
I would like to ask about the reasonable threshold for IncLevelDifference?Maybe 0.1 or 0.2 is reasonable?Thank you very much!

**Comment by EricKutschera** [comment]
Using 0.1 or 0.2 as a threshold for IncLevelDifference seems reasonable to me. This issue has some discussion about filtering based on IncLevelDifference: https://github.com/Xinglab/rmats-turbo/issues/183#issuecomment-1054318031

**Comment by klossaw** [comment]
Tank you for your help,eric!
