### ISSUE TITLE
output file explanation

### ISSUE THREAD

**Issue by rezarahman12** [Xinglab/rmats-turbo#308]
Dear rMATS team
I've used rMATS-turbo to identify alternative splicing of two conditions using fastq file. I've seen there is no error message but in the output file I noticed some parameters which I pasted below-
read outcome totals across all BAMs
USED: 533749912
NOT_PAIRED: 0
NOT_NH_1: 50779464
NOT_EXPECTED_CIGAR: 9336232
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 10512556
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 825860
CLIPPED: 0
total: 605204024
outcomes by BAM written to: test/fastq/24h/out/2023-07-29-15_39_26_063734_read_outcomes_by_bam.txt

My questions is it normal output or I need to give any other flags? 

I do highly appreciate your time and help.
Kind reards
Reza

**Comment by EricKutschera** [comment]
That output looks good. It shows that about 88% of the alignments passed the filters. The numbers for the different outcomes look normal and you don't need to use any other flags

**Comment by rezarahman12** [comment]
Thanks a lot for your clarification. I appreciate your time.
