### ISSUE TITLE
Does rMATS work for mature mRNA splicing?

### ISSUE THREAD

**Issue by s-weissbach** [Xinglab/rmats-turbo#311]
Hi,

I've used rMATS for some time and it worked always fine for me. Now, I have a dataset of ribosomal bound mRNA and it does not yield any splicing events.

```
EventType	TotalEventsJC	TotalEventsJCEC	SignificantEventsJC	SigEventsJCSample1HigherInclusion	SigEventsJCSample2HigherInclusion	SignificantEventsJCEC	SigEventsJCECSample1HigherInclusion	SigEventsJCECSample2HigherInclusion
SE	21803	21803	0	0	0	0	0	0
A5SS	3465	3465	0	0	0	0	0	0
A3SS	5907	5907	0	0	0	0	0	0
MXE	1037	1037	0	0	0	0	0	0
RI	4512	4512	0	0	0	0	0	0
```

Is there a way to detect splicing events in such data?

**Comment by stephaaaaan** [comment]
The problem seems to be `JUNCTION_NOT_MATCHED_TO_ANNOTATION: 56318416`, `EXON_NOT_MATCHED_TO_ANNOTATION: 114267742` and `NOT_NH_1: 13610008`. What can I do to fix this?

`USED: 11043618
NOT_PAIRED: 18217
NOT_NH_1: 13610008
NOT_EXPECTED_CIGAR: 1188172
NOT_EXPECTED_READ_LENGTH: 3877414
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 114267742
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 56318416
CLIPPED: 14457729
TOTAL_FOR_BAM: 214781316`

**Comment by EricKutschera** [comment]
EXON_NOT_MATCHED_TO_ANNOTATION and JUNCTION_NOT_MATCHED_TO_ANNOTATION would happen if the alignment coordinates don't match up with the --gtf file given to rMATS. What reference files did you use to align the reads and what --gtf did you use with rMATS?

**Comment by s-weissbach** [comment]
I in fact did use a GTF version that was not most up-to-date. I rerun with matching gtf file and still have a lot of reads that do not match the annotation.
```
USED: 11440206
NOT_PAIRED: 21863
NOT_NH_1: 14273673
NOT_EXPECTED_CIGAR: 1170923
NOT_EXPECTED_READ_LENGTH: 6439870
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 112085721
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 51812141
CLIPPED: 14925959
TOTAL_FOR_BAM: 212170356
```
Although this time I got some splice events:
```
EventType	TotalEventsJC	TotalEventsJCEC	SignificantEventsJC	SigEventsJCSample1HigherInclusion	SigEventsJCSample2HigherInclusion	SignificantEventsJCEC	SigEventsJCECSample1HigherInclusion	SigEventsJCECSample2HigherInclusion
SE	21894	21894	0	0	0	0	0	0
A5SS	3485	3485	0	0	0	0	0	0
A3SS	5941	5941	0	0	0	0	0	0
MXE	1050	1050	0	0	0	0	0	0
RI	4529	4529	0	0	0	0	0	0
```

I used:
- Gencode vM33 annotation for mm39 (https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M33/gencode.vM33.annotation.gtf.gz) 

I also downloaded the reference genome from there, so that should work and the same set-up worked for other analysis.

**Comment by s-weissbach** [comment]
Hi, sorry for not replying. 

I used GRCm39.primary_assembly.genome.fa (also Gencode), so it should be fine in my opinion. 

What do you mean by manually checking the alignment with the gtf? 

The alignment in the bam file looks like this:
```
D00535:22:CBLNNANXX:6:2307:15540:28250  147     chr1    3055037 255     101M    =       3055021 -117  CTATCCCTGACATCAATTTAGCCTTTCTTTTTCTATTGTTCTTATTTAAGCAGTTGTACTCCTGTGTTCTAGCTGCTTCTCCTTATCATCCCCTAACCTCA GGFGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGBCBBB NH:i:1  HI:i:1  AS:i:199        nM:i:0
```
But how to check whether this matches the gtf file?

**Comment by EricKutschera** [comment]
GRCm39.primary_assembly.genome.fa should be fine

You can look at the alignments and gtf in IGV and see if the exons and junctions match up. rMATS is expecting any exon alignments to be aligned within the coordinates of an annotated exon. rMATS is expecting junction alignments to have splice sites that match the coordinates of splice sites in the annotation

The example alignment you posted is a 101 bp match starting at 3,055,037 on chr1. With gencode.vM33.annotation.gtf loaded I don't see any annotated exon at those coordinates. The closest exon in at about 3,143,000

![20230817_igv_coord](https://github.com/Xinglab/rmats-turbo/assets/3375309/fbf5f211-ab66-4b2a-99ca-4c0fc7a6279e)

**Comment by s-weissbach** [comment]
Ah, this is a good idea. 

I checked in IGV for three individual files and some different genes. Everything seems to be as expected
![Screenshot from 2023-08-17 16-28-56](https://github.com/Xinglab/rmats-turbo/assets/37835571/3f5197c3-f938-429e-9cec-cf68c8f0f231)

**Comment by EricKutschera** [comment]
The alignments in that screenshot do look like they line up with the exons in the gtf. There are some exon alignments in between the annotated exons which I would expect to get the NOT_MATCHED_TO_ANNOTATION outcome. Also it's hard to tell if the alignments exactly match without zooming in or checking the cigar and start coordinate

The coverage track in the screenshot shows 570 as the upper limit. The read outcome totals that you posted before showed about 75% of alignments with NOT_MATCHED_TO_ANNOTATION. Maybe the alignments in the screenshot are ok, but the other alignments that didn't fit on the screen could have an issue

Can you post one of the bam files (or part of a bam file)?

**Comment by s-weissbach** [comment]
I filtered for chr1 to have a file that can be uploaded to wetransfer. 
https://we.tl/t-6qW8aexKad

I went for more alignments through, and for me it looks good... It is really puzzling.

**Comment by EricKutschera** [comment]
I ran rMATS using that chr1 bam file and the outcomes look ok:
```
USED: 9400775
NOT_PAIRED: 968
NOT_NH_1: 401389
NOT_EXPECTED_CIGAR: 49556
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 175564
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 18107
CLIPPED: 696627
total: 10742986
```

87% of the reads were used and less than 2% had NOT_MATCHED_TO_ANNOTATION. There doesn't seem to be any issue with that bam file
