### ISSUE TITLE
cryptic exons

### ISSUE THREAD

**Issue by rezarahman12** [Xinglab/rmats-turbo#314]
Hello rMATS developer,

I'm just wondering whether rMATS cab be used for the identification of cryptic exons from RNA-seq, if so, may you please shed some light on the approach to detect cryptic exons?
Thank you for your consideration.

Best regards
Reza

**Comment by EricKutschera** [comment]
rMATS uses the exons in the --gtf to detect splicing events. If --novelSS is used then rMATS can detect events where some of the splice sites are not found in the --gtf. However, rMATS will not detect events with an exon where both splice sites are not in the --gtf. This post has some details about how rMATS detects events: https://github.com/Xinglab/rmats-turbo/issues/17

**Comment by rezarahman12** [comment]
thanks
