### ISSUE TITLE
Running prep and post steps separately

### ISSUE THREAD

**Issue by bbtn1993** [Xinglab/rmats-turbo#315]
Hi, I ran a prep step on all 15 of my samples at the same time and got the .rmats files.  I am now trying to run the post step with the following command:
python rmats.py --b1 /root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/XXX/Mouse_heart_male/rmats_files/post2.txt --b2 /root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/XXX/Mouse_heart_male/rmats_files/post1.txt --gtf /root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/XXX/gencode.vM25.annotation.gtf -t paired --readLength 150 --nthread 10 --od /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/XXX/Mm_male_hearts/post_output_DM1204_DM1 --tmp /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/XXX/Mm_male_hearts/tmp_post_output_DM1204_DM1 --task post

I am getting the following error for every sample:
/root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/XXX/Mouse_heart_male/rmats_files/2023-08-24-13_55_39_818525_10.rmats not found in .rmats files

I rechecked the post1 and post2 files, and they have the correct paths to the .rmats files.  Do I still need to run the script to disambiguate my files if they are all named differently?  They are all in the same folder.  Thanks!

**Comment by EricKutschera** [comment]
The --b1 and --b2 files have paths to bams in them just like in the prep step: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#running-prep-and-post-separately. From the error it looks like your --b1 and --b2 files have paths to .rmats files

The post step will look for the .rmats files in the --tmp directory. For every .rmats file found it will check the first line of the file to see what bams that .rmats file is for. The --b1 and --b2 files give the paths to the bams to use. The paths in --b1 and --b2 need to be found in the .rmats files. The post step won't actually read the bam files, but it uses the path as a string to find info in the .rmats files

**Comment by bbtn1993** [comment]
Hi Erik,
Thanks.  Now I am getting the error:
/root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/XXX/Mouse_heart_male/G7-2_001.HISAT2-2.2.1.aligned.sorted.bam not found in .rmats files, so I think rMATS is having a hard time finding the .rmats files.  My command this time was:
python rmats.py --b1 /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/DM1/Mm_male_hearts/WT.txt --b2 /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/DM1/Mm_male_hearts/DM1.txt --gtf /root/cloud-data/snf-mgln-ts-us/Science_Computing/Dongyu/DM1/gencode.vM25.annotation.gtf -t paired --readLength 150 --nthread 10 --od /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/DM1/Mm_male_hearts/post_output_WT_DM1 --tmp /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/DM1/Mm_male_hearts/tmp_post_output_WT_DM1 --task post

My "tmp_output_prep1" folder is in the /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/DM1/Mm_male_hearts/ folder, and I also copied it into the folder containing the bam files in case it was looking there for rmats files.

**Comment by EricKutschera** [comment]
The --tmp directory used for the post step needs to have the .rmats files in it. It sounds like you got the .rmats files from the prep step, but then you copied them to the wrong directory

If you want to run the post step with  `--tmp /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/DM1/Mm_male_hearts/tmp_post_output_WT_DM1` then the output from:
```
head -n 1 /home/RICBR01/GROUP-TS/ScienceComputing/Brenda/rmats/DM1/Mm_male_hearts/tmp_post_output_WT_DM1/*.rmats
```
should include all the bam files in --b1 and --b2

**Comment by bbtn1993** [comment]
Eric, thanks for all your help.  I was able to get the results that I needed, much appreciated!
