### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by katagirya** [Xinglab/rmats-turbo#329]
I am running rMATS on bam files with the following command:

```
#!/bin/bash

#PBS -m e
#PBS -k oe
#PBS -l nodes=1:ppn=16
#PBS -l vmem=50GB
#PBS -l walltime=24:00:00

# Load any necessary modules
#module load rMATS  # Load rMATS module if available
source /etc/profile.d/modules.sh #enables the modules to work on the cluster
module load rmats/4.0.2
module load anaconda2/2019.10
module load star
module load samtools


# Specify output directory and temporary directory
output_directory=/project/output_rmat

# Change to the directory where your BAM files and annotation file are located
cd /project/aligned_files

# Run rMATS
python2.7 /share/apps/rmats/4.0.2/rMATS-turbo-Linux-UCS4/rmats.py --b1 /home/eric/hisat_analysis/cases.txt --b2 /home/eric/hisat_analysis/controls.txt --gtf /home/eric/reference/gencode.v19.annotation.gtf -t paired --readLength 98 --od $output_directory --nthread 16
```

However, I get an error below:

Traceback (most recent call last):
  File "/share/apps/rmats/4.0.2/rMATS-turbo-Linux-UCS4/rmats.py", line 308, in <module>
    main()
  File "/share/apps/rmats/4.0.2/rMATS-turbo-Linux-UCS4/rmats.py", line 289, in main
    run_stat(jc_it % ('SE'), args.tstat, 'JC', 'SE', args.cstat, args.od, args.tmp, args.stat)
  File "/share/apps/rmats/4.0.2/rMATS-turbo-Linux-UCS4/rmats.py", line 230, in run_stat
    validate_countfile(istat)
  File "/share/apps/rmats/4.0.2/rMATS-turbo-Linux-UCS4/rmats.py", line 185, in validate_countfile
    header = data[0]
IndexError: list index out of range

What could I be doing wrong?

Thanks

**Comment by EricKutschera** [comment]
It looks like you are using rMATS v4.0.2 which is before the code was available on github: http://rnaseq-mats.sourceforge.net/
You could try the latest version, v4.1.2, which has some fixes and should at least give a better error message. It looks like you have a conda module so you could install rmats v4.1.2 with conda like in this post: https://github.com/Xinglab/rmats-turbo/issues/304#issuecomment-1621728170

The traceback you posted seems to be saying that one of the output files was empty when it shouldn't be, but I'm not sure why that would happen

**Comment by katagirya** [comment]
Thanks, Eric. I am going to try this.
