### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zpliu1126** [Xinglab/rmats-turbo#34]
Hi~ 
when I according the protocol to install rmats-turbo. I code `././build_rmats --conda` ,it  prompt me `bash: gsl-config: command not found`;But I checked my path,and typed `gsl-config` work well。 I don't know  why it not work。

```bash
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
bash: gsl-config: command not found
(base) [zpliu@mn02 rmats-turbo]$ gsl-config 
Usage: gsl-config [OPTION]

Known values for OPTION are:

  --prefix		show GSL installation prefix 
  --libs		print library linking information, with cblas
  --libs-without-cblas	print library linking information, without cblas
  --cflags		print pre-processor and compiler flags
  --help		display this help and exit
  --version		output version information

An external CBLAS library can be specified using the GSL_CBLAS_LIB
environment variable. The GSL CBLAS library is used by default.
```
Best Regards

**Comment by EricKutschera** [comment]
It looks like you may have gsl-config installed in your "base" conda environment. You can check the full path of the gsl-config that is being run with `which gsl-config`. When you run `./build_rmats --conda` it activates a new conda environment (./conda_envs/rmats) which does not have gsl-config. With the new conda environment active it won't be able to find things from your "base" environment.

You could try manually installing gsl in ./conda_envs/rmats and then re-running the build:

```
conda activate ./conda_envs/rmats
conda install -c conda-forge -c bioconda gsl
conda deactivate
./build_rmats --conda
```

**Comment by zpliu1126** [comment]
oh~，it not work too。
I activate `rmats`  env  and rebuild；and the `gsl-config` is in this env when I type `which gsl-congif`

```bash
activate ./conda_envs/rmats/
conda install -c conda-forge -c bioconda gsl
./build_rmats
```
![EN0@9P2_DC{9@75%7Z@TGHY](https://user-images.githubusercontent.com/39325949/89296464-f577e280-d694-11ea-8376-e0a9746df147.png)

**Comment by EricKutschera** [comment]
Try `./build_rmats --conda` instead of just `./build_rmats`. Having ./conda_envs/rmats/ already activated may not work because the build script will source your ~/.bashrc which may re-activate your "base" environment

**Comment by zpliu1126** [comment]
after install `gsl-config` in rMats env，and I rebuild in the `base` env I find the `rMats` env will reinstall again； and `gsl-config`  disappear
```bash
## rMats env
conda   install -c conda-forge -c bioconda gsl
conda deactivate 
## base env
./build_rmats --conda 
```
![image](https://user-images.githubusercontent.com/39325949/89298940-94520e00-d698-11ea-9625-53bc7600a4da.png)

**Comment by EricKutschera** [comment]
The install should give you a prompt like:
`WARNING: A conda environment already exists at '/path/to/rmats-turbo/conda_envs/rmats' Remove existing environment (y/[n])?`

If you choose "n" (the default) it should keep what you installed manually.

As an alternative, you could add `conda install -c conda-forge -c bioconda gsl` immediately before the first usage of `gsl-config` in ./build_rmats to ensure that any newly created environment gets gsl installed

**Comment by zpliu1126** [comment]
wo,fixed this bug,I builded successful!

Because run `./build_rmats ` would `source ~/.bashrc` and  then activate `base` env ；
so it would prompt that `bash: gsl-config: command not found`  which is in `rMATs` env。
process looks like that

```bash
 ##create rMats env
./build_rmats --conda
## activate rMats env
conda activate ./conda_envs/rmats/
conda install -c conda-forge -c bioconda gsl
## add rMats env bins to ~/.bashrc
export PATH="path-to-rmats/rmats-turbo/conda_envs/rmats/bin:${PATH}"
## rebuild 
source ~/.bashrc
./build_rmats 
```
Thank you for your patiently answer my questions~~

**Comment by Anees-caas** [comment]
Hi ~ 
I am following the above steps but am also getting the error.
 ./build_rmats --conda
-bash: ./build_rmats: No such file or directory"
