### ISSUE TITLE
STAR_binary_index

### ISSUE THREAD

**Issue by bbtn1993** [Xinglab/rmats-turbo#341]
Hi, I am trying to run rMATS from fastq files instead of bam files this time.  Is the STAR_binary_index something that should already exist from setting up rMATS turbo, or is it something I need to create? (I did not set up rMATS turbo).  Thanks!

**Comment by EricKutschera** [comment]
The STAR binary index needs to be created. Here's the README description:
```

--bi BINDEX   The directory name of the STAR binary indices (name of
              the directory that contains the SA file). (Only if using fastq)
```

https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf has a section titled "Generating genome indexes that explains how to create an index. A possible command is:
```
STAR --runThreadN {threads} --runMode genomeGenerate --genomeDir /path/to/output_STAR_binary_index --genomeFastaFiles /path/to/GRCh38.primary_assembly.genome.fa --sjdbGTFfile /path/to/gencode.v44.primary_assembly.annotation.gtf
```

where the input files are the gencode human reference files: https://www.gencodegenes.org/human/
https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.primary_assembly.annotation.gtf.gz
https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/GRCh38.primary_assembly.genome.fa.gz

**Comment by HadesK9** [comment]
Hi tried this but I keep getting this error
-bash: STAR: command not found

any idea what I'm doing wrong? thank you!

**Comment by bbtn1993** [comment]
Thanks so much for your help!  This seems to have worked successfully, and I have attached a file showing the output files.  Does this look like what I should get for output?  Which file(s) will rMATS actually use from this output?
[Output_STAR_binary_index.docx](https://github.com/Xinglab/rmats-turbo/files/13382997/Output_STAR_binary_index.docx)

Thanks again!  Brenda

**Comment by EricKutschera** [comment]
Yes those files look correct. rMATS will use the directory as the `--genomeDir` argument to STAR:
https://github.com/Xinglab/rmats-turbo/blob/v4.2.0/rmats.py#L72

**Comment by bbtn1993** [comment]
Thanks again :)
