### ISSUE TITLE
So many problems when using rMATs !!!

### ISSUE THREAD

**Issue by AIBio** [Xinglab/rmats-turbo#35]
Hi,

Let's us directly go into the main points.

### 1st problem: installation

I used the command as below:
`/build_rmats --conda`

The last returned information showed as below: 
> Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Loading required package: nloptr
Loading required package: foreach
Loading required package: doParallel
Loading required package: iterators
Loading required package: parallel
Loading required package: PAIRADISE

But! When I run:
`./run_rmats`

The error came to my screen:
>Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rmats.py", line 16, in <module>
    from rmatspipeline import run_pipe
ImportError: /home/cmq/software/rmats-turbo/rmatspipeline.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK8BamTools12BamAlignment14SetErrorStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_

I activated the environment in building step and then ran again, But the error still exists.

Do you have any idea can fix this problem.

### 2nd problem: Running rMATs

Since the rMATs can be installed by conda, I tried to skip the building step and directly analyzed my data.
My command to install packages: `conda install -c bioconda rmats`. (python 2.7)

I ran the command:
`gtf=/home/yhw/genome/ensembl/release97/mus_musculus/dna_anno/Mus_musculus.GRCm38.97.gtf`
`rmats.py --b1 dox_bamfile.txt --b2 nodox_bamfile.txt -t paired --od ${OutDir} --gtf ${gtf} --tmp ./temp --readLength 123 --variable-read-length --nthread 12 --tstat 6 --cstat 0.05 --libType fr-unstranded > ${log_file} 2>&1`
my bam txt files (dox_bamfile.txt)
> ./results/star/no_rmrRNA_unique/SRR4032346_1_val_1_SRR4032346_2_val_2Aligned.sortedByCoord.out.bam,./results/star/no_rmrRNA_unique/SRR4032347_1_val_1_SRR4032347_2_val_2Aligned.sortedByCoord.out.bam
(nodox_bamfile.txt)
> ./results/star/no_rmrRNA_unique/SRR4032348_1_val_1_SRR4032348_2_val_2Aligned.sortedByCoord.out.bam,./results/star/no_rmrRNA_unique/SRR4032349_1_val_1_SRR4032349_2_val_2Aligned.sortedByCoord.out.bam

I have checked the consistency of chromosome name between bam file and gtf file. My genome fa file and gtf file were downloaded from ENSEMBL. STAR was used to align sequences to genome.

The returned information:

> gtf: 15.9409089088
There are 55573 distinct gene ID in the gtf file
There are 142333 distinct transcript ID in the gtf file
There are 34470 one-transcript genes in the gtf file
There are 839112 exons in the gtf file
There are 26884 one-exon transcripts in the gtf file
There are 21787 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 2.561190
Average number of exons per transcript is 5.895414
Average number of exons per transcript excluding one-exon tx is 7.035384
Average number of gene per geneGroup is 7.477396
statistic: 0.0188231468201
novel: 275.361290932
The splicing graph and candidate read have been saved into ./temp/2020-08-05-10:17:36_394168.rmats
save: 0.000603199005127
loadsg: 0.000283002853394
==========
Done processing each gene from dictionary to compile AS events
Found 18864 exon skipping events
Found 728 exon MX events
Found 8323 alt SS events
There are 5310 alt 3 SS events and 3013 alt 5 SS events.
Found 4082 RI events
==========
ase: 1.25338506699
count: 0.19796705246
Processing count files.
Done processing count files.

But! the results are empty !!!

After adding parameter `--statoff`, I got the non-empty results. However, I want to find the differential splicing events. Do you have any suggestions to figure it out? 

Just now, I change the --cstat as 0.5 and ran again.
`gtf=/home/yhw/genome/ensembl/release97/mus_musculus/dna_anno/Mus_musculus.GRCm38.97.gtf`
`rmats.py --b1 dox_bamfile.txt --b2 nodox_bamfile.txt -t paired --od ${OutDir} --gtf ${gtf} --tmp ./temp --readLength 123 --variable-read-length --nthread 12 --tstat 6 --cstat 0.5 --libType fr-unstranded > ${log_file} 2>&1`

The results named with *MATS* are still empty~

I don't believe all differential splicing events are non-significanyly. I guess the package wasn't installed correctly. Hence, I'm tring to re-installed the packages without using conda.

Your timely reply and precious advices can save my life. It took me two days to fix these problems.

Hanwen Yu

**Comment by EricKutschera** [comment]
For this error:
`ImportError: /home/cmq/software/rmats-turbo/rmatspipeline.cpython-36m-x86_64-linux-gnu.so: undefined symbol: ZNK8BamTools12BamAlignment14SetErrorStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8`

You could try the solution from this issue: https://github.com/Xinglab/rmats-turbo/issues/21

For the empty output, if your build issue is resolved, you could try building and running the code from the latest master branch which includes this change https://github.com/Xinglab/rmats-turbo/pull/25

That change writes out stats about why rMATS is unable to use the reads in the BAM files. It may help identify the cause of your empty output

**Comment by AIBio** [comment]
> 
> 
> For this error:
> `ImportError: /home/cmq/software/rmats-turbo/rmatspipeline.cpython-36m-x86_64-linux-gnu.so: undefined symbol: ZNK8BamTools12BamAlignment14SetErrorStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8`
> 
> You could try the solution from this issue: #21
> 
> For the empty output, if your build issue is resolved, you could try building and running the code from the latest master branch which includes this change #25
> 
> That change writes out stats about why rMATS is unable to use the reads in the BAM files. It may help identify the cause of your empty output

Hi,

Thank you for your reply.

I followed your instructions to change the path of compilers in setup.py file and successfuly compile rMATS!
When I ran the packages to analyze data, some errors were reported.

> Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JC_SE/rMATS_result_P-V.txt'
paste: ./temp/JC_SE/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory

Seemingly, the pvalues aren't calculated. But I don't know how to fix it. Could you give me some suggestions?

Hanwen Yu

**Here is the full log file:**

> /home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: **libgfortran.so.5: cannot open shared object file: No such file or directory**
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JC_SE/rMATS_result_P-V.txt'
paste: ./temp/JC_SE/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JCEC_SE/rMATS_result_P-V.txt'
paste: ./temp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JC_MXE/rMATS_result_P-V.txt'
paste: ./temp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JCEC_MXE/rMATS_result_P-V.txt'
paste: ./temp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JC_A3SS/rMATS_result_P-V.txt'
paste: ./temp/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JCEC_A3SS/rMATS_result_P-V.txt'
paste: ./temp/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JC_A5SS/rMATS_result_P-V.txt'
paste: ./temp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JCEC_A5SS/rMATS_result_P-V.txt'
paste: ./temp/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JC_RI/rMATS_result_P-V.txt'
paste: ./temp/JC_RI/rMATS_result_FDR.txt: No such file or directory
/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/cmq/software/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: './temp/JCEC_RI/rMATS_result_P-V.txt'
paste: ./temp/JCEC_RI/rMATS_result_FDR.txt: No such file or directory
gtf: 15.319586515426636
There are 55573 distinct gene ID in the gtf file
There are 142333 distinct transcript ID in the gtf file
There are 34470 one-transcript genes in the gtf file
There are 839112 exons in the gtf file
There are 26884 one-exon transcripts in the gtf file
There are 21787 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 2.561190
Average number of exons per transcript is 5.895414
Average number of exons per transcript excluding one-exon tx is 7.035384
Average number of gene per geneGroup is 7.477396
statistic: 0.017763853073120117
novel: 0.03796553611755371
The splicing graph and candidate read have been saved into ./temp/2020-08-06-01:27:40_877421.rmats
save: 0.0017375946044921875
loadsg: 0.0008401870727539062
==========
Done processing each gene from dictionary to compile AS events
Found 18864 exon skipping events
Found 728 exon MX events
Found 8323 alt SS events
There are 5310 alt 3 SS events and 3013 alt 5 SS events.
Found 4082 RI events
==========
ase: 1.212465524673462
count: 0.2764575481414795
Processing count files.
Done processing count files.

**Comment by EricKutschera** [comment]
The traceback is caused by the earlier error: `/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory`

That seems to indicate that the gfortran library that was found at compile time is no longer available. If you know where `libgfortran.so.5` is on your system then you could add that path to LD_LIBRARY_PATH. Maybe your LD_LIBRARY_PATH or something else about your environment has changed while you were troubleshooting the compiler issues. One thing that you could try is deactivating the conda environment before running `run_rmats` because `run_rmats` will activate the environment itself. I'm not sure if that matters, but the conda environment might change the LD_LIBRARY_PATH or other environment variables

You could also try building from scratch so that a fresh conda environment is created. Maybe something has changed during the multiple attempts to get the build to finish

**Comment by AIBio** [comment]
> 
> 
> The traceback is caused by the earlier error: `/home/cmq/software/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory`
> 
> That seems to indicate that the gfortran library that was found at compile time is no longer available. If you know where `libgfortran.so.5` is on your system then you could add that path to LD_LIBRARY_PATH. Maybe your LD_LIBRARY_PATH or something else about your environment has changed while you were troubleshooting the compiler issues. One thing that you could try is deactivating the conda environment before running `run_rmats` because `run_rmats` will activate the environment itself. I'm not sure if that matters, but the conda environment might change the LD_LIBRARY_PATH or other environment variables
> 
> You could also try building from scratch so that a fresh conda environment is created. Maybe something has changed during the multiple attempts to get the build to finish

Hi,

As you said, I search the whole server to find `libgfortran.so.5` that is used in compiling step and add path of library (/usr/local/lib64) as an environment variable saved in conda env created by rMATs. (ref: [Saving environment variables](https://stackoverflow.com/questions/46826497/conda-set-ld-library-path-for-env-only)). 

Finally, I ran again with same command. The error dispeared ~

However, I met an another problem. -_-||

> Traceback (most recent call last):
  File "rmatspipeline/rmatspipeline.pyx", line 2929, in rmats.rmatspipeline._load_job
ValueError: './results/star/no_rmrRNA_unique/SRR4032346_1_val_1_SRR4032346_2_val_2Aligned.sortedByCoord.out.bam' is not in list
Exception ignored in: 'rmats.rmatspipeline._load_job'
Traceback (most recent call last):
  File "rmatspipeline/rmatspipeline.pyx", line 2929, in rmats.rmatspipeline._load_job
ValueError: './results/star/no_rmrRNA_unique/SRR4032346_1_val_1_SRR4032346_2_val_2Aligned.sortedByCoord.out.bam' is not in list
Traceback (most recent call last):
  File "rmatspipeline/rmatspipeline.pyx", line 2929, in rmats.rmatspipeline._load_job
ValueError: './results/star/no_rmrRNA_unique/SRR4032346_1_val_1_SRR4032346_2_val_2Aligned.sortedByCoord.out.bam' is not in list
Exception ignored in: 'rmats.rmatspipeline._load_job'
Traceback (most recent call last):
  File "rmatspipeline/rmatspipeline.pyx", line 2929, in rmats.rmatspipeline._load_job
ValueError: './results/star/no_rmrRNA_unique/SRR4032346_1_val_1_SRR4032346_2_val_2Aligned.sortedByCoord.out.bam' is not in list

I checked the bam files. The full paths of these files are correct. STAR didn't return me any errors. Do you know how to figure it out?

Hanwen Yu

**Comment by AIBio** [comment]
Hi,
Considering you may need more information to address this problem, I download the latest master branch to find out whether my bam files are incorrect or not. 

When `./build_rmats --conda`, an eroor showed up: 

>SafetyError: The package for r-base located at /home/cmq/software/anaconda3/pkgs/r-base-3.6.2-h7ed4ef7_1
appears to be corrupted. The path 'lib/R/doc/html/packages.html'
has an incorrect size.
  reported size: 2946 bytes
  actual size: 3846 bytes
                                                                                                                                                                                             done
Executing transaction: done
Cloning into 'PAIRADISE'...

**Comment by AIBio** [comment]
Hi,

Sorry to bother you so many times.

I built and ran the latest master branch of rMATs. By examining the **read_outcomes_by_bam.txt** file, I got the message: 
> /home/cmq/bioinfo/gse85632/results/star/no_rmrRNA_unique/SRR4032346_1_val_1_SRR4032346_2_val_2Aligned.sortedByCoord.out.bam
USED: 0
NOT_PAIRED: 69523310
NOT_NH_1: 0
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
TOTAL_FOR_BAM: 69523310

I think rMATS may fail to recognize paired-end data, such as bam files generated by STAR. After changing the `-t single` and running again, I got the non-empty results!!! I will try to use conda to install rMATs to compare the results whether they are same or not. 

At last, Thank you again ~~~

**Comment by AIBio** [comment]
Hi,

I compared the two results generated from two versions of rMATs installed by two method(one by conda, another by manually compile). They are total identical !!!

Thank you for precious suggestions ~~~

Hanwen Yu
