### ISSUE TITLE
error while loading shared libraries: libgsl.so.25

### ISSUE THREAD

**Issue by Qingru44004** [Xinglab/rmats-turbo#352]
Hi,

I used conda to install rmats. But when I run statistic part it shows me error:

miniconda3/envs/rmats3.9/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "miniconda3/envs/rmats3.9/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'rmats_post/tmp/JC_SE/rMATS_result_P-V.txt'
paste: rmats_post/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory

I tried to install gsl==2.5. But the error shows that rmats requires gsl>=2.7

Could not solve for environment specs
The following packages are incompatible
├─ gsl 2.5  is requested and can be installed;
├─ pin-1 is installable and it requires
│  └─ python 3.9.* , which can be installed;
└─ rmats is not installable because there are no viable options
   ├─ rmats [4.1.2|4.2.0] would require
   │  └─ gsl >=2.7,<2.8.0a0 , which conflicts with any installable versions previously reported;

**Comment by EricKutschera** [comment]
The rmats bioconda package expects to be installed with conda-forge dependencies and the conda-forge gsl-2.7 uses libgsl.so.25. Using `-c conda-forge` with `conda install` usually works, but conda might have a config value that prevents things from working correctly. `conda config --show-sources` can show the values and `channel_priority: disabled` could be causing the issue

See these posts:
https://github.com/Xinglab/rmats-turbo/issues/281
https://github.com/Xinglab/rmats-turbo/issues/300

**Comment by Qingru44004** [comment]
Thanks! It solved my problem.
