### ISSUE TITLE
Do I need to filter out the low reads of IJC and SJC？

### ISSUE THREAD

**Issue by Squirrelity** [Xinglab/rmats-turbo#354]
Thank you for your tool. I found that the read count of IJC and SJC running out is very low, but their fdr is less than 0.05. Do I need to filter them out？
IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2
0	1	1	0
1	0	0	2
0	1	1	0
1	0	0	1
1	0	0	2
2	0	0	1
2	4	7	0
0	2	1	0
2	0	0	1

**Comment by EricKutschera** [comment]
Filtering out events with low read counts is reasonable: https://github.com/Xinglab/rmats-turbo/issues/183#issuecomment-1054318031

**Comment by Squirrelity** [comment]
> Filtering out events with low read counts is reasonable: [#183 (comment)](https://github.com/Xinglab/rmats-turbo/issues/183#issuecomment-1054318031)

Thank you！
