### ISSUE TITLE
intron retention

### ISSUE THREAD

**Issue by rezarahman12** [Xinglab/rmats-turbo#357]
Hi Eric,
I would like to know the start and end of retained introns events from rMATS output. Should I check columns upstreamEE and downstreamES? How can I design a primer targeting retained introns for RT PCR validation?

I appreciate your time and help.

Best regards
Reza

**Comment by EricKutschera** [comment]
From the README: https://github.com/Xinglab/rmats-turbo/tree/v4.2.0#output
> The inclusion form includes (retains) the intron (upstreamEE, downstreamES)

This post shows what each coordinate represents: https://github.com/Xinglab/rmats-turbo/issues/158#issuecomment-966763718

I'm not familiar with designing primers

**Comment by rezarahman12** [comment]
Thanks
