### ISSUE TITLE
Error running rMATS in ubuntu with conda

### ISSUE THREAD

**Issue by mlcsmits** [Xinglab/rmats-turbo#369]
Hey rMATS team, I was working on ubuntu with conda and trying to run rMATS turbo 4.2.0 when it exited in failure. Here is everything that I know: I ran the following command: 
python /mnt/studentfiles/2024/2024MBI03/rmats_turbo_v4_2_0/rmats.py --b1 /mnt/studentfiles/2024/2024MBI03/subset/subset_SRR19760417.bam --gtf /mnt/studentfiles/2024/2024MBI03/RefSeq/genomic.gtf -t paired --readLength 100 --nthread 4 --od /mnt/studentfiles/2024/2024MBI03/rmats/ --tmp /mnt/studentfiles/2024/2024MBI03/rmats/
This is the output of the tool: 
 (See figure attached)
![rMATS error](https://github.com/Xinglab/rmats-turbo/assets/161313142/28b38a4d-22c1-4154-bc09-98144e372e30)

I have read it but I do not understand what those error means. I've read the manual page for the rMATS tool and I think I'm calling it correctly, I attempted calling with --variable-read-length and we have tried to make the path into a text file, it did not succeed. Could you please help me?

**Comment by jingxian555** [comment]
Hello,the steps for my successful installation are shared with you.
<img width="487" alt="微信图片_20240226214934" src="https://github.com/Xinglab/rmats-turbo/assets/144584241/bc5e6dc7-fdd1-49e2-8f23-2fa2360493c3">

**Comment by EricKutschera** [comment]
Here's the line for that error: https://github.com/Xinglab/rmats-turbo/blob/v4.2.0/rmats.py#L189

It's trying to read your --b1 file as a text file, but your command gave subset_SRR19760417.bam as --b1

Here's an example of --b1 b1.txt from the README: https://github.com/Xinglab/rmats-turbo/tree/v4.2.0?tab=readme-ov-file#starting-with-bam-files

**Comment by jingxian555** [comment]
辛苦了，邮件已收到~我会尽快给你回复的

**Comment by EricKutschera** [comment]
Here's the line for the error: https://github.com/Xinglab/rmats-turbo/blob/v4.2.0/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L3737

It's reading all the .rmats files in your --tmp directory and for each file it expects the 1st line to be comma separated bam paths (like from --b1). Then it expects the 2nd line to be the read length. Somehow it found what looks like a line from a .sam file. My guess is that it's reading a .rmats file created from a previous run where --b1 was not being supplied correctly

If you remove your --tmp directory (or use a new empty --tmp directory) and try again then that error might go away

**Comment by mlcsmits** [comment]
The code worked with a new tmp directory. Thank you
