### ISSUE TITLE
Segmentation fault and ValueError: 'file path' is not in list

### ISSUE THREAD

**Issue by shum-sky** [Xinglab/rmats-turbo#37]
Hi again!

In the experiment I am trying to apply rMATS to, I have 2 conditions, genotype and diet. When I divided the samples by just one condition (genotype), everything worked fine, apart from few differential splicing events :)

However, when I tried to separate the samples by two conditions, the script gave me the following error:

/opt/sge/default/spool/hpc10/job_scripts/62788: line 13:  3224 Segmentation fault      (core dumped) /home/ashumskiy/anaconda3/bin/python /home/ashumskiy/Programs/rmats-turbo/rmats.py --b1 /home/ashumskiy/SIRT6/rMATS/WTND.txt --b2 /home/ashumskiy/SIRT6/rMATS/KOND.txt --gtf /home/ashumskiy/Mus_musculus.GRCm38.100.gtf -t single --readLength 90 --nthread 4 --od /home/ashumskiy/SIRT6/rMATS/WTND_vs_KOND --tmp /home/ashumskiy/SIRT6/rMATS/tmp --variable-read-length

/opt/sge/default/spool/hpc10/job_scripts/62788: line 18:  3255 Segmentation fault      (core dumped) /home/ashumskiy/anaconda3/bin/python /home/ashumskiy/Programs/rmats-turbo/rmats.py --b1 /home/ashumskiy/SIRT6/rMATS/WTND.txt --b2 /home/ashumskiy/SIRT6/rMATS/KOHFD.txt --gtf /home/ashumskiy/Mus_musculus.GRCm38.100.gtf -t single --readLength 90 --nthread 4 --od /home/ashumskiy/SIRT6/rMATS/WTND_vs_KOHFD --tmp /home/ashumskiy/SIRT6/rMATS/tmp --variable-read-length
/opt/sge/default/spool/hpc10/job_scripts/62788: line 23:  3275 Segmentation fault      (core dumped) 

/home/ashumskiy/anaconda3/bin/python /home/ashumskiy/Programs/rmats-turbo/rmats.py --b1 /home/ashumskiy/SIRT6/rMATS/WTND.txt --b2 /home/ashumskiy/SIRT6/rMATS/WTHFD.txt --gtf /home/ashumskiy/Mus_musculus.GRCm38.100.gtf -t single --readLength 90 --nthread 4 --od /home/ashumskiy/SIRT6/rMATS/WTND_vs_WTHFD --tmp /home/ashumskiy/SIRT6/rMATS/tmp --variable-read-length
Traceback (most recent call last):
File "rmatspipeline/rmatspipeline.pyx", line 2929, in rmats.rmatspipeline._load_job
ValueError: '/home/ashumskiy/SIRT6/results_star/bam/mouse-25122---B1.bam' is not in list
Exception ignored in: 'rmats.rmatspipeline._load_job'

The last part with the Python error happened a couple of times, with the mouse-25122, as well as another one, all of which are contained in the three runs that suffered a segmentation fault. All other runs went smoothly.

I am definitely sure the path is right and the files are not corrupted, would be grateful for some help in this matter!

**Comment by Oliverfeudj** [comment]
Hello, @EricKutschera I am writing here because I'm facing exactly the same issue, how do I "give each run a separate --tmp directory" please?
Thank you for your reply

**Comment by EricKutschera** [comment]
Each time you run an rmats command you can use a different directory path for --tmp.
For example:
* `python rmats.py --tmp /path/to/rmats_directory/run_1_tmp {other arguments}`
* `python rmats.py --tmp /path/to/rmats_directory/run_2_tmp {other arguments}`

That prevents different runs of rmats from seeing temporary files from other old runs
