### ISSUE TITLE
Failed to open BAM files, all results files are emtpy, changed to --outSAMtype BAM Unsorted

### ISSUE THREAD

**Issue by kerendanan1511** [Xinglab/rmats-turbo#370]
Hi, 

After submitting rmats_py using this command line: 

python ~/.conda/envs/rmats_env/bin/rmats.py --s1 septic.txt --s2 non_septic.txt --gtf /$GTF --bi $STAR_index -t paired --readLength 150 --nthread 32 --od output_dir --tmp output_dir/tmp_output --variable-read-length --novelSS 

all the fastq files have created a regular bam dir including aligned.out.bam files as normal, but all the output files of the rmats are empty and have 0 AS events. 

I have received failed to open BAM files, but it didnt rise any exception. 

I have checked in the issues of the git and none of the paths provided include ~/, beside the path to rmats.py in my conda env. Have to mention that I have already  run rmats on different fastq files, and successfully. This time had to do these changes due to the error that led me to change the parameter in STAR. 

Any ideas what did I do wrong? 

Thanks

**Comment by EricKutschera** [comment]
When run with --s1 rMATS assumes the STAR command will output `Aligned.sortedByCoord.out.bam`: https://github.com/Xinglab/rmats-turbo/blob/v4.2.0/rmats.py#L84

You mentioned the bam dirs have `aligned.out.bam` which is not the file rMATS is looking for. Maybe that's related to the STAR parameter change you made

If you already have the bam files that you want from the previous run then you could try running rMATS with --b1 and --b2 to avoid running STAR again. Also if you are doing a new run you can use new --od and --tmp directories to avoid any issues of rMATS finding old files

**Comment by kerendanan1511** [comment]
Thank you!  it worked
