### ISSUE TITLE
no files had been generated in prep and post

### ISSUE THREAD

**Issue by suiyue7** [Xinglab/rmats-turbo#375]
Hi, your software is great and I am very grateful for developing such a good tool. I am trying to run rmats from bam.Howerver,three hours later, no files had been generated in prep and post.
rmats was installed through conda.
bam was generated by star.
Here is my code:
/data/users/yekeyue2024/.conda/envs/rMATs/bin/rmats.py --gtf /data/users/yekeyue2024/database/ucsc_human/hg38.ncbiRefSeq.gtf --tmp /data/users/yekeyue2024/rnasplicing/GMCM/cleandata/star/prep/ --od /data/users/yekeyue2024/rnasplicing/GMCM/cleandata/star/post/ --readLength 150 --b1 /data/users/yekeyue2024/rnasplicing/GMCM/cleandata/star/b1.txt --b2 /data/users/yekeyue2024/rnasplicing/GMCM/cleandata/star/b1.txt -t paired  --anchorLength 1 --nthread 6 --libType fr-unstranded --task both --variable-read-length --novelSS

![1](https://github.com/Xinglab/rmats-turbo/assets/146133498/7ac67ae1-e27e-46f1-98a2-4fab856afb75)
![2](https://github.com/Xinglab/rmats-turbo/assets/146133498/12dafd6b-964c-4b99-8be8-23c9c57a1b8b)
![3](https://github.com/Xinglab/rmats-turbo/assets/146133498/f9106a0d-a9d4-4440-89df-95cfe91b68e9)

Thank you very much for your help resolving this.

**Comment by EricKutschera** [comment]
That command is using `--task both` (the default) which runs the prep step and the post step. I would expect the prep step with bam files to take about 1 hour for every 50 million alignments. `--nthread` can be increased up to the number of bam files to make use of additional CPUs. After the prep step is finished there should be at least 1 non-empty .rmats file in `--tmp`

The post step can take a long time if `--novelSS` is used depending on how many novel splice sites are found. You could try running without `--novelSS` first

You could also try running on a small dataset first to verify that your install of rMATS is working

**Comment by suiyue7** [comment]
Thank you for your quick answer ! I run rmats without --novelSS and it now works.
I also tried to run rmats with --novelSS and it took half a day and finished successfully.
