### ISSUE TITLE
Error in readRDS(file) :   cannot read workspace version 3 written by R 4.0.5; need R 3.5.0 or newer

### ISSUE THREAD

**Issue by danli349** [Xinglab/rmats-turbo#388]
Hello 

I have R 4.2.0 installed, 

```bash
R

R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
But when I run `./build_rmats` to build `rmats`, I got this error:

```bash
Error in readRDS(file) :   cannot read workspace version 3 written by R 4.0.5; need R 3.5.0 or newer
```

How can I solve it?
Thanks

**Comment by EricKutschera** [comment]
From this post (https://stackoverflow.com/questions/63043842/cannot-read-workspace-version-3-written-by-r-4-0-2-need-r-3-5-0-or-newer) it seems like one possibility is that `Rscript` called by `build_rmats` is not the same version as `R`: https://github.com/Xinglab/rmats-turbo/blob/v4.3.0/build_rmats#L96

Another possibility is that there is there is an `.RData` file in your directory created from an older R version

Also the R packages are optional for rMATS. You can run the build with `--no-paired-model` (and in v4.3.0 also `--no-darts-model`) to skip the R dependencies

**Comment by danli349** [comment]
@EricKutschera Thanks I delete the `.RData file` and this problem was solved.
