### ISSUE TITLE
p-values for novel splice-site predictions

### ISSUE THREAD

**Issue by fklirono** [Xinglab/rmats-turbo#39]
Hello,

I have run rMATS turbo v4.1.0 and I was wondering where can I find the p-values (and their FDR adjustments) for the novel splice-site predictions? As far as I can tell, the only predictions that have p-values are those in `*.MATS.JC.txt `which do not include the IDs of the novel splice-site predictions found in `fromGTF.novelSpliceSite.*.txt`.

Side question: on your wiki you [state](https://github.com/Xinglab/rmats-turbo#starting-with-bam-files):

> Reads can be mapped independently of rMATS with any aligner and then the resulting BAM files can be used as input to rMATS.

However on your [FAQ](http://rnaseq-mats.sourceforge.net/faq.html#5) you mention:

> Q: Can I run rMATS with STAR aligner output?
> A: STAR aligner performs soft clipping by default which will generate variable read lengths. You can run STAR with "--alignEndsType EndToEnd" option to suppress soft clipping.

So which one of the two is it? Can rMATS handle any aligner, or special care needs to be paid to soft-clipping. If that's the case shouldn't it be mentioned **in bold** somewhere?  I have already mapped upwards to 100 samples with STAR soft-clipping on. Can I just pass the `--variable-read-length` flag to rMATS and hope for the best?

Thank you!

**Comment by EricKutschera** [comment]
The `*.MATS.JC.txt` and and `*.MATS.JCEC.txt` files should contain results for all events (regular, novelJunction, and novelSpliceSite). Events may be removed during a filtering step (https://github.com/Xinglab/rmats-turbo/blob/bc29dc5202f9e18aed99fe7dfe6f95ad41579223/rmats.py#L248) before the statistical model is run which removes events which either:
1. Only have reads for the inclusion or skipping isoform, but not both
2. Only have reads for sample 1 or sample 2, but not both

You can disable the filtering step by running with `--statoff` and then you could check the `JC.raw.input*` and `JCEC.raw.input*` files to see why the events were filtered

rMATS does not require a specific aligner. It can work with BAMs with or without uniform read length. You can use `--variable-read-length` to allow rMATS to process reads of any length. A value is still needed for `--readLength` and you can use the max read length before clipping or any other reasonable value (average or median read length). `--readLength` is used for normalization in the PSI value calculation and changing `--readLength` did not have a noticeable impact in our testing

**Comment by EricKutschera** [comment]
I just realized that while rMATS can handle variable length reads, it does not handle reads with soft clipping in the CIGAR string. I think that rMATS could be adapted to ignore the clipped part of the sequence, but that will require code changes. You may be able to try the suggestions in this post to remove the soft clipping from the BAM files to get variable length reads: https://www.biostars.org/p/84452/

Sorry for the confusion

**Comment by angarb** [comment]
@EricKutschera and @fklirono, thank you for this conversation! 
So, just to clarify, if we are using STAR - we should turn off soft clipping? 
The soft clipping negatively impacts rMATS?

**Comment by fklirono** [comment]
Thanks Eric for the clarifications! Please, mention the soft-clipping issue on the github README/Wiki clearly so that others can notice it and be advised about.

On the practical side, can I hard-clip reads on the fly while running rMATS, i.e. is rMATS serially going through the BAM alignments or it needs to randomly access them? The former would be an acceptable solution which minimizes disk-usage and I get to keep the soft-clipped alignments which I prefer.

Thanks again!

**Comment by EricKutschera** [comment]
@angarb
Yes, you should turn off soft clipping. The current implementation of rMATS will ignore alignments that have clipping operations in the CIGAR string

@fklirono
rMATS uses the bamtools library to read the BAM file. rMATS only does one loop over the BAM alignments here: https://github.com/Xinglab/rmats-turbo/blob/bc29dc5202f9e18aed99fe7dfe6f95ad41579223/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L631

I'm not sure if on the fly clipping will work or not
