### ISSUE TITLE
Bioconda release

### ISSUE THREAD

**Issue by WardDeb** [Xinglab/rmats-turbo#4]
Hi,

I was wondering if a Bioconda release for 4.1.0 is planned soon ?

Kind regards,

Warddeb

**Comment by EricKutschera** [comment]
Hi Warddeb,

I am working on getting 4.1.0 into Bioconda. Here is the PR that I am still making changes to: https://github.com/bioconda/bioconda-recipes/pull/22493

Hopefully I can finish that up soon

**Comment by WardDeb** [comment]
Great, thanks for the fast work.
