### ISSUE TITLE
SE events in output table do not match to the GTF annotation

### ISSUE THREAD

**Issue by CyberGypsy6324** [Xinglab/rmats-turbo#401]
Hi rMATS team,

I have a question about the output table of skipped exon. From my understanding, "Upstream-Skipped-Downstream" is the known event in the GTF annotation file and "Upstream-Downstream" is the novel event detected by rMATS from RNA-Seq data. 

<img width="747" alt="Untitled" src="https://github.com/Xinglab/rmats-turbo/assets/138286888/b905c457-1df8-4469-918c-17c8a5cc5065">

However, I find an event in the output table of skipped exon which looks weird:

```
GeneID	geneSymbol	chr	strand	exonStart_0base	exonEnd	upstreamES	upstreamEE	downstreamES	downstreamEE
ENSG00000102181.21	CD99L2	chrX	-	150828305	150829604	150816278	150816455	150831230	150831293
```

The positon of exons is shown in the IGV:

<img width="999" alt="Screen Shot 2024-05-08 at 2 56 07 PM" src="https://github.com/Xinglab/rmats-turbo/assets/138286888/c1a93ba0-1286-47db-8a66-c2571ac77b7c">

In this detected event, the connecting of "Upstream-Skipped-Downstream" cannot be found in the GTF annotation. This makes me confused. I wonder my understanding above is not correct. Can you help me about this question? Thank you.

**Comment by EricKutschera** [comment]
rMATS can detect events where some of the exons or junctions are not annotated. The inclusion isoform (up-skip-down) and/or the skipping isoform (up-down) could have novel exons or junctions. These posts have some details:
https://github.com/Xinglab/rmats-turbo/issues/277#issuecomment-1486991997
https://github.com/Xinglab/rmats-turbo/issues/17#issuecomment-650224207

**Comment by CyberGypsy6324** [comment]
Hi Eric,

Thank you for sharing some previous answers. I'm still not quite clear about my question after reading them. I didn't enable `--novelSS` when running rMATS. The exon skipping event I mentioned above is from the output file `SE.MATS.JCEC.txt`. I expected all inclusion isoforms (up-skip-down) should exist in the GTF annotation file. However, the 3 exons involved in that event only have the isoforms 1) up-down 2) skip-down while the isoform up-skip-down doesn't exist according to the annotation.

<img width="1128" alt="Screen Shot 2024-05-10 at 11 26 42 AM" src="https://github.com/Xinglab/rmats-turbo/assets/138286888/e69a0f2f-b1e2-4f79-9e3a-b38f7a7ded59">

**Comment by EricKutschera** [comment]
It looks like all 3 exons are annotated in the GTF. rMATS can detect events with novel combinations of annotated splice sites even without `--novelSS`

https://github.com/Xinglab/rmats-turbo/tree/v4.3.0?tab=readme-ov-file#output
> fromGTF.novelJunction.[AS_Event].txt: AS events derived from novel combinations of splice sites annotated in the GTF file. Does not include events with an unannotated splice site

**Comment by CyberGypsy6324** [comment]
Hi Eric

Thank you for your explanation. Now I see why there are novel connections.

And I'm interested in the changes in protein sequence caused by the alternative splicing. For exon skipping, my original plan to extract novel protein sequences is:

1. Using the upstream, skipped, and downstream exons to identify the affected transcripts.
2. Edit the transcript sequences according to the skipping events.
3. Extract the novel protein sequences from edited transcript sequences.

Do you think this workflow is correct? Also like the case I mentioned above, when upstream, skipped, and downstream exons cannot even identify one transcript (which means the connection up-skip-down doesn't exist in the GTF annotation file), how should I know what effect SE has on the protein sequence?

**Comment by EricKutschera** [comment]
Splicing events reported by rMATS are based on reads covering individual junctions and exons. You can compare the rMATS events to annotated transcripts, but the events may not match nicely to transcripts. You could try limiting your analysis to cases where there is an annotated transcript that has all 3 exons in order
