### ISSUE TITLE
A3SS and A5SS

### ISSUE THREAD

**Issue by adeslatt** [Xinglab/rmats-turbo#404]
Hello,

I've created a repository to handle experiments for which rMATS was executed on separately, to make it easy to make a consensus set of junctions (unique union of all the samples) 

I make bed files, and translate the nucleotide sequences to open reading frames and resolve them to amino acids to sort out putative function differences between the experiments.

I have a question about A3SS and A5SS nomenclature in the resulting coordinate files structure.   From the supplemental information from the original 2011 paper - I can see that the shortES, shortEE are for the A3SS the shorter exon start and end numbers, making the A3SS spot a bit longer than the A3SS longExonStart_0base and longExonEnd - which makes the A3SS location from the 5' exon a bit shorter.  

My question is to where is the **flanking Exon** referring (**flankingES** and **flankingEE**)
*  in the case of the A3SS is it an exon 5' to it or 3' to it?  
*  Also same question for the A5SS.

Thanks in advance for your reply!

Checkout my[ post-rmats-single-run](https://github.com/adeslatt/post-rmats-single-run?tab=readme-ov-file#post-rmats-single-run) repository -- feedback welcome - working on improving it as I use it.

**Comment by EricKutschera** [comment]
For A3SS the flanking exon is at the 5' side. For A5SS the flanking exon is at the 3' side

This post has a diagram of the rMATS events with labels for the coordinates: https://github.com/Xinglab/rmats-turbo/issues/158#issuecomment-966763718

Also see this post for a discussion of how the columns depend on the strand of the event: https://groups.google.com/g/rmats-user-group/c/LWWvruwr-pg/m/jMmLmZCiBgAJ

**Comment by adeslatt** [comment]
Thanks so much -- I did manage to sort it out looking at the coordinates but this reference is very helpful --
