### ISSUE TITLE
Bioconda install v4.3.0- multiple errors

### ISSUE THREAD

**Issue by camcorey** [Xinglab/rmats-turbo#405]
HI, I installed rmats-turbo v4.3.0 and am using it in a mini-conda3 v22.11.1. My run ended with multiple errors, similar to those in past queries. What do I need to do within conda to fix this? thanks, Corey
Traceback (most recent call last):
  File "rmatspipeline/rmatspipeline.pyx", line 2799, in rmatspipeline._load_job
ValueError: invalid literal for int() with base 10: '/home/camcorey/data/Aae/output/VP2_Aligned.sortedByCoord.out.bam'
Exception ValueError: ValueError("invalid literal for int() with base 10: '/home/camcorey/data/Aae/output/VP2_Aligned.soryCoord.out.bam'",) in 'rmatspipeline._load_job' ignored
Running the statistical part.
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JC_SE/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JC_SE/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JCEC_SE/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JC_MXE/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JC_MXE/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JCEC_MXE/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JC_A3SS/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JCEC_A3SS/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JC_A5SS/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JCEC_A5SS/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JC_RI/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JC_RI/rMATS_result_FDR.txt: No such file or directory
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
IOError: [Errno 2] No such file or directory: '/tmp/tmpGkkFmM/JCEC_RI/rMATS_result_P-V.txt'
paste: /tmp/tmpGkkFmM/JCEC_RI/rMATS_result_FDR.txt: No such file or directory
The statistical part is done.
Done.

**Comment by EricKutschera** [comment]
It looks like there are two main errors:
```
Traceback (most recent call last):
File "rmatspipeline/rmatspipeline.pyx", line 2799, in rmatspipeline._load_job
ValueError: invalid literal for int() with base 10: '/home/camcorey/data/Aae/output/VP2_Aligned.sortedByCoord.out.bam'
Exception ValueError: ValueError("invalid literal for int() with base 10: '/home/camcorey/data/Aae/output/VP2_Aligned.soryCoord.out.bam'",) in 'rmatspipeline._load_job' ignored
```
and
```
/home/camcorey/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgfortran.so.3: cannpen shared object file: No such file or directory
```

The first error could be due to `--b1` or `--b2` files not having comma separated paths: https://github.com/Xinglab/rmats-turbo/issues/322

The line number for the first error doesn't match with the v4.3.0 code: `File "rmatspipeline/rmatspipeline.pyx", line 2799, in rmatspipeline._load_job`
https://github.com/Xinglab/rmats-turbo/blob/v4.3.0/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L3697

Based on the line number, it seems like you might have v4.0.2 installed. Can you verify the versions with:
`ls /home/camcorey/miniconda3/envs/rmats/conda-meta/rmats*`
`ls /home/camcorey/miniconda3/envs/rmats/conda-meta/libgfortran*`

You could try creating a new conda environment and installing with: `conda install -c conda-forge -c bioconda rmats=4.3.0`

**Comment by camcorey** [comment]
Thanks so much. The suggestions worked. FYI- the rmats conda page at https://anaconda.org/bioconda/rmats links to 4.0.2 even though it states 4.0.3 in the header.
