### ISSUE TITLE
"IJC_SAMPLE_1 SJC_SAMPLE_1 IJC_SAMPLE_2 SJC_SAMPLE_2" in the EVENT.MATS.JCEC.txt file is 0, while the value of the five columns "PValue FDR IncLevel1 IncLevel2 IncLevelDifference" five columns have a value of NA.

### ISSUE THREAD

**Issue by xiaobearxiaobear** [Xinglab/rmats-turbo#410]
i have similar question:ie: The value of the four columns "IJC_SAMPLE_1 SJC_SAMPLE_1 IJC_SAMPLE_2 SJC_SAMPLE_2" in the EVENT.MATS.JCEC.txt file is 0, while the value of the five columns "PValue FDR IncLevel1 IncLevel2 IncLevelDifference" five columns have a value of NA.
here is my report of the results given at the end of running the command
$ python3 /public/home/xiaoming/miniconda3/envs/myenvname/bin/rmats.py --b1 b1.txt --b2 b2.txt --gtf /public/home/xiaoming/hTSC_STB96_RNA_seq/hTSC_STB96_rMATs/hTSC_STB24/GCF_000001405_40_GRCh38_p14_genomic.gtf -t paired --libType fr-unstranded --readLength 100 --nthread 4 --od AS --tmp AS --variable-read-length --statoff
gtf: 110.33750867843628
There are 50006 distinct gene ID in the gtf file
There are 200905 distinct transcript ID in the gtf file
There are 24989 one-transcript genes in the gtf file
There are 2298165 exons in the gtf file
There are 10649 one-exon transcripts in the gtf file
There are 4969 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 4.017618
Average number of exons per transcript is 11.439063
Average number of exons per transcript excluding one-exon tx is 12.023358
Average number of gene per geneGroup is 8.155996
statistic: 0.07963252067565918

read outcome totals across all BAMs
USED: 575925120
NOT_PAIRED: 6175140
NOT_NH_1: 381853089
NOT_EXPECTED_CIGAR: 6831273
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 23086919
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 979511
CLIPPED: 68565642
total: 1063416694
outcomes by BAM written to: AS/2024-06-14-23_18_12_994584_read_outcomes_by_bam.txt

novel: 1732.8452179431915
The splicing graph and candidate read have been saved into AS/2024-06-14-23_18_12_994584_*.rmats
save: 11.968095302581787
loadsg: 0.5375621318817139

==========
Done processing each gene from dictionary to compile AS events
Found 89609 exon skipping events
Found 18301 exon MX events
Found 34574 alt SS events
There are 17338 alt 3 SS events and 17236 alt 5 SS events.
Found 6597 RI events
ase: 2.233708381652832
count: 21.929344415664673
Processing count files.
Done processing count files.

**Comment by EricKutschera** [comment]
(also posted at https://github.com/Xinglab/rmats-turbo/issues/376)

Since you ran with `--statoff` all detected events will be kept in the final output files, even if there are no supporting reads. Are those columns 0 or NA for every row in your output files or just a lot of the rows? Having 0 or NA values is expected for some rows when run with --statoff since events can be detected directly from the --gtf without supporting alignments

The read outcomes look fine with about 575 million reads USED

**Comment by xiaobearxiaobear** [comment]
when i remove the ----statoff, another question appear.
here is my report of the results given at the end of running the command.
(myenvname) [zhangman@admin1 hTSC_STB24]$ python3 /public/home/zhangman/miniconda3/envs/myenvname/bin/rmats.py --b1 b1.txt --b2 b2.txt --gtf /public/home/zhangman/hTSC_STB96_RNA_seq/hTSC_STB96_rMATs/hTSC_STB24/GCF_000001405_40_GRCh38_p14_genomic.gtf -t paired --libType fr-unstranded --readLength 100 --nthread 4 --od AS_nostatoff --tmp AS_nostatoff --variable-read-length
gtf: 175.6603581905365
There are 50006 distinct gene ID in the gtf file
There are 200905 distinct transcript ID in the gtf file
There are 24989 one-transcript genes in the gtf file
There are 2298165 exons in the gtf file
There are 10649 one-exon transcripts in the gtf file
There are 4969 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 4.017618
Average number of exons per transcript is 11.439063
Average number of exons per transcript excluding one-exon tx is 12.023358
Average number of gene per geneGroup is 8.155996
statistic: 0.028829097747802734

read outcome totals across all BAMs
USED: 575925120
NOT_PAIRED: 6175140
NOT_NH_1: 381853089
NOT_EXPECTED_CIGAR: 6831273
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 23086919
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 979511
CLIPPED: 68565642
total: 1063416694
outcomes by BAM written to: AS_nostatoff/2024-06-15-20_15_59_083606_read_outcomes_by_bam.txt

novel: 1741.9771091938019
The splicing graph and candidate read have been saved into AS_nostatoff/2024-06-15-20_15_59_083606_*.rmats
save: 5.01044225692749
loadsg: 0.8946847915649414

==========
Done processing each gene from dictionary to compile AS events
Found 89609 exon skipping events
Found 18301 exon MX events
Found 34574 alt SS events
There are 17338 alt 3 SS events and 17236 alt 5 SS events.
Found 6597 RI events
==========

ase: 1.9986369609832764
count: 29.488370656967163
Processing count files.
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JC_SE/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JCEC_SE/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JC_MXE/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JCEC_MXE/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JC_A3SS/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JCEC_A3SS/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JC_A5SS/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JCEC_A5SS/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JC_RI/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JC_RI/rMATS_result_FDR.txt: No such file or directory
/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
          ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AS_nostatoff/tmp/JCEC_RI/rMATS_result_P-V.txt'
paste: AS_nostatoff/tmp/JCEC_RI/rMATS_result_FDR.txt: No such file or directory
Done processing count files.

so I should be how to solve below?

**Comment by EricKutschera** [comment]
This is the main error: `/public/home/zhangman/miniconda3/envs/myenvname/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory`

It looks like you installed rMATS from conda. The conda-forge version of gsl is needed for the conda install to work and you may not have had conda configiured for conda-forge when you installed rMATS. See this post: https://github.com/Xinglab/rmats-turbo/issues/281
