### ISSUE TITLE
rMATS long runtime

### ISSUE THREAD

**Issue by kairitanaka** [Xinglab/rmats-turbo#413]
Would appreciate any sort of guidance as I'm a bit new to this. I read through the paper and my process should be similar to procedure 1. Currently using bam files from TCGA. My GTF file is from gencode called gencode.v38.annotation.gtf. I'm looking at two groups which is either positive or negative for a SNP that could lead to affects in splicing for a specific gene. 

**Command I ran to install**
conda install -c conda-forge -c bioconda rmats

**Packages in enviornment**
 packages in environment at /cellar/users/ktanaka/miniconda3/envs/rmats_env:
 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.6.2             hbcca054_0    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
htslib                    1.20                 h5efdd21_1    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libcurl                   8.8.0                hca28451_0    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0              h77fa898_11    conda-forge
libgfortran-ng            13.2.0              h69a702a_11    conda-forge
libgfortran5              13.2.0              h3d2ce59_11    conda-forge
libgomp                   13.2.0              h77fa898_11    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0              hc0a3c3a_11    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
numpy                     1.26.4          py310hb13e2d6_0    conda-forge
openssl                   3.3.1                h4ab18f5_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
python                    3.10.14         hd12c33a_0_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
readline                  8.2                  h8228510_1    conda-forge
rmats                     4.3.0           py310h1918981_2    bioconda
rmats2sashimiplot         3.0.0                    pypi_0    pypi
setuptools                70.1.0             pyhd8ed1ab_0    conda-forge
star                      2.7.11b              h43eeafb_1    bioconda
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

**Command Run**
GTF_FILE="/cellar/users/ktanaka/references/gencode.v38.annotation.gtf"
B1_FILE="/cellar/users/ktanaka/positive_bam_files_comma.txt"
B2_FILE="/cellar/users/ktanaka/negative_bam_files_comma.txt"
OUTPUT_DIR="/cellar/users/ktanaka/SNP_rmats/post"
TMP_DIR="/cellar/users/ktanaka/SNP_rmats/prep"

rmats.py --gtf $GTF_FILE \
         --tmp $TMP_DIR \
         --od $OUTPUT_DIR \
         --readLength 48 \
         --b1 $B1_FILE \
         --b2 $B2_FILE \
         -t single \
         --anchorLength 1 \
         --nthread 1 \
         --libType fr-unstranded \
         --task both \
         --variable-read-length \
         --novelSS
(looked at the paper) 

which resulted in over 12 hours of this running with one empty file in my prep directory.
(rmats_env) [ktanaka@nrnb-login-01 prep]$ ll
total 1
-rw-rw-r-- 1 ktanaka carter-users 0 Jun 22 02:11 2024-06-22-02_11_14_491730_0.rmats

I looked at the trouble shooting in the paper but I believe that TCGA does not have any clipping as well. 
I'm pretty confident that the read lengths should be 48 as I've ran

(rmats_env) [ktanaka@nrnb-login-01 all_full_bams]$ samtools view fe036511-fe82-467c-9c6e-59bfb8b0a329.rna_seq.genomic.gdc_realn.bam | awk '{print length($10)}' | head -1000 | sort -u
48
(rmats_env) [ktanaka@nrnb-login-01 all_full_bams]$ samtools view fac69f81-0d8c-40a0-8263-b54d5f06d7b3.rna_seq.genomic.gdc_realn.bam | awk '{print length($10)}' | head -1000 | sort -u
48

on multiple bam files. 

Did I setup wrong? 
Thanks!

**Comment by EricKutschera** [comment]
`--novelSS` can cause rMATS to take a long time depending on the dataset. Having a lot of bam files or large bam files can also lead to a long runtime

Since `2024-06-22-02_11_14_491730_0.rmats` was empty, the command didn't finish the prep step. I would expect the prep step with a single thread to take about 30 minutes to 1 hour per 100M reads. The prep step can use up to one CPU per input bam file: https://github.com/Xinglab/rmats-turbo/issues/129#issuecomment-861488461

However you're running with `--nthread 1` and `--task both` so everything is being done on a single thread. Depending on the bam files in `--b1` and `--b2`, taking 12 hours or more may be expected

**Comment by kairitanaka** [comment]
ah sounds good
Will try and let it run for a bit and maybe up the number of threads
Thanks for the feedback!
