### ISSUE TITLE
What to do when samples have different read lengths

### ISSUE THREAD

**Issue by tjbencomo** [Xinglab/rmats-turbo#416]
Hi,

I am trying to run rMATS on a set of samples from two different studies. Because samples are from different studies, the samples from one study have a different read length than those of the other study (100bp vs 300bp). In the prep step I can set the read length individually for each sample, but only one read length value can be specified in the post step.

How do you suggest handling samples with different read lengths? Would setting the read length to the smaller value for all samples be OK or would that cause major problems?

**Comment by EricKutschera** [comment]
I would recommend using the average length in the post step, but using the smaller value is probably also fine. I think the rMATS results should not change very much and you could try multiple values to check. Here's a related post: https://github.com/Xinglab/rmats-turbo/issues/83#issuecomment-766845772

**Comment by tjbencomo** [comment]
Thanks for the help!
