### ISSUE TITLE
Which Aligner Does rMATS Use?

### ISSUE THREAD

**Issue by malbahrani** [Xinglab/rmats-turbo#43]
Hi,

I noticed probably since rMATS version 3.x you started supporting FASTAQ as inputs.  I was wondering which aligner does rMATS use under the hood in the latest version? Is it STAR?

I tried looking up this information in your Docs and FAQs, but I was not sure.

Thanks!

**Comment by EricKutschera** [comment]
rMATS uses STAR: https://github.com/Xinglab/rmats-turbo/blob/master/rmats.py#L62
