### ISSUE TITLE
characterisation of SE events detected from rMATS turbo

### ISSUE THREAD

**Issue by rezarahman12** [Xinglab/rmats-turbo#439]
Hi rMATS team,

My question here is not about rMATS turbo, rather, I will appreciate if you kindly suggest way of characterisation of skipped exons identified through rMATS-turbo.

I would like to know how many of the skipped exons suggested by rMATS-turbo are either CDS or 5'/3' UTR. Could you please suggest a bioinformatics way of doing that.

I appreciate your time very much.

Best regards
Reza

**Comment by EricKutschera** [comment]
The GENCODE annotation files like https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.annotation.gtf.gz have rows with CDS or UTR as the 3rd column (feature). An example line is:
```
chr1	HAVANA	CDS	65565	65573	.	+	0	gene_id "ENSG00000186092.7"; transcript_id "ENST00000641515.2"; gene_type "protein_coding"; gene_name "OR4F5"; transcript_type "protein_coding"; transcript_name "OR4F5-201"; exon_number 2; exon_id "ENSE00003813641.1"; level 2; protein_id "ENSP00000493376.2"; hgnc_id "HGNC:14825"; tag "RNA_Seq_supported_partial"; tag "basic"; tag "Ensembl_canonical"; tag "GENCODE_Primary"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; ccdsid "CCDS30547.2"; havana_gene "OTTHUMG00000001094.4"; havana_transcript "OTTHUMT00000003223.4";
```

You could find all the CDS and UTR coordinates from the gtf file and then check the exons against those coordinates. Maybe `bedtools intersect` could be useful: https://bedtools.readthedocs.io/en/latest/index.html

**Comment by rezarahman12** [comment]
Thanks a lot, Eric! Appreciate it
