### ISSUE TITLE
Conflict Between STAR Reports and rMATS Output 

### ISSUE THREAD

**Issue by FarzanehRah** [Xinglab/rmats-turbo#446]
Hi,
I am experiencing an issue with 3 of my 5 BAM files where the **USED** value is 0, and the majority of reads are classified as **NOT_NH_1**, which is associated with multimapped reads. However, the STAR report indicates that the uniquely mapped reads are as follows: 87.36%, 86.15%, 86.24%.
How can I resolve this issue? Any guidance would be greatly appreciated!

Thank you!

```
CTRL1_mapped.bam
USED: 132682255
NOT_PAIRED: 12981260
NOT_NH_1: 26848920
NOT_EXPECTED_CIGAR: 1708071
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 4826799
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 182950
CLIPPED: 17371961
TOTAL_FOR_BAM: 196602216
CTRL2_mapped.bam
USED: 134358958
NOT_PAIRED: 12138462
NOT_NH_1: 26118428
NOT_EXPECTED_CIGAR: 1549425
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 4869843
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 215746
CLIPPED: 17154630
TOTAL_FOR_BAM: 196405492
CTRL3_mapped.bam
USED: 0
NOT_PAIRED: 11750440
NOT_NH_1: 173390230
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 17465936
TOTAL_FOR_BAM: 202606606
M1_mapped.bam
USED: 0
NOT_PAIRED: 12162292
NOT_NH_1: 168371709
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 18283817
TOTAL_FOR_BAM: 198817818
M2_mapped.bam
USED: 0
NOT_PAIRED: 11358034
NOT_NH_1: 151879456
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 16023660
TOTAL_FOR_BAM: 179261150
```
![image](https://github.com/user-attachments/assets/f1f96472-3bd0-48c0-93c1-32dca845f36e)

![image](https://github.com/user-attachments/assets/ec54316b-454a-4f55-bd0f-f628b5ddcb14)

![image](https://github.com/user-attachments/assets/dd75cfb9-4019-45d4-8ae6-574d34563a83)

![image](https://github.com/user-attachments/assets/034446c3-232c-4f57-955c-cfcf1b229249)

![image](https://github.com/user-attachments/assets/b20a87fb-fc9e-4e8a-a7c7-908fac42b7a7)

**Comment by EricKutschera** [comment]
If you check a few lines of the BAM files where the reads are being filtered by rMATS do you see the `NH:i` attribute? It could be that the STAR command used to create those BAM files set `--outSAMattributes` so that the NH attribute wasn't included

Also, the way that rMATS reports the number of multimapped reads is different than how STAR reports it: https://github.com/Xinglab/rmats-turbo/issues/122#issuecomment-848966334

**Comment by FarzanehRah** [comment]
Thank you so much! I received the BAM files for running rMATS. I checked the BAM files, BAM files with zero USED reads show no attributes. 
Thanks again for your help and prompt reply!

![image (1)](https://github.com/user-attachments/assets/cf2daae2-a16e-4a5f-9d27-6af243476364)

![image](https://github.com/user-attachments/assets/3baa5c36-13c1-494e-b24a-2ef08dd08b4f)
