### ISSUE TITLE
Result from JC or JCEC

### ISSUE THREAD

**Issue by wyzhangMPI** [Xinglab/rmats-turbo#45]
Hi,
    I am using rMATs to compute the differentially AS events between two groups of RNA-seq data. Regarding to the AS events with statistical FDR values, I got two types of files: [AS_Event].MATS.JC.txt and [AS_Event].MATS.JCEC.txt. These two files differ both in the numbers of detected AS events, as well as the FDR values for the same event. Which file should I use for the downstream analysis?
   Additionally, I also plan to detect splicing QTLs, as the matched genomic sequencing data is also available. I would prefer to use the PSI  (percent of splicing index) value as the phenotype for each AS event, and my question is where can I get the PSI values from the rMATs output?
   Thanks and have a nice day!

Best wishes,
Wenyu Zhang

**Comment by EricKutschera** [comment]
The JC files only consider "junction counts" while the JCEC files consider both "junction counts" and "exon counts". There is a diagram in the README that shows for each event type which reads are junction reads and which are exon reads: https://github.com/Xinglab/rmats-turbo#output

The JC files are more strict in that they only count the junction reads which provide better evidence to support the event. The JCEC files include the additional exon count data which may result in more significant events from the statistical analysis. Whether you want to use JC or JCEC is up to you

The PSI value for each replicate is reported in the MATS files in the columns IncLevel1 and IncLevel2. It is calculated from the other columns as: (IJC_SAMPLE_1/IncFormLen) / ((IJC_SAMPLE_1/IncFormLen) + (SJC_SAMPLE_1/SkipFormLen))

**Comment by wyzhangMPI** [comment]
> E_1

Thanks! it is now clear to me.
