### ISSUE TITLE
JC and JCEC counts are the same

### ISSUE THREAD

**Issue by JonEilers** [Xinglab/rmats-turbo#451]
Hi,
I am scratching my head at the results I am getting from running rmats on some smart-seq2 snRNA-seq data. I expect the JC and JCEC counts to be slightly different, but so far everything I have tried results in the two columns being identical. Any suggestions or insights would be greatly appreciated. 
Thanks
Jon

```bash
rmats.py \
    --b1 AD_cases.b1 \
    --b2 nonAD_cases.b2 \
    --gtf Homo_sapiens.GRCh38.112.gtf \
    --od wClip.GRCh38.112.output \
    --tmp wClip.GRCh38.112.tmp \
    -t single \
    --allow-clipping \
    --readLength 40 \
    --variable-read-length \
    --nthread 24 \
    --statoff
```

| | | | | | | | | | |
|-|-|-|-|-|-|-|-|-|-|
|EventType|EventTypeDescription|TotalEventsJC|TotalEventsJCEC|SignificantEventsJC|SigEventsJCSample1HigherInclusion|SigEventsJCSample2HigherInclusion|SignificantEventsJCEC|SigEventsJCECSample1HigherInclusion|SigEventsJCECSample2HigherInclusion|
|SE|skipped exon|59078|59078|0|0|0|0|0|0|
|A5SS|alternative 5' splice sites|8848|8848|0|0|0|0|0|0|
|A3SS|alternative 3' splice sites|13623|13623|0|0|0|0|0|0|
|MXE|mutually exclusive exons|4727|4727|0|0|0|0|0|0|
|RI|retained intron|9859|9859|0|0|0|0|0|0|

```bash
gtf: 24.20939612388611
There are 63140 distinct gene ID in the gtf file
There are 254129 distinct transcript ID in the gtf file
There are 39366 one-transcript genes in the gtf file
There are 1668828 exons in the gtf file
There are 26152 one-exon transcripts in the gtf file
There are 23777 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 4.024850
Average number of exons per transcript is 6.566854
Average number of exons per transcript excluding one-exon tx is 7.205446
Average number of gene per geneGroup is 8.705872
statistic: 0.030899763107299805

read outcome totals across all BAMs
USED: 1533638
NOT_PAIRED: 0
NOT_NH_1: 8443595
NOT_EXPECTED_CIGAR: 22284
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 1610984
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 416001
CLIPPED: 0
total: 12026502
outcomes by BAM written to: /mnt/data1/home/jon/marvel_pipeline/test_run/rmats/rMATS/wClip.GRCh38.112.tmp/2024-11-14-11_51_34_574045_read_outcomes_by_bam.txt

novel: 1260.9347653388977
The splicing graph and candidate read have been saved into /mnt/data1/home/jon/marvel_pipeline/test_run/rmats/rMATS/wClip.GRCh38.112.tmp/2024-11-14-11_51_34_574045_*.rmats
save: 0.1422741413116455
loadsg: 0.002064228057861328

==========
Done processing each gene from dictionary to compile AS events
Found 59078 exon skipping events
Found 4727 exon MX events
Found 22471 alt SS events
There are 13623 alt 3 SS events and 8848 alt 5 SS events.
Found 9859 RI events
==========

ase: 2.157892942428589
count: 1.3568360805511475
Processing count files.
Done processing count files.
```

**Comment by EricKutschera** [comment]
Since you ran with `--statoff` there is no filtering of events. In that case the total events reported in the summary file will be the same for JC and JCEC: https://github.com/Xinglab/rmats-turbo/issues/374#issuecomment-2007811836

If you look at the output files like SE.MATS.JC.txt and SE.MATS.JCEC.txt then you might see some difference in the columns like `IJC_SAMPLE_1` since the JCEC file can include reads without a splice junction in  those counts

Also only about 13% of your alignments were `USED` and 70% were `NOT_NH_1` and 13% were `EXON_NOT_MATCHED_TO_ANNOTATION`. If your reads are `--readLength 40` then the large amount of multimapping (`NOT_NH_1`) may be expected

**Comment by JonEilers** [comment]
Thanks!
