### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by yz201906** [Xinglab/rmats-turbo#46]
I have tried all options but none works. Building from master or the release source code gives exact this output with or without the CXXFLAGS option:
![image](https://user-images.githubusercontent.com/37310711/92665617-012e7880-f2d5-11ea-8c32-48a6e8a957dd.png)

**Comment by EricKutschera** [comment]
In the first few lines of the screenshot that you posted there is: `/bin/bash: cmake: command not found`

Without cmake, the bamtools part of the build fails which leads to the error at the bottom of the screenshot

**Comment by yz201906** [comment]
Hi, I am sorry, I thought I had installed all the dependencies but apparently still missing `cmake`.  It should work now. Sorry about the confusion
