### ISSUE TITLE
Questions for parameter "cstat"

### ISSUE THREAD

**Issue by thereallda** [Xinglab/rmats-turbo#47]
Hi,

Currently, I want to output all the detected splicing events by changing the "cstat" to zero, so there will be no cutoff for splicing difference. However, the results are little bit werid by changing "cstat". 

The following commands both output the same results.
`python .../rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rmats.py --b1 ctrl.txt --b2 sh1.txt --od as1_v3 -t paired --readLength 150 --cstat 0.001 --libType fr-unstranded --nthread 16 --gtf .../genomes/rat/star/Rattus_norvegicus.Rnor_6.0.96.chr.gtf`

`python .../rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rmats.py --b1 ctrl.txt --b2 sh1.txt --od as1_v4 -t paired --readLength 150 --cstat 0 --libType fr-unstranded --nthread 16 --gtf .../genomes/rat/star/Rattus_norvegicus.Rnor_6.0.96.chr.gtf`

`python .../rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rmats.py --b1 ctrl.txt --b2 sh1.txt --od as1_v5 -t paired --readLength 150 --cstat 0.1 --libType fr-unstranded --nthread 16 --gtf .../genomes/rat/star/Rattus_norvegicus.Rnor_6.0.96.chr.gtf`

> There are 32623 distinct gene ID in the gtf file      
There are 40808 distinct transcript ID in the gtf file
There are 27245 one-transcript genes in the gtf file
There are 310574 exons in the gtf file
There are 9929 one-exon transcripts in the gtf file
There are 9599 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.250897
Average number of exons per transcript is 7.610616
Average number of exons per transcript excluding one-exon tx is 9.736229
Average number of gene per geneGroup is 4.035672
>
>Done processing each gene from dictionary to compile AS events
Found 11343 exon skipping events
Found 998 exon MX events
Found 688 alt SS events
There are 418 alt 3 SS events and 270 alt 5 SS events.
Found 420 RI events
>
>Running the statistical part.
The statistical part is done.
Done.

> $cat ctrl.txt 
R19021274-ZNY-1.sorted.bam,R19021274-ZNY-4.sorted.bam,R19021274-ZNY-7.sorted.bam,R19021274-ZNY-10.sorted.bam
>$cat sh1.txt 
#R19021274-ZNY-2.sorted.bam,R19021274-ZNY-5.sorted.bam,R19021274-ZNY-8.sorted.bam,R19021274-ZNY-11.sorted.bam

 I don't know if I understand this issue correctly, so any help would be appreciated.

Thanks!

**Comment by EricKutschera** [comment]
cstat is the cutoff used in the null hypothesis test for differential splicing. It will only impact the PValue and FDR columns in the output files. cstat does not change the number of detected events. cstat changes the significance level that rmats reports. With cstat=0 you may find events with very small IncLevelDifference that have a small (significant) PValue, but when you increase to cstat=0.1 the PValue should be close to 1.0 for those events with very small IncLevelDifference.

The lines in the output like: "Found 11343 exon skipping events" only indicate that rmats is aware of the exons and junctions that define those events. The .MATS output files will not include all of those events. There must be some evidence (reads) from the BAM files supporting an event for it to end up in the .MATS file. The fromGTF.[AS_Event].txt files have all the event definitions, including those that did not have enough evidence to make it to the .MATS files

**Comment by thereallda** [comment]
Thanks Eric! Your prompt reply really help me sort this out.
