### ISSUE TITLE
Input fastqs from multiple lanes

### ISSUE THREAD

**Issue by merckey** [Xinglab/rmats-turbo#48]
Hi, 
I'm using rmats-turbo for splicing events detection and quite new to it. I'm compare 2 samples without replicate. However, for each sample, there are fastq.gz files sequenced from 2 lanes. Do I need to merge reads from multiple lane together before I run rmats or I can simply create the text file like this? Will rmats-turbo use the correct algorithm for the no-replicates samples?

sample_A.txt
```
sample_A_lane1_R1.fq.gz:sample_A_lane1_R2.fq.gz,sample_A_lane2_R1.fq.gz:sample_A_lane2_R2.fq.gz
```

sample_B.txt
```
sample_B_lane1_R1.fq.gz:sample_B_lane1_R2.fq.gz,sample_B_lane2_R1.fq.gz:sample_B_lane2_R2.fq.gz
```

Best,

JL

**Comment by EricKutschera** [comment]
If you provide rmats-turbo with the sample_A.txt and sample_B.txt files you described above then rmats-turbo will consider each lane as a replicate

If you merge the reads from multiple lanes together then rmats-turbo will not consider the different lanes as replicates in its statistical model. If that is what you want then you could merge each lane1/lane2 pair of files and your sample_A.txt and sampleB.txt would each have one `:` separated R1 R2 pair

**Comment by merckey** [comment]
Thank for you the clarification!
Merging them together is what I need.
