### ISSUE TITLE
Reads or fragments

### ISSUE THREAD

**Issue by lkmklsmn** [Xinglab/rmats-turbo#51]
Hi,

Great tool!

I was trying to find out how rMATS is handling paired-end RNAseq data. Is each read treated separately or are the counts somehow combined per fragment?

**Comment by EricKutschera** [comment]
rMATS will count each end of the pair separately. The only special handling rMATS does for paired reads is that when rMATS is run with `-t paired` (the default) it will check that the read "IsProperPair"
https://github.com/Xinglab/rmats-turbo/blob/8520f7df122b1690efbf836ec3ce63512a0cbd27/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L273
From the SAM specification, the proper pair flag means: "each segment properly aligned according to the aligner" https://samtools.github.io/hts-specs/SAMv1.pdf
So as long as both ends of the pair are properly aligned, rMATS will treat each end separately

**Comment by lkmklsmn** [comment]
Thanks for the quick response. This clears up my question!
