### ISSUE TITLE
summary.txt

### ISSUE THREAD

**Issue by jingjiai** [Xinglab/rmats-turbo#56]
Hi,
I have get a summary.txt, but I have a question about it.
I want to know whether the result only calculates the number of inclusion exon, even if it is a SE event. 
But in my opinion, SE should calculate the exclusion exon.
So houw to understand it?
<img width="184" alt="figure" src="https://user-images.githubusercontent.com/73580177/97782493-bd693880-1bcc-11eb-9227-3226089d8b63.png">

**Comment by EricKutschera** [comment]
I'm not sure that I understand your question. Are you asking about how the summary.txt is calculated? This is the code for generating that file: https://github.com/Xinglab/rmats-turbo/blob/master/rMATS_P/summary.py

Or is your question about the definition for the inclusion and skipping isoforms for the different event types? In the "Output" section of the README it says that for SE "The inclusion form includes the target exon"
