### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by chaoyanggu** [Xinglab/rmats-turbo#62]
When I run rmats.py, an error appeared as follows:
 line 1: 2784173 Segmentation fault      (core dumped)  , but the core file cannot be generated; I don’t know why； The python version  I used is 2.7.13, 
the code is 
python /software/rmats-turbo/rmats.py --b1 MV411-C.txt --b2 MV411-T.txt --gtf  ref_annot.gtf -t paired --readLength 120 --nthread 4 --od ./output --tmp ./tmp_output

Is there anything else that needs to be set or modified? thanks very  much .

**Comment by EricKutschera** [comment]
Your command seems reasonable to me. You could try running under gdb to get more info about the error

`gdb python`
then at the gdb prompt use `r` (for run) and your command
`r /software/rmats-turbo/rmats.py --b1 MV411-C.txt --b2 MV411-T.txt --gtf ref_annot.gtf -t paired --readLength 120 --nthread 4 --od ./output --tmp ./tmp_output`

If it segfaults while in gdb you should see a more helpful error message. You can then run `bt` (for back trace) to get more details

**Comment by chaoyanggu** [comment]
ok，thank you.

**Comment by ShenTTT** [comment]
I also got the same error, did you fix it?
