### ISSUE TITLE
final outputs

### ISSUE THREAD

**Issue by wangjiawen2013** [Xinglab/rmats-turbo#63]
Dear,
According to rMATS document, --od contains the final output files from the post step:
[AS_Event].MATS.JC.txt: Final output including only reads that span junctions defined by rmats (Junction Counts)
[AS_Event].MATS.JCEC.txt: Final output including both reads that span junctions defined by rmats (Junction Counts) and reads that do not cross an exon boundary (Exon Counts)
.....
There are so many outputs that I am confused, which file should I use to identify the significant alternative splicing events ?  There were no replicates in my experiment, so are the FDR and p-value still meaningful ?

**Comment by EricKutschera** [comment]
You can use either [AS_Event].MATS.JC.txt or [AS_Event].MATS.JCEC.txt. Here's an answer to a previous question about the difference between those two: https://github.com/Xinglab/rmats-turbo/issues/45#issuecomment-688843471

Even if group 1 only contains a single replicate and group 2 contains only a single replicate the FDR and p-value are still meaningful. Additional replicates are not necessary. As long as there are two groups to compare then rMATS can produce meaningful FDR and p-value results
