### ISSUE TITLE
why get the different results when use python of different versions(all the same  parameter)

### ISSUE THREAD

**Issue by wlchen1** [Xinglab/rmats-turbo#66]

**Comment by wlchen1** [comment]
①
gtf: 2.8210999965667725
There are 20180 distinct gene ID in the gtf file
There are 20180 distinct transcript ID in the gtf file
There are 20180 one-transcript genes in the gtf file
There are 193766 exons in the gtf file
There are 1866 one-exon transcripts in the gtf file
There are 1866 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.000000
Average number of exons per transcript is 9.601883
Average number of exons per transcript excluding one-exon tx is 10.478323
Average number of gene per geneGroup is 9.968069
statistic: 0.00513768196105957
novel: 6780.5988001823425
The splicing graph and candidate read have been saved into /home/rmats_tmp_output/2020-12-04-01:51:00_750239.rmats
save: 291.3525137901306
loadsg: 1.8705708980560303

==========
Done processing each gene from dictionary to compile AS events
Found 101628 exon skipping events
Found 33031 exon MX events
Found 112917 alt SS events
There are 70911 alt 3 SS events and 42006 alt 5 SS events.
Found 16840 RI events
==========

ase: 9.065913915634155
count: 190.3296229839325
Processing count files.
Done processing count files.
②
gtf: 2.239166498184204
There are 20180 distinct gene ID in the gtf file
There are 20180 distinct transcript ID in the gtf file
There are 20180 one-transcript genes in the gtf file
There are 193766 exons in the gtf file
There are 1866 one-exon transcripts in the gtf file
There are 1866 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.000000
Average number of exons per transcript is 9.601883
Average number of exons per transcript excluding one-exon tx is 10.478323
Average number of gene per geneGroup is 9.968069
statistic: 0.004263639450073242
novel: 5165.130467891693
The splicing graph and candidate read have been saved into /home/rmats_tmp_output/2020-12-05-23:33:17_400227.rmats
save: 267.5274648666382
WARNING: there are redundant temporary files.
loadsg: 3.0763745307922363

==========
Done processing each gene from dictionary to compile AS events
Found 33546 exon skipping events
Found 5349 exon MX events
Found 38795 alt SS events
There are 23990 alt 3 SS events and 14805 alt 5 SS events.
Found 6803 RI events
==========

ase: 2.4995596408843994
count: 316.83789014816284
Processing count files.
Done processing count files.

**Comment by EricKutschera** [comment]
It looks like you are reusing the same `--tmp` directory from the first run. The output message shows:
`The splicing graph and candidate read have been saved into /home/rmats_tmp_output/2020-12-04-01:51:00_750239.rmats`
and then `{...} saved into /home/rmats_tmp_output/2020-12-05-23:33:17_400227.rmats`

The second run also has this message: `WARNING: there are redundant temporary files.` I think that rmats found the old files from the previous run, and those files prevented rmats from successfully processing some of the data. If you run again, but using a unique `--tmp` argument for each run you may get results that match between python versions

**Comment by wlchen1** [comment]
ok, Thanks for your help.

**Comment by Dazhuangafei** [comment]
hello! I have the same question. Although I delete the --tmp directory or using a new  --tmp directory, it's always the result 

./run_rmats --b1 /path/software/testData/b1.txt --b2 /path/software/testData/b1.txt  --gtf /path/software/testData/Homo_sapiens.GRCh38.99.gtf -t paired --readLength 50 --variable-read-length --nthread 4 --od /path/software/bam2 --tmp /path/software/bam1
gtf: 33.60717272758484
There are 60676 distinct gene ID in the gtf file
There are 227818 distinct transcript ID in the gtf file
There are 36763 one-transcript genes in the gtf file
There are 1376499 exons in the gtf file
There are 25269 one-exon transcripts in the gtf file
There are 22508 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.754664
Average number of exons per transcript is 6.042099
Average number of exons per transcript excluding one-exon tx is 6.671126
Average number of gene per geneGroup is 8.463790
statistic: 0.028331279754638672
novel: 0.35172033309936523
The splicing graph and candidate read have been saved into /path/software/bam1/2023-03-10-17:41:18_951764.rmats
save: 0.17890334129333496
WARNING: there are redundant temporary files.
loadsg: 0.0016570091247558594

==========
Done processing each gene from dictionary to compile AS events
Found 49159 exon skipping events
Found 3392 exon MX events
Found 16615 alt SS events
There are 10094 alt 3 SS events and 6521 alt 5 SS events.
Found 6994 RI events
==========

ase: 3.3003063201904297
count: 0.8210811614990234
Processing count files.
Done processing count files.

If you have any suggestion,  I will be very grateful !
