### ISSUE TITLE
"fastq.gz" not recognized. "fastq" was.

### ISSUE THREAD

**Issue by scottaroony** [Xinglab/rmats-turbo#72]
Hi, 

Just installed  rmats-turbo yesterday and have been getting an error when trying to run it using compressed fastq.gz files.

Returns an error "status 104" along with "ReadAlignChunk_processChunks.cpp:177:processChunks EXITING because of FATAL ERROR in input reads: unknown file format: the read ID should start with @ or > "

I decompressed the fastq.gz files and now the code appears to be running fine.

I can give more details if needed but I'm guessing this is something simple?

Scott.

**Comment by EricKutschera** [comment]
Support for fastq.gz input files was added in this PR (https://github.com/Xinglab/rmats-turbo/pull/19) which was merged after the 4.1.0 release. If you built rmats from the original 4.1.0 source code then I would not expect fastq.gz files to work. You could try making the 2 line change from that PR to the rmats.py that you are using, or you could try building from the latest commit on the master branch

**Comment by scottaroony** [comment]
yep, 4.1.0. Thanks for the info. It's working with unzipped so I won't tempt fate and change anything. I'm not using a lot of data at this stage.
Thanks.
