### ISSUE TITLE
Build issue on linux

### ISSUE THREAD

**Issue by bio-scott** [Xinglab/rmats-turbo#76]
Hi,

I downloaded rmats_turbo_v4_1_0.tar, extracted it, and I'm trying to build with:
`./build_rmats --conda`

when building, this error is returned (trimmed to what should be the relevant portion):
```
# gfortran -c lbfgs_scipy/routines.f -o lbfgs_scipy/lbfgsb.o linpack.o blas.o timer.o
gcc -I/usr/include -Wall -O2 -msse2 -funroll-loops -fopenmp -o rMATSexe src/main.c src/myfunc.c src/util.c src/cthreadpool.c lbfgs_scipy/lbfgsb.o lbfgs_scipy/linpack.o lbfgs_scipy/timer.o -lgsl -lgslcblas -lm -lm -lgfortran -lgsl -lgslcblas -lgomp -lblas -llapack
```
... (some warnings)
```
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -llapack
collect2: error: ld returned 1 exit status
make[1]: *** [rMATSexe] Error 1
```

blas and lapack are already installed
i.e. 
```
$ conda install blas
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

Installing via `yum install lapack-devel blas-devel` (as listed in instructions for v4.0) does not work for me as it requires root permission. 

This issue appears (in general form) [here](https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary). 

Is there a specific solution that will work for rMATS?

**Comment by EricKutschera** [comment]
I think the issue is that the rmats build is only looking for libraries in the regular system paths and not looking where conda installed things. You could try adding a -L argument to this line of rMATS_C/Makefile just before $(LDFLAGS): https://github.com/Xinglab/rmats-turbo/blob/bc29dc5202f9e18aed99fe7dfe6f95ad41579223/rMATS_C/Makefile#L36

`-L/path/to/conda_envs/rmats/lib`

That should resolve the ld errors if these files exist: `conda_envs/rmats/lib/libblas.so` `conda_envs/rmats/lib/liblapack.so`

**Comment by bio-scott** [comment]
Thanks for the suggestion, Eric! 

I ended up cloning an environment from someone else for now. But I will try this if I end up installing on another machine as well, and I'll update the result here. Thanks again.

**Comment by ChristianRohde** [comment]
> I think the issue is that the rmats build is only looking for libraries in the regular system paths and not looking where conda installed things. You could try adding a -L argument to this line of rMATS_C/Makefile just before $(LDFLAGS):
> 
> https://github.com/Xinglab/rmats-turbo/blob/bc29dc5202f9e18aed99fe7dfe6f95ad41579223/rMATS_C/Makefile#L36
> 
> `-L/path/to/conda_envs/rmats/lib`
> 
> That should resolve the ld errors if these files exist: `conda_envs/rmats/lib/libblas.so` `conda_envs/rmats/lib/liblapack.so`

Hi,

I can confirm that your help worked. I installed lapack, blas and cython with conda and needed to add my path with  -L just as you described. Finally rMATS is installed.

Thanks you so much!

**Comment by ChristianRohde** [comment]
Just another feedback: I started to use rMATS yesterday which I installed in December. There was one error left executing my installation very similar to https://github.com/Xinglab/rmats-turbo/issues/256. Alright, here I learned that "conda install -c conda-forge -c bioconda rmats=4.1.2" is available too :D. Before during my manual installation I even created a conda environment to solve some dependencies but I was not aware that rMATS is available from conda as well. Maybe you can add this option to install rMATS to your starting page. This would have saved a lot of time to get rMATS running. Now rMATS finished without an error...
