### ISSUE TITLE
Using rMATs with long reads only

### ISSUE THREAD

**Issue by sannalda** [Xinglab/rmats-turbo#8]
I currently only have long reads from ONT, and I want to use rMATS. I was wondering how I could use/modify the parameters to use rMATS with long reads?

**Comment by EricKutschera** [comment]
You can use rMATS on long read data with most of the default parameters. rMATS will treat long reads the same way that it treats short reads. You will likely want to use `--variable-read-length` if your reads are not all the same length. You can use the mean or the median read length for `--readLength`. The final results are not very sensitive to variations in `--readLength`

**Comment by yxing77** [comment]
The long-read data referred to here are from Oxford Nanopore, and rMATS-turbo doesn't work with ONT long-read data. We are developing a separate tool for accurate discovery and quantitation of mRNA isoforms from ONT data, which we hope to make available in coming months.

**Comment by pchamely-2** [comment]
Hi there! Has there been any updates on this effort to use rMATS with ONT data? We would like to use specifically the annotation function with our ONT data.

**Comment by EricKutschera** [comment]
We have released a new tool for long read data. See this post for more details: https://github.com/Xinglab/rmats-turbo/issues/98#issuecomment-1099257299
