### ISSUE TITLE
Missing summary.txt

### ISSUE THREAD

**Issue by ShenTTT** [Xinglab/rmats-turbo#84]
I completed the analysis using the following command:

`python /home/nus/Desktop/NGS/rmats-turbo/rmats.py --b1 '/media/nus/AMLab_Ext1/Shen/splicing/compare/P50_DS.txt' --b2 '/media/nus/AMLab_Ext1/Shen/splicing/compare/P50_WS.txt' --gtf '/media/nus/AMLab_Ext1/Shen/splicing/compare/converted.gtf' -t single --readLength 150 --variable-read-length --nthread 12 --tstat 1 --novelSS --od '/media/nus/AMLab_Ext1/Shen/splicing/compare/P50/output' --tmp '/media/nus/AMLab_Ext1/Shen/splicing/compare/P50/temp_output'`

I got a complete set of files for each type of AS event in the output folder but why the summary.txt is not there? I want to know the total number of AS events detected...

This is mentioned in the instruction so I suppose the summary file would be generated by default...
`summary.txt: Brief summary of all AS event types. Includes the total event counts and significant event counts. By default, events are counted as significant if FDR <= 0.05. The summary can be regenerated with different criteria by running rMATS_P/summary.py`

**Comment by EricKutschera** [comment]
If you installed the official 4.1.0 release from either the release page (https://github.com/Xinglab/rmats-turbo/releases) or the bioconda 4.1.0 release (https://anaconda.org/bioconda/rmats) then you are using the commit at the bottom of this page: https://github.com/Xinglab/rmats-turbo/commits/master

The summary file was added in this commit: https://github.com/Xinglab/rmats-turbo/commit/285769835193d5bb1c43687cb686f867c7bd6541 and a small update to the summary was added in this commit https://github.com/Xinglab/rmats-turbo/commit/19af556a235b78e7a8f9cc6daeac7ec7f16abe95

You can try building from the latest source code or using the docker image (https://hub.docker.com/r/xinglab/rmats/tags?page=1&ordering=last_updated) to get a more up to date version. We are planning to make a new official release eventually (hopefully soon) and update the bioconda version as mentioned in this issue: https://github.com/Xinglab/rmats-turbo/issues/82

**Comment by ShenTTT** [comment]
Thanks Eric, will try it out!

**Comment by EricKutschera** [comment]
Version 4.1.1 has been released and it will produce the summary.txt file

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> Version 4.1.1 has been released and it will produce the summary.txt file

Hi @EricKutschera Eric, could you please share an example about how to run singularity... 
````
 singularity exec \
 --bind /home/zhou/ \
 /home/zhou/raid/singularity/rmats.4.1.1.sif \
````
but I didn't find the rmats.py, could you please share a template?
Best,
JG

**Comment by EricKutschera** [comment]
`singularity run docker://xinglab/rmats:v4.1.1 {rmats arguments}` will run singularity against the docker image from https://hub.docker.com/r/xinglab/rmats/tags?page=1&ordering=last_updated

The docker images are set so that by default it will execute: `python /rmats/rmats.py {rmats arguments}`. With no arguments it will use `--help` for `{rmats arguments}`

https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/Dockerfile#L47

Here's a partial example command: `singularity run docker://xinglab/rmats:v4.1.1 --b1 b1.txt --b2 b2.txt --gtf {...}`

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @EricKutschera  it's looks worked, however, I didn't detect any AS events.
````
[zhou@localhost rmats]$ singularity run docker://xinglab/rmats:v4.1.1 \
> --b1 $b1 --b2 $b2 \
> --gtf $gtf \
> --od ${dir}/rmats/AS \
> --tmp ${dir}/rmats/AS/tmp \
> -t paired \
> --readLength 151 --cstat 0.0001 --nthread 50


INFO:    Using cached SIF image
gtf: 20.9519200325
There are 60669 distinct gene ID in the gtf file
There are 228048 distinct transcript ID in the gtf file
There are 36746 one-transcript genes in the gtf file
There are 1378888 exons in the gtf file
There are 25229 one-exon transcripts in the gtf file
There are 22486 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.758888
Average number of exons per transcript is 6.046481
Average number of exons per transcript excluding one-exon tx is 6.674222
Average number of gene per geneGroup is 8.468240
statistic: 0.0517349243164

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 744309913
NOT_EXPECTED_CIGAR: 239477436
NOT_EXPECTED_READ_LENGTH: 1170793316
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: -1409670699
total: 744909966
outcomes by BAM written to: /home/zhou/t12b/EGA/EGAD00001004183/RNA//rmats/AS/tmp/2021-04-05-22:22:46_908624_read_outcomes_by_bam.txt

novel: 34434.399688
The splicing graph and candidate read have been saved into /home/zhou/t12b/EGA/EGAD00001004183/RNA//rmats/AS/tmp/2021-04-05-22:22:46_908624_*.rmats
save: 0.0251770019531
loadsg: 0.0231578350067

==========
Done processing each gene from dictionary to compile AS events
Found 49249 exon skipping events
Found 3400 exon MX events
Found 16694 alt SS events
There are 10123 alt 3 SS events and 6571 alt 5 SS events.
Found 7022 RI events
==========

ase: 2.66019296646
count: 4.7595038414
Processing count files.
Done processing count files.
````
![image](https://user-images.githubusercontent.com/20199977/113670289-36f1df00-96b5-11eb-91fd-8d314a6ef71a.png)
![image](https://user-images.githubusercontent.com/20199977/113670338-46712800-96b5-11eb-9642-1f6eddf1b65c.png)
![image](https://user-images.githubusercontent.com/20199977/113670356-4d983600-96b5-11eb-8502-a01faf5f4136.png)
2021-04-05-22:22:46_908624_read_outcomes_by_bam.txt
![image](https://user-images.githubusercontent.com/20199977/113670409-60126f80-96b5-11eb-8541-991416752167.png)

Could you please help me to check this?
Best,
JG

**Comment by EricKutschera** [comment]
```
read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 744309913
NOT_EXPECTED_CIGAR: 239477436
NOT_EXPECTED_READ_LENGTH: 1170793316
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: -1409670699
total: 744909966
```

CLIPPED is -1,409,670,699 which seems to indicate that the 32 bit integer used to total the number of clipped reads overflowed. The overflow would happen around 2 billion alignments not used due to clipping. The overflow is not necessarily a problem since the counts are just for debugging. The counts for the individual bam files in read_outcomes_by_bam.txt should be accurate as long as each individual bam did not exceed 2 billion alignments. The counts for the first bam are

```
NOT_NH_1: 14319786 (37%)
NOT_EXPECTED_CIGAR: 430041 (1%)
NOT_EXPECTED_READ_LENGTH: 20451765 (53%)
CLIPPED: 3457874 (9%)
TOTAL_FOR_BAM: 38659466
```

The categories sum to the reported total so the counts look accurate. I added in the `(%)` for each category and it seems that read length is the main reason for the reads not being used. If you look at your bam files do the sequence lengths actually match `--readLength 151`?

`NOT_NH_1` was the reason for another 37% of those reads. That means that the reads did not have a unique alignment. That may be due to the reads themselves or to the procedure used to perform the alignment

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi Eric @EricKutschera Thanks for your comments.
I upload STAR results for one of the samples, please check those.
Best,
JG

[EGAN00001749614_Log.final.out.txt](https://github.com/Xinglab/rmats-turbo/files/6265437/EGAN00001749614_Log.final.out.txt)
[EGAN00001749614_Log.out.txt](https://github.com/Xinglab/rmats-turbo/files/6265438/EGAN00001749614_Log.out.txt)
[EGAN00001749614_Log.progress.out.txt](https://github.com/Xinglab/rmats-turbo/files/6265439/EGAN00001749614_Log.progress.out.txt)

**Comment by EricKutschera** [comment]
The Log.final.out.txt has: `Average input read length | 101` so it seems like you should use `--readLength 101`. That file also has `Uniquely mapped reads % | 85.10%` so at least for that example bam it seems like the alignment went well. I don't see anything to indicate a problem with the alignment in those log files

You can double check the read length by manually looking at the read sequences in the bam file with `samtools view {bam_file} | head`

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @EricKutschera, thanks for your reply.  I will check those, best,
JG

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @EricKutschera I re-analyses by following:

````
singularity run docker://xinglab/rmats:v4.1.1 \
--b1 $b1 --b2 $b2 \
--gtf $gtf \
--od ${dir}/rmats/AS \
--tmp ${dir}/rmats/AS/tmp \
-t paired \
--readLength 101 --cstat 0.0001 --nthread 50

````

However, still zero...

````
INFO:    Using cached SIF image
gtf: 22.6697890759
There are 60669 distinct gene ID in the gtf file
There are 228048 distinct transcript ID in the gtf file
There are 36746 one-transcript genes in the gtf file
There are 1378888 exons in the gtf file
There are 25229 one-exon transcripts in the gtf file
There are 22486 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.758888
Average number of exons per transcript is 6.046481
Average number of exons per transcript excluding one-exon tx is 6.674222
Average number of gene per geneGroup is 8.468240
statistic: 0.0345010757446

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 744309913
NOT_EXPECTED_CIGAR: 239477436
NOT_EXPECTED_READ_LENGTH: 1170793316
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: -1409670699
total: 744909966
outcomes by BAM written to: /home/zhou/t12b/EGA/EGAD00001004183/RNA//rmats/AS/tmp/2021-05-02-04:37:07_257005_read_outcomes_by_bam.txt

novel: 36493.977566
The splicing graph and candidate read have been saved into /home/zhou/t12b/EGA/EGAD00001004183/RNA//rmats/AS/tmp/2021-05-02-04:37:07_257005_*.rmats
save: 0.021959066391
loadsg: 0.0266358852386

==========
Done processing each gene from dictionary to compile AS events
Found 49249 exon skipping events
Found 3400 exon MX events
Found 16694 alt SS events
There are 10123 alt 3 SS events and 6571 alt 5 SS events.
Found 7022 RI events
==========

ase: 2.23776197433
count: 4.62951993942
Processing count files.
Done processing count files.
````
Could you please double-check this ?

**Comment by jianguozhouzunyimedicaluniversity** [comment]
````
/home/zhou/t12b/EGA/EGAD00001004183/RNA/CircRNA/STAR/EGAN00001749442_Aligned.sortedByCoord.out.bam
101
0
0
0

````

**Comment by jianguozhouzunyimedicaluniversity** [comment]
````
/home/zhou/t12b/EGA/EGAD00001004183/RNA/CircRNA/STAR/EGAN00001749442_Aligned.sortedByCoord.out.bam
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 14319786
NOT_EXPECTED_CIGAR: 430041
NOT_EXPECTED_READ_LENGTH: 20451765
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 3457874
TOTAL_FOR_BAM: 38659466
/home/zhou/t12b/EGA/EGAD00001004183/RNA/CircRNA/STAR/EGAN00001749444_Aligned.sortedByCoord.out.bam
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 66999275
NOT_EXPECTED_CIGAR: 463206
NOT_EXPECTED_READ_LENGTH: 67236268
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 8710773
TOTAL_FOR_BAM: 143409522
/home/zhou/t12b/EGA/EGAD00001004183/RNA/CircRNA/STAR/EGAN00001749284_Aligned.sortedByCoord.out.bam
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 35693310
NOT_EXPECTED_CIGAR: 646223
NOT_EXPECTED_READ_LENGTH: 62573005
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 7759808
TOTAL_FOR_BAM: 106672346
````

**Comment by EricKutschera** [comment]
The read outcomes look the same as when you used `--readLength 151` so it seems that your reads are not length 151 or 101. You can manually look at some of the alignments with `samtools view {bam_file} | head` and see what the actual read lengths are. If there isn't a consistent read length then you can run rmats with `--variable-read-length` to allow reads of any length to be used (you still need to provide a --readLength for rmats to calculate inclusion levels).

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @EricKutschera 
 
````
samtools view /home/zhou/t12b/EGA/EGAD00001004183/RNA/CircRNA/STAR/EGAN00001749440_Aligned.sortedByCoord.out.bam  | head
HWI:1:X:6:2202:16230:50947      419     chr1    12029   0       50M     =       12134   156 TGCTGGCCTGTGCCAGGGTGCAAGCTGAGCACTGGAGTGGAGTTTTCCTG       BBBB@GGGGGGGGGEGGDGGGGGGGEFGGGGGGGGGGFGGGGGGFGG=BF   NH:i:7  HI:i:6  AS:i:99 nM:i:0  NM:i:0  MD:Z:50 jM:B:c,-1       jI:B:i,-1   MC:Z:51M
HWI:1:X:6:2316:18700:10435      419     chr1    12043   0       50M     =       12680   1211AGGGTGCAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCAT       ABBBBGB@FGGGGGGGCFGDGGGDGGGFG>DFGCD>@CDGEGGGGGG/@F   NH:i:6  HI:i:5  AS:i:100        nM:i:0  NM:i:0  MD:Z:50 jM:B:c,-1       jI:B:i,-1    MC:Z:18M523N33M XS:A:+
HWI:1:X:6:2316:18700:10435      419     chr1    12043   0       50M     =       183199  171730       AGGGTGCAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCAT      ABBBBGB@FGGGGGGGCFGDGGGDGGGFG>DFGCD>@CDGEGGGGGG/@F   NH:i:6  HI:i:6  AS:i:99 nM:i:0  NM:i:0  MD:Z:50 jM:B:c,-1       jI:B:i,-1    MC:Z:18M523N33M XS:A:+
HWI:1:X:6:1111:9191:24480       419     chr1    12053   0       51M     =       12127   125 CTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGG      BBBBBGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG@GGGGGGG  NH:i:7  HI:i:6  AS:i:98 nM:i:1  NM:i:0  MD:Z:51 jM:B:c,-1       jI:B:i,-1   MC:Z:51M
HWI:1:X:6:1309:1875:11369       355     chr1    12078   1       50M     =       12210   183 GTGGAGAGGAGCCATGCCTAGAGAGGGATGGGCCATTGTTCATCTTCTGG       BB@=?>;E;1/B/;CG;;1B:FG19C/CB/0F@:BC1:BB1F1:EF111?   NH:i:3  HI:i:2  AS:i:91 nM:i:4  NM:i:1  MD:Z:23T26      jM:B:c,-1       jI:B:i,-1    MC:Z:51M
HWI:1:X:6:1111:9191:24480       339     chr1    12127   0       51M     =       12053   -125GCCCCTGTTGTCTGCATGTAATTTAATACCACAACCAGGCATAGGGGAAAG      GGGGGGGGGGGGGGGGGGGGGEGFGGGGGGGGGGGGGGGGGGGGGGCCBBC  NH:i:7  HI:i:6  AS:i:98 nM:i:1  NM:i:1  MD:Z:21C29      jM:B:c,-1       jI:B:i,-1    MC:Z:51M
HWI:1:X:6:2204:3926:68092       99      chr1    12129   0       47M     =       12220   142 CCCTGTTGTCTGCATGTAACTTAATACCACAACCAGGCATAGAGGAA  CCCCCGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG      NH:i:5  HI:i:1  AS:i:94 nM:i:1  NM:i:1  MD:Z:42G4       jM:B:c,-1       jI:B:i,-1   MC:Z:51M
HWI:1:X:6:2202:16230:50947      339     chr1    12134   0       51M     =       12029   -156TTGTCTGCATGTAACTTAATACCACAACCAGGCATAGGGGAAAGATTGGAG      GGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGCCCCB  NH:i:7  HI:i:6  AS:i:99 nM:i:0  NM:i:0  MD:Z:51 jM:B:c,-1       jI:B:i,-1   MC:Z:50M
HWI:1:X:6:1309:1875:11369       403     chr1    12210   1       51M     =       12078   -183CTCTCACAACCCAGGCCAGTAAGTAGTGCTTGTGCTAATCTCATTGGCTGT      F=;1GCGFE0=00FF=11>GDCE:1GF=1>GF@1;11E@11>110=?:333  NH:i:3  HI:i:2  AS:i:91 nM:i:4  NM:i:3  MD:Z:11T24C5C8  jM:B:c,-1       jI:B:i,-1    MC:Z:50M
HWI:1:X:6:2204:3926:68092       147     chr1    12220   0       51M     =       12129   -142CTAGGCCAGTAAGTAGTGCTTGTGCTCATCTCCTTGGCTGTGATACGTGGC      DF:@FGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGBB@BB  NH:i:5  HI:i:1  AS:i:94 nM:i:1  NM:i:0  MD:Z:51 jM:B:c,-1       jI:B:i,-1   MC:Z:47M
````
Best,
JG

**Comment by EricKutschera** [comment]
From the cigar strings (like `50M`), those reads have length from 47 to 51. Since you don't have a fixed read length you can use `--variable-read-length`

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi @EricKutschera so you mean:
````
singularity run docker://xinglab/rmats:v4.1.1 \
--b1 $b1 --b2 $b2 \
--gtf $gtf \
--od ${dir}/rmats/AS \
--tmp ${dir}/rmats/AS/tmp \
-t paired \
--variable-read-length --readLength 50 --cstat 0.0001 --nthread 50
````

**Comment by EricKutschera** [comment]
That command looks fine to me. If you are using the same `${dir}` as a previous rmats command, make sure to remove any old output before running the new command

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> That command looks fine to me. If you are using the same `${dir}` as a previous rmats command, make sure to remove any old output before running the new command

````
CLIPPED: -1409670699
total: 744909966
outcomes by BAM written to: /home/zhou/t12b/EGA/EGAD00001004183/RNA//rmats/AS/tmp/2021-05-03-23:20:24_290309_read_outcomes_by_bam.txt

novel: 34942.693141
The splicing graph and candidate read have been saved into /home/zhou/t12b/EGA/EGAD00001004183/RNA//rmats/AS/tmp/2021-05-03-23:20:24_290309_*.rmats
save: 741.071270943
loadsg: 19.8007769585

==========
Done processing each gene from dictionary to compile AS events
Found 288116 exon skipping events
Found 77501 exon MX events
Found 26437 alt SS events
There are 15752 alt 3 SS events and 10685 alt 5 SS events.
Found 7551 RI events
==========

ase: 10.2782990932
count: 1301.49507904
Processing count files.
Done processing count files.
````
worked!
thx.
