### ISSUE TITLE
report error  while performing rmats

### ISSUE THREAD

**Issue by xiangboabc** [Xinglab/rmats-turbo#87]
Hi

Sorry to disturb you.  Error report while performing rmats

Command line :
python /public/zhxiangbo/software/rmats-turbo/rmats.py --variable-read-length --nthread 4 --gtf gft_ch10 --b1 txt1 --b2 txt2 --od output --tmp output-temp

 txt1: /public/zhxiangbo/human/bam/R21008961-25R-25R_combined.uniq.sorted_10.bam,/public/zhxiangbo/human/bam/R21008962-26R-26R_combined.uniq.sorted_10.bam,/public/zhxiangbo/human/bam/R21008963-27R-27R_combined.uniq.sorted_10.bam

txt2: /public/zhxiangbo/human/bam/R21008989-58R-58R_combined.uniq.sorted_10.bam,/public/zhxiangbo/human/bam/R21008988-57R-57R_combined.uniq.sorted_10.bam,/public/zhxiangbo/human/bam/R21008986-53R-53R_combined.uniq.sorted_10.bam

Error:

 File "/public/zhxiangbo/software/rmats-turbo/rMATS_P/inclusion_level.py", line 56, in <module>
    psi2=vec2psi(inc2,skp2,effective_inclusion_length,effective_skipping_length);
  File "/public/zhxiangbo/software/rmats-turbo/rMATS_P/inclusion_level.py", line 30, in vec2psi
    psi.append(str(round(float(inc[i])/inclusion_length/(float(inc[i])/inclusion_length+float(skp[i])/skipping_length),3)));
ZeroDivisionError: float division by zero

Thank you

**Comment by EricKutschera** [comment]
It looks like your error message is similar to the one reported here: https://github.com/Xinglab/rmats-turbo/issues/28#issuecomment-664563174

If you add a value for --readLength to your command line then the error should be resolved. Even though you are using --variable-read-length, --readLength is still needed to determine IncFormLen and SkipFormLen for calculating the inclusion levels

A change is included in the latest release (v4.1.1) that provides a more helpful error message: https://github.com/Xinglab/rmats-turbo/pull/13

> ERROR: --readLength is required. An average or median --readLength can be used in combination with --variable-read-length when the reads do not have the same length
