### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by samir-watson** [Xinglab/rmats-turbo#9]
Hi, I am installing rmats on a cluster and I am having an issue with the installation where I get the following error.

![error Annotation 2020-06-14 014450](https://user-images.githubusercontent.com/63302622/84581419-e2f1d300-ade0-11ea-9eb6-805f6e88a173.png)

**Comment by EricKutschera** [comment]
The error is: `/usr/bin/ld: cannot find -llapack` which means that it cannot find the LAPACK library during compilation. You will need to install LAPACK and then try to install rmats again.
