### ISSUE TITLE
SE and MXE get empty outputs

### ISSUE THREAD

**Issue by baoyl818** [Xinglab/rmats-turbo#91]
Dear friend,

When I use rmats-turbo_v4.1.0 , I find  SE.MATS.JC.txt and MXE.MATS.JC.txt just have headline, but other files are correct. 

**My command line is : ** 
python3 /work/Software/rmats-turbo_v4.1.0/rMATS_P/FDR.py --b1 case.bam.list --b2 control.bam.list --gtf /work/Database/hg38.refseq.gtf --od /work -t paired --libType fr-unstranded --readLength 150 --nthread 10 --tstat 2 --cstat 0.0001 --tmp /work/rMats_tmp --variable-read-length --novelSS

case.bam.list : hase 56 bams from STAR
control.bam.list : has 54 bams from STAR

**The error message is : **
Traceback (most recent call last):
  File "/work/Software/rmats-turbo_v4.1.0/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/work/rMats_tmp/JC_SE/rMATS_result_P-V.txt'
paste: /work/rMats_tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/work/Software/rmats-turbo_v4.1.0/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/work/rMats_tmp/JCEC_SE/rMATS_result_P-V.txt'
paste: /work/rMats_tmp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/work/Software/rmats-turbo_v4.1.0/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/work/rMats_tmp/JC_MXE/rMATS_result_P-V.txt'
paste: /work/rMats_tmp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
Traceback (most recent call last):
  File "/work/Software/rmats-turbo_v4.1.0/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/work/rMats_tmp/JCEC_MXE/rMATS_result_P-V.txt'
paste: /work/rMats_tmp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory

When I check the  /work/rMats_tmp dir, I find that SE's rMATS_result_.txt and MXE's rMATS_result_.txt just have a head line, and have on rMATS_result_FDR.txt,rMATS_result_P-V.txt, and rMATS_result_.txt is empty.

Best
Thank you very much

**Comment by EricKutschera** [comment]
The commandline you posted starts with `python3 /work/Software/rmats-turbo_v4.1.0/rMATS_P/FDR.py`. I think you actually ran rmats.py (FDR.py does not need to be run by hand)


The error message is similar to what was reported here: https://groups.google.com/g/rmats-user-group/c/u-hw6Wzi1LA
The code has been updated here: https://github.com/Xinglab/rmats-turbo/pull/75

v4.1.1 has that code change. If you can upgrade to v4.1.1, then the error should not occur anymore

If you can't upgrade, then there is a work around. You can check the stack size limits on your machine with:
* `ulimit -Hs`: checks the hard limit (maybe unlimited)
* `ulimit -Ss`: checks the soft limit (maybe 8192)

You can then increase the limit with:
* `ulimit -Ss 16384`: sets the soft limit to 16384 (you can pick a larger value if needed)

If the stack size is large enough, then rmats will stay within the limit and complete successfully

**Comment by baoyl818** [comment]
Thanks very much !

Yes, my command line is :
python3 /work/Software/rmats-turbo_v4.1.0/rmats.py --b1 case.bam.list --b2 control.bam.list --gtf /work/Database/hg38.refseq.gtf --od /work -t paired --libType fr-unstranded --readLength 150 --nthread 10 --tstat 2 --cstat 0.0001 --tmp /work/rMats_tmp --variable-read-length --novelSS 

Best!
