### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by HamishTong** [Xinglab/rmats-turbo#94]
Hi,

I am trying to install rmats-turbo and have the following errors:

`ytong@MSI:/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1$ ./build_rmats
cd bamtools; mkdir -p build; cd build; cmake ..; make;
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build
make[1]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[2]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[  0%] Built target SharedHeaders
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[  0%] Built target AlgorithmsHeaders
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[  0%] Built target APIHeaders
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[ 38%] Built target BamTools-static
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[ 39%] Linking CXX shared library ../../../lib/libbamtools.so
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[ 76%] Built target BamTools
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[ 80%] Built target jsoncpp
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[ 85%] Built target BamTools-utils
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[3]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[ 86%] Linking CXX executable ../../../bin/bamtools
make[3]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
[100%] Built target bamtools_cmd
make[2]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
make[1]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/bamtools/build'
cd bamtools/lib; rm *.so *.so.* *.dylib
rm: cannot remove '*.dylib': No such file or directory
make: [Makefile:4: build] Error 1 (ignored)
cd rMATS_C; make;
make[1]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/rMATS_C'
cd lbfgs_scipy && make
make[2]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/rMATS_C/lbfgs_scipy'
f77 -c -O2  -c -o lbfgsb.o lbfgsb.f
f77 -c -O2  -c -o linpack.o linpack.f
f77 -c -O2  -c -o timer.o timer.f
make[2]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/rMATS_C/lbfgs_scipy'
cc -I/usr/include -Wall -O2 -msse2 -funroll-loops -fopenmp -o rMATSexe src/main.c src/myfunc.c src/util.c src/cthreadpool.c lbfgs_scipy/lbfgsb.o lbfgs_scipy/linpack.o lbfgs_scipy/timer.o -L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm -lm -lgfortran -lgsl -lgslcblas -lgomp -lblas -llapack
src/main.c: In function ‘main’:
src/main.c:107:5: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-resul ]
  107 |     fgets(str_line, MAX_LINE, ifp);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.c:111:9: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-resul ]
  111 |         fgets(str_line, MAX_LINE, ifp);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/util.c: In function ‘parse_file’:
src/util.c:241:5: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-resul ]
  241 |     fgets(title, TITLE_LEN, ifp);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make clean
make[2]: Entering directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/rMATS_C'
rm -rf util.o myfunc.o cthreadpool.o *.o src/*.o lbfgs_scipy/*.o
rm -rf rMATS.Rcheck
make[2]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/rMATS_C'
make[1]: Leaving directory '/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1/rMATS_C'
cd rMATS_pipeline; python setup.py build_ext;
running build_ext
cp `find ./rMATS_pipeline/build | grep so` .;
Loading required package: nloptr
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages(package$name, repos = repos) :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages(package$name, repos = repos) :
  unable to install packages
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘nloptr’
Execution halted`

I was not sure what went wrong in the middle, but at the bottom it seemed lacking R packages nloptr and repos. I then went to R studio trying to install these packages, but it says they are not available for the current version of R (4.0.3). 

Could someone please help? I am using Ubuntu on Windows OS.

**Comment by EricKutschera** [comment]
It looks like the main part of the build completed successfully. I think the warnings are safe to ignore.

It looks like this is the only error that actually prevented the build from completing:
```
Warning in install.packages(package$name, repos = repos) : 'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages(package$name, repos = repos) : unable to install packages
In addition: Warning message: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, : there is no package called ‘nloptr’
Execution halted
```

The R dependencies are only needed if using the `--paired-model` argument of rmats.py. If you don't need the paired model then you can build with `./build_rmats --no-paired-model`

If you do want to use the paired model then you'll need to install the R dependencies. I was able to install nloptr for R version 4.0.3 so I think that the error message `there is no package called ‘nloptr’` does not mean that the package is not available for your R version. Instead, I think it is just a result of the earlier error message `'lib = "/usr/local/lib/R/site-library"' is not writable`. Maybe R is installed under a different user (root) and so you can't install packages as your regular user. Also `repos` is not an R package. It's an argument to the `install.packages` command that says the URL of the package repository to try to install from

**Comment by HamishTong** [comment]
Thank you, Eric!
I switched to root and successfully completed the installation.
