### ISSUE TITLE
Mostly empty output

### ISSUE THREAD

**Issue by HamishTong** [Xinglab/rmats-turbo#95]
Hi,

I found a few similar issues posted but there seem to be different reasons for not having correct output. In my case it seemed that BAM files were not processed as they are supposed to. Below are the running codes:
`ytong@MSI:/mnt/c/Users/User/Downloads/rmats_turbo_v4_1_1$ python rmats.py --b1 /mnt/c/Users/User/Desktop/Project/Splicing/RF-STM/b1.txt \
mnt/c/U> --b2 /mnt/c/Users/User/Desktop/Project/Splicing/RF-STM/b2.txt \
> --gtf /mnt/c/Users/User/Desktop/Project/Splicing/gencode.v37.primary_assembly.annotation.gtf \
> -t paired --readLength 50 --nthread 4 \
> --od /mnt/c/Users/User/Desktop/Project/Splicing/RF-STM/rMATod \
> --tmp /mnt/c/Users/User/Desktop/Project/Splicing/RF-STM/tmp
gtf: 63.5786659718
There are 60710 distinct gene ID in the gtf file
There are 234552 distinct transcript ID in the gtf file
There are 36833 one-transcript genes in the gtf file
There are 1461241 exons in the gtf file
There are 25170 one-exon transcripts in the gtf file
There are 22532 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.863482
Average number of exons per transcript is 6.229923
Average number of exons per transcript excluding one-exon tx is 6.858617
Average number of gene per geneGroup is 8.498198
statistic: 0.024619102478
read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 12655048
NOT_NH_1: 62473116
NOT_EXPECTED_CIGAR: 453537
NOT_EXPECTED_READ_LENGTH: 193553280
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 16496545
total: 285631526
outcomes by BAM written to: /mnt/c/Users/User/Desktop/Project/Splicing/RF-STM/tmp/2021-03-03-17:24:43_816550_read_outcomes_by_bam.txt
novel: 223.021104097
The splicing graph and candidate read have been saved into /mnt/c/Users/User/Desktop/Project/Splicing/RF-STM/tmp/2021-03-03-17:24:43_816550_*.rmats
save: 0.0240399837494
loadsg: 0.0616619586945
Done processing each gene from dictionary to compile AS events
Found 52059 exon skipping events
Found 3824 exon MX events
Found 18472 alt SS events
There are 11183 alt 3 SS events and 7289 alt 5 SS events.
Found 8017 RI events
ase: 1.85104894638
count: 0.712628126144
Processing count files.
Done processing count files.`
I also attached the document for tmp folder.

These BAM files were generated by STAR 2.5.2a located on our institute's hpc cluster. Below are the codes I used to run STAR alignment:
`STAR --genomeDir ~/STARfiles/STARindex \
--runThreadN 15 \
--readFilesIn ./RF-STM/combined/470-06-R1.fastq.gz ./RF-STM/combined/470-06-R2.fastq.gz   \
--readFilesCommand zcat \
--outFileNamePrefix ./RF-STM/STARoutput/SA-470-06/470-06- \
--outSAMtype BAM SortedByCoordinate \
--outSAMunmapped Within \
--outSAMattributes Standard `

I would really appreciate if you could help!

[2021-03-03-172443_816550_read_outcomes_by_bam.txt](https://github.com/Xinglab/rmats-turbo/files/6079729/2021-03-03-17.24.43_816550_read_outcomes_by_bam.txt)

**Comment by EricKutschera** [comment]
Here are the read outcomes by percentage from your output:

```
67.8%: NOT_EXPECTED_READ_LENGTH: 193,553,280
21.9%: NOT_NH_1: 62,473,116
5.8%: CLIPPED: 16,496,545
4.4%: NOT_PAIRED: 12,655,048
0.2%: NOT_EXPECTED_CIGAR: 453,537
```

It seems like the read length is the main issue. In your command you used: `--readLength 50`. You could check your fastq files to see what the actual read length is

**Comment by HamishTong** [comment]
Thank you for your swift reply! You are correct, my read length was 40 and it fixed the problem by changing read length.

Thank you!

**Comment by jessicaholder1** [comment]
hello @HamishTong I was wondering how you checked the read length from your fastq files?

**Comment by EricKutschera** [comment]
A .fastq file is a text file with 4 lines per read
1. `@` followed by read ID
2. the read sequence
3. `+` potentially followed by read ID
4. the quality sequence

From https://en.wikipedia.org/wiki/FASTQ_format:
```
@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65
```

In that example the read length is 60
```
$ python3
>>> len('GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT')
60
```
