### ISSUE TITLE
The long-read data referred to here are from Oxford Nanopore, and rMATS-turbo doesn't work with ONT long-read data. We are developing a separate tool for accurate discovery and quantitation of mRNA isoforms from ONT data, which we hope to make available in coming months.

### ISSUE THREAD

**Issue by pchamely-2** [Xinglab/rmats-turbo#97]
The long-read data referred to here are from Oxford Nanopore, and rMATS-turbo doesn't work with ONT long-read data. We are developing a separate tool for accurate discovery and quantitation of mRNA isoforms from ONT data, which we hope to make available in coming months.

_Originally posted by @yxing77 in https://github.com/Xinglab/rmats-turbo/issues/8#issuecomment-644914961_

**Comment by fburdet** [comment]
Hello! Any news on the ONT long-read compatibility?

I had not seen the issue so I tried anyway. I get an output but only NOT_NH1 reads, and then 0 counts / events.

Thanks in advance to keep me posted!

**Comment by EricKutschera** [comment]
See this post that has updates about our new tool: https://github.com/Xinglab/rmats-turbo/issues/98

**Comment by fburdet** [comment]
Ah great!! Thanks a lot for the quick answer! I had missed ESPRESSO indeed. I'll check it right now.

**Comment by fburdet** [comment]
Ah but actually, I already have expression values per transcript (possibly less good than with ESPRESSO, but they still seem ok, I did them with IsoQuant)

What I'm currently interested in is really what rMATS does: get a comparison of exon skipping, retained introns, ... between 2 conditions sequenced with ONT. Reading in the issues, there doesn't seem to be a way to do that with your tools.

I'll give a try to the softwares listed in
https://github.com/Xinglab/rmats-turbo/issues/109#issuecomment-816666479
